/* DREAMFOREN INTERNAL APPROVAL · v120.29.0 */
(function(){
  'use strict';
  const BUCKET='approval-files';
  const state={docs:[],steps:[],files:[],logs:[],profiles:[],summary:'all',preset:null};
  const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const me=()=>{try{return dfCloudUser?.id||''}catch(_){return ''}}, admin=()=>{try{return String(dfCloudProfile?.role||'').toLowerCase()==='admin'}catch(_){return false}}, db=()=>{try{return dfSupabase}catch(_){return null}};
  const TYPES={general:'일반기안',quality_manual:'품질매뉴얼',quality_document:'품질문서',purchase:'구매·지출',leave:'휴가·근태',contract:'견적·계약',analysis:'시험·분석'};
  const STATUS={draft:'임시저장',submitted:'결재요청',in_review:'검토중',approved:'최종승인',rejected:'반려',cancelled:'상신취소'};
  const msg=(text,type='')=>{const e=$('dfApprovalMessage');if(e){e.className='df-approval-message '+type;e.textContent=text}};
  const person=id=>state.profiles.find(x=>x.id===id)||{};
  const fmtDate=v=>v?new Date(v).toLocaleString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'-';
  const safeName=v=>String(v||'file').replace(/[^0-9A-Za-z가-힣._-]/g,'_');

  async function load(){
    if(!db()||!me())return;msg('내부결재 문서를 불러오는 중입니다.');
    try{
      let p=await db().rpc('df_approval_people');
      if(p.error&&admin())p=await db().from('profiles').select('id,name,email,job_title,team,role').eq('active',true).order('name');
      if(p.error)throw p.error;state.profiles=(p.data||[]).map(x=>({job_title:'',...x}));
      const d=await db().from('approval_documents').select('*').order('created_at',{ascending:false});if(d.error)throw d.error;state.docs=d.data||[];
      const ids=state.docs.map(x=>x.id);state.steps=[];state.files=[];state.logs=[];
      if(ids.length){
        const [s,f,l]=await Promise.all([db().from('approval_steps').select('*').in('document_id',ids).order('step_order'),db().from('approval_attachments').select('*').in('document_id',ids),db().from('approval_audit_logs').select('*').in('document_id',ids).order('created_at')]);
        if(s.error)throw s.error;if(f.error)throw f.error;if(l.error)throw l.error;state.steps=s.data||[];state.files=f.data||[];state.logs=l.data||[];
      }
      render();msg('결재문서를 최신 상태로 불러왔습니다.','ok');window.DF_DIAG?.info('INTERNAL-APPROVAL','내부결재 동기화 완료',`문서 ${state.docs.length}건 / 내 결재대기 ${pendingMine().length}건`)
    }catch(e){msg(/approval_documents|schema cache|does not exist/i.test(e.message||'')?'내부결재 DB 설치가 필요합니다. ZIP의 22_v12028_internal_approval.sql을 먼저 실행해주세요.':'내부결재 불러오기 실패 · '+(e.message||e),'bad');$('dfApprovalList').innerHTML='<div class="df-doc-empty">내부결재 자료를 표시할 수 없습니다.</div>';window.DF_DIAG?.error('INTERNAL-APPROVAL','내부결재 불러오기 실패',e.message||String(e))}
  }
  const docSteps=id=>state.steps.filter(x=>x.document_id===id).sort((a,b)=>a.step_order-b.step_order);
  const pendingMine=()=>state.steps.filter(x=>x.approver_id===me()&&x.status==='pending');
  function render(){
    const pendingIds=new Set(pendingMine().map(x=>x.document_id));
    $('dfApprovalCountAll').textContent=state.docs.length;$('dfApprovalCountPending').textContent=pendingIds.size;$('dfApprovalCountMine').textContent=state.docs.filter(x=>x.requester_id===me()).length;$('dfApprovalCountApproved').textContent=state.docs.filter(x=>x.status==='approved').length;$('dfApprovalCountRejected').textContent=state.docs.filter(x=>x.status==='rejected').length;
    const badge=$('dfApprovalNavBadge');if(badge){badge.textContent=pendingIds.size;badge.hidden=!pendingIds.size}
    const st=$('dfApprovalStatus')?.value||'all',type=$('dfApprovalType')?.value||'all',q=($('dfApprovalSearch')?.value||'').trim().toLowerCase();
    let rows=state.docs.filter(d=>(st==='all'||d.status===st)&&(type==='all'||d.doc_type===type));
    if(state.summary==='pending')rows=rows.filter(d=>pendingIds.has(d.id));else if(state.summary==='mine')rows=rows.filter(d=>d.requester_id===me());else if(state.summary==='approved')rows=rows.filter(d=>d.status==='approved');else if(state.summary==='rejected')rows=rows.filter(d=>d.status==='rejected');
    if(q)rows=rows.filter(d=>`${d.approval_no} ${d.title} ${person(d.requester_id).name||''}`.toLowerCase().includes(q));
    $('dfApprovalList').innerHTML=rows.length?rows.map(card).join(''):'<div class="df-doc-empty">조건에 맞는 결재문서가 없습니다.</div>';
  }
  function card(d){
    const steps=docSteps(d.id),done=steps.filter(x=>x.status==='approved').length,who=person(d.requester_id),pending=steps.find(x=>x.status==='pending');
    return `<article class="df-approval-card status-${esc(d.status)}" data-ap-id="${esc(d.id)}"><div class="df-approval-card-main"><div class="df-approval-card-top"><span class="df-approval-state">${esc(STATUS[d.status]||d.status)}</span><span>${esc(TYPES[d.doc_type]||d.doc_type)}</span><small>${esc(d.approval_no)}</small></div><h2>${esc(d.title)}</h2><p>기안자 ${esc(who.name||'직원')} · ${esc(who.job_title||who.team||'직급 미지정')} · ${fmtDate(d.created_at)}</p></div><div class="df-approval-progress"><b>${done}/${steps.length}</b><span>${pending?`현재 ${esc(person(pending.approver_id).name||'결재자')} 검토`:(d.status==='approved'?'결재 완료':d.status==='rejected'?'반려 처리':'결재선 '+steps.length+'단계')}</span></div><button type="button" class="company-btn secondary" data-ap-open>상세보기</button></article>`;
  }
  function approverOptions(selected=''){return '<option value="">선택 안 함</option>'+state.profiles.map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.name||p.email)} · ${esc(p.job_title||p.team||'직급 미지정')}</option>`).join('')}
  function openForm(existing=null,preset=null){
    const own=existing?.requester_id===me(),editable=!existing||existing.status==='draft'&&own;if(!editable)return openDetail(existing.id);
    let m=$('dfApprovalFormModal');if(!m){m=document.createElement('div');m.id='dfApprovalFormModal';m.className='company-modal-backdrop';document.body.appendChild(m)}
    const oldSteps=existing?docSteps(existing.id):[],data=preset||{},type=data.doc_type||existing?.doc_type||'general';
    m.hidden=false;m.style.display='flex';m.innerHTML=`<div class="company-modal df-approval-form"><div class="company-modal-head"><div><h2>${existing?'기안문 수정':'새 기안 작성'}</h2><small>결재선을 순서대로 지정한 뒤 임시저장하거나 상신합니다.</small></div><button class="company-modal-close" data-close>×</button></div><div class="df-approval-form-grid"><label>문서종류<select id="dfApFormType" ${data.locked?'disabled':''}>${Object.entries(TYPES).map(([v,l])=>`<option value="${v}" ${v===type?'selected':''}>${l}</option>`).join('')}</select></label><label class="wide">제목<input id="dfApFormTitle" value="${esc(data.title||existing?.title||'')}"></label><label class="wide">기안내용<textarea id="dfApFormContent" placeholder="요청사항과 검토할 내용을 입력하세요.">${esc(data.content||existing?.content||'')}</textarea></label></div><section class="df-approval-line-edit"><h3>결재선</h3><div><label>1차 검토<select data-ap-step data-step-name="1차 검토">${approverOptions(oldSteps[0]?.approver_id)}</select></label><label>2차 검토<select data-ap-step data-step-name="2차 검토">${approverOptions(oldSteps[1]?.approver_id)}</select></label><label>최종 승인<select data-ap-step data-step-name="최종 승인">${approverOptions(oldSteps[2]?.approver_id)}</select></label></div><small>선택하지 않은 단계는 건너뜁니다. 동일인을 중복 지정할 수 없습니다.</small></section><label class="df-approval-files">첨부파일 <small>여러 파일 가능 · 파일당 20MB 이하</small><input id="dfApFormFiles" type="file" multiple><span id="dfApFileNames">선택된 파일이 없습니다.</span></label><div class="df-approval-form-actions"><button class="company-btn secondary" data-close>취소</button><button class="company-btn secondary" data-save>임시저장</button><button class="company-btn primary" data-submit>결재 상신</button></div></div>`;
    const close=()=>{m.hidden=true;m.style.display='none';state.preset=null};m.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);m.onclick=e=>{if(e.target===m)close()};$('dfApFormFiles').onchange=e=>{$('dfApFileNames').textContent=[...e.target.files].map(x=>x.name).join(', ')||'선택된 파일이 없습니다.'};
    m.querySelector('[data-save]').onclick=()=>saveForm(existing,data,false,m);m.querySelector('[data-submit]').onclick=()=>saveForm(existing,data,true,m);
  }
  async function saveForm(existing,preset,submit,modal){
    const title=$('dfApFormTitle').value.trim(),content=$('dfApFormContent').value.trim(),doc_type=preset.doc_type||$('dfApFormType').value,selects=[...modal.querySelectorAll('[data-ap-step]')],chosen=selects.map(x=>x.value).filter(Boolean),files=[...$('dfApFormFiles').files];
    if(!title)return alert('제목을 입력해주세요.');if(submit&&!chosen.length)return alert('결재자를 한 명 이상 지정해주세요.');if(new Set(chosen).size!==chosen.length)return alert('같은 결재자를 중복 지정할 수 없습니다.');if(files.some(f=>f.size>20*1024*1024))return alert('첨부파일은 파일당 20MB 이하만 가능합니다.');
    const btn=modal.querySelector(submit?'[data-submit]':'[data-save]');btn.disabled=true;btn.textContent=submit?'상신 중...':'저장 중...';
    try{
      let doc=existing;if(existing){const u=await db().from('approval_documents').update({title,content,doc_type,updated_at:new Date().toISOString()}).eq('id',existing.id).select().single();if(u.error)throw u.error;doc=u.data;await db().from('approval_steps').delete().eq('document_id',doc.id)}
      else{const ins=await db().from('approval_documents').insert({title,content,doc_type,requester_id:me(),quality_document_id:preset.quality_document_id||null,quality_revision:preset.quality_revision||null,quality_section_revision_id:preset.quality_section_revision_id||null,leave_request_id:preset.leave_request_id||null}).select().single();if(ins.error)throw ins.error;doc=ins.data}
      const steps=selects.filter(x=>x.value).map((x,i)=>({document_id:doc.id,step_order:i+1,step_name:x.dataset.stepName,approver_id:x.value,status:'waiting'}));if(steps.length){const s=await db().from('approval_steps').insert(steps);if(s.error)throw s.error}
      for(const file of files){const path=`${doc.id}/${crypto.randomUUID()}_${safeName(file.name)}`,up=await db().storage.from(BUCKET).upload(path,file,{contentType:file.type||'application/octet-stream'});if(up.error)throw up.error;const f=await db().from('approval_attachments').insert({document_id:doc.id,file_name:file.name,storage_path:path,mime_type:file.type||'',file_size:file.size,uploaded_by:me()});if(f.error)throw f.error}
      if(preset.leave_request_id){const lr=await db().from('leave_requests').update({approval_document_id:doc.id,status:submit?'submitted':'draft',updated_at:new Date().toISOString()}).eq('id',preset.leave_request_id);if(lr.error)throw lr.error}
      if(preset.quality_section_revision_id&&submit){const qr=await db().from('quality_section_revisions').update({status:'submitted',updated_at:new Date().toISOString()}).eq('id',preset.quality_section_revision_id);if(qr.error)throw qr.error}
      if(submit){const r=await db().rpc('df_approval_submit',{p_document:doc.id});if(r.error)throw r.error}
      modal.hidden=true;modal.style.display='none';state.preset=null;await load();msg(submit?'결재 상신이 완료되었습니다.':'기안문을 임시저장했습니다.','ok')
    }catch(e){alert((submit?'결재 상신':'임시저장')+' 실패\n'+(e.message||e));window.DF_DIAG?.error('INTERNAL-APPROVAL',submit?'결재 상신 실패':'임시저장 실패',e.message||String(e))}finally{btn.disabled=false;btn.textContent=submit?'결재 상신':'임시저장'}
  }
  async function openDetail(id){
    const d=state.docs.find(x=>x.id===id);if(!d)return;const steps=docSteps(id),files=state.files.filter(x=>x.document_id===id),logs=state.logs.filter(x=>x.document_id===id),pending=steps.find(x=>x.status==='pending'),canAct=pending&&(pending.approver_id===me()||admin());
    let m=$('dfApprovalDetailModal');if(!m){m=document.createElement('div');m.id='dfApprovalDetailModal';m.className='company-modal-backdrop';document.body.appendChild(m)}m.hidden=false;m.style.display='flex';
    m.innerHTML=`<div class="company-modal df-approval-detail"><div class="company-modal-head"><div><h2>${esc(d.title)}</h2><small>${esc(d.approval_no)} · ${esc(TYPES[d.doc_type]||d.doc_type)}</small></div><button class="company-modal-close" data-close>×</button></div><div class="df-approval-detail-meta"><span>상태 <b>${esc(STATUS[d.status]||d.status)}</b></span><span>기안자 <b>${esc(person(d.requester_id).name||'-')}</b></span><span>기안일 <b>${fmtDate(d.created_at)}</b></span>${d.quality_revision?`<span>연결 문서 <b>품질매뉴얼 Rev.${esc(d.quality_revision)}</b></span>`:''}</div><section class="df-approval-content"><h3>기안내용</h3><div>${esc(d.content).replace(/\n/g,'<br>')}</div></section><section class="df-approval-line"><h3>결재선</h3><div>${steps.map(s=>`<article class="${esc(s.status)}"><small>${esc(s.step_name)}</small><strong>${esc(person(s.approver_id).name||'결재자')}</strong><span>${esc(person(s.approver_id).job_title||person(s.approver_id).team||'')}</span><b>${s.status==='approved'?'승인':s.status==='rejected'?'반려':s.status==='pending'?'결재대기':'대기'}</b>${s.acted_at?`<time>${fmtDate(s.acted_at)}</time>`:''}${s.opinion?`<p>${esc(s.opinion)}</p>`:''}</article>`).join('')}</div></section><section class="df-approval-attachment"><h3>첨부파일</h3>${files.length?files.map(f=>`<button type="button" data-file-id="${esc(f.id)}">📎 ${esc(f.file_name)} <small>${(Number(f.file_size||0)/1024/1024).toFixed(2)}MB</small></button>`).join(''):'<p>첨부파일이 없습니다.</p>'}</section><section class="df-approval-audit"><h3>처리이력</h3>${logs.map(l=>`<p><time>${fmtDate(l.created_at)}</time><b>${esc(person(l.actor_id).name||'사용자')}</b><span>${l.action==='submitted'?'결재 상신':l.action==='approved'?'승인':l.action==='rejected'?'반려':esc(l.action)}</span></p>`).join('')||'<p>처리이력이 없습니다.</p>'}</section>${canAct?`<section class="df-approval-decision"><textarea id="dfApOpinion" placeholder="승인 또는 반려 의견을 입력하세요."></textarea><button class="company-btn danger" data-reject>반려</button><button class="company-btn primary" data-approve>승인</button></section>`:''}<div class="df-approval-detail-actions">${d.status==='draft'&&d.requester_id===me()?'<button class="company-btn primary" data-edit>기안 수정</button>':''}<button class="company-btn secondary" data-print>인쇄 / PDF</button><button class="company-btn secondary" data-close>닫기</button></div></div>`;
    const close=()=>{m.hidden=true;m.style.display='none'};m.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);m.onclick=e=>{if(e.target===m)close()};m.querySelector('[data-edit]')?.addEventListener('click',()=>{close();openForm(d)});m.querySelector('[data-print]').onclick=()=>printDoc(d,steps,logs);m.querySelector('[data-approve]')?.addEventListener('click',()=>act(d,'approve',m));m.querySelector('[data-reject]')?.addEventListener('click',()=>act(d,'reject',m));m.querySelectorAll('[data-file-id]').forEach(b=>b.onclick=()=>openFile(files.find(x=>x.id===b.dataset.fileId)));
  }
  async function act(d,action,modal){const opinion=$('dfApOpinion')?.value.trim()||'';if(action==='reject'&&!opinion)return alert('반려 사유를 입력해주세요.');if(!confirm(action==='approve'?'이 결재단계를 승인할까요?':'이 문서를 반려할까요?'))return;try{const r=await db().rpc('df_approval_act',{p_document:d.id,p_action:action,p_opinion:opinion});if(r.error)throw r.error;modal.hidden=true;modal.style.display='none';await load();msg(action==='approve'?'승인 처리가 완료되었습니다.':'반려 처리되었습니다.',action==='approve'?'ok':'warn')}catch(e){alert('결재 처리 실패\n'+(e.message||e));window.DF_DIAG?.error('INTERNAL-APPROVAL','승인·반려 처리 실패',e.message||String(e))}}
  async function openFile(file){if(!file)return;const r=await db().storage.from(BUCKET).createSignedUrl(file.storage_path,600);if(r.error)return alert('첨부파일 열기 실패\n'+r.error.message);window.open(r.data.signedUrl,'_blank','noopener')}
  function printDoc(d,steps,logs){const w=window.open('about:blank','_blank');if(!w)return alert('팝업 차단을 해제해주세요.');w.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${esc(d.approval_no)}</title><style>@page{size:A4 portrait;margin:16mm}*{box-sizing:border-box}body{font-family:'Malgun Gothic',sans-serif;color:#172f43;margin:0}header{border-bottom:3px solid #183c57;padding-bottom:12px}header h1{font-size:24px;margin:6px 0}.meta{display:grid;grid-template-columns:repeat(2,1fr);border:1px solid #aaa;margin:15px 0}.meta span{padding:7px;border:1px solid #ddd;font-size:11px}.line{display:flex;justify-content:flex-end;margin:15px 0}.line div{width:32mm;height:27mm;border:1px solid #777;text-align:center;padding:4px;font-size:10px}.line b{display:block;margin:5px}.content{min-height:130mm;border:1px solid #aaa;padding:12px;line-height:1.7;font-size:11px}.history{margin-top:14px;font-size:9px}.history p{margin:3px 0}button{position:fixed;right:12px;top:12px}@media print{button{display:none}}</style></head><body><button onclick="print()">인쇄 / PDF</button><header><small>DREAMFOREN INTERNAL APPROVAL</small><h1>${esc(d.title)}</h1><b>${esc(d.approval_no)}</b></header><div class="line">${steps.map(s=>`<div>${esc(s.step_name)}<b>${esc(person(s.approver_id).name||'')}</b>${s.status==='approved'?'승인':s.status==='rejected'?'반려':STATUS[d.status]||''}<br>${s.acted_at?esc(String(s.acted_at).slice(0,10)):''}</div>`).join('')}</div><div class="meta"><span>문서종류 <b>${esc(TYPES[d.doc_type]||d.doc_type)}</b></span><span>기안자 <b>${esc(person(d.requester_id).name||'-')}</b></span><span>기안일 <b>${fmtDate(d.created_at)}</b></span><span>상태 <b>${esc(STATUS[d.status]||d.status)}</b></span></div><section class="content">${esc(d.content).replace(/\n/g,'<br>')}</section><section class="history"><b>처리이력</b>${logs.map(l=>`<p>${fmtDate(l.created_at)} · ${esc(person(l.actor_id).name||'사용자')} · ${esc(l.action)}</p>`).join('')}</section></body></html>`);w.document.close()}
  window.dfApprovalOpenForQuality=(row,manual)=>{
    window.v62ShowOnly?.('approval');state.preset={doc_type:'quality_manual',title:`품질 매뉴얼 Rev.${row.version} 개정 승인`,content:`문서번호: DFEN-QM-00\n개정번호: Rev.${row.version}\n개정사유: ${manual?.metadata?.last_change_reason||'개정 내용 검토'}\n\n품질매뉴얼 개정 초안을 검토하고 승인하여 주시기 바랍니다.`,quality_document_id:row.id,quality_revision:row.version,locked:true};
    load().then(()=>{const duplicate=state.docs.find(x=>x.quality_document_id===row.id&&['submitted','in_review','approved'].includes(x.status));if(duplicate)openDetail(duplicate.id);else openForm(null,state.preset)})
  };
  window.dfApprovalOpenPreset=preset=>{
    window.v62ShowOnly?.('approval');state.preset=preset||{};load().then(()=>{const duplicate=state.docs.find(x=>((preset.quality_section_revision_id&&x.quality_section_revision_id===preset.quality_section_revision_id)||(preset.leave_request_id&&x.leave_request_id===preset.leave_request_id))&&['submitted','in_review','approved'].includes(x.status));if(duplicate)openDetail(duplicate.id);else openForm(null,state.preset)})
  };
  document.addEventListener('DOMContentLoaded',()=>{
    $('dfApprovalRefresh')?.addEventListener('click',load);$('dfApprovalNew')?.addEventListener('click',()=>openForm());['dfApprovalStatus','dfApprovalType'].forEach(id=>$(id)?.addEventListener('change',render));$('dfApprovalSearch')?.addEventListener('input',render);document.querySelectorAll('[data-ap-summary]').forEach(b=>b.onclick=()=>{state.summary=b.dataset.apSummary;document.querySelectorAll('[data-ap-summary]').forEach(x=>x.classList.toggle('active',x===b));render()});$('dfApprovalList')?.addEventListener('click',e=>{const card=e.target.closest('[data-ap-id]');if(card&&e.target.closest('[data-ap-open]'))openDetail(card.dataset.apId)});document.querySelector('[data-view="approval"]')?.addEventListener('click',()=>setTimeout(load,30));setTimeout(()=>{if(me())load()},1500);
  },{once:true});
})();
