/* DREAMPOEN v120.37.32.0 — 원본 HWPX 반기보고서 / 완료 성적서만 집계 */
(function(){
  "use strict";
  var VERSION="v120.37.32.0",TABLE="half_year_reports",FILES="half_year_report_files",BUCKET="quality-documents",FILTER="dreampoen_halfyear_hwpx_filters_v1";
  var options={},state={year:new Date().getFullYear(),half:new Date().getMonth()<6?1:2,query:"",filter:"all",reports:[],records:[],selected:"",current:null,files:[],busy:false,bulkBusy:false,error:"",importer:null},queues=new Map();
  function s(v){return String(v==null?"":v).trim();}function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}function copy(v){return JSON.parse(JSON.stringify(v==null?{}:v));}function id(v){return s(v&&v.Id||v&&v.id);}function by(x){return document.getElementById(x);}function root(){return by("dfHalfYearReportApp");}
  function db(){return typeof options.database==="function"?options.database():options.database|| (typeof dfSupabase!=="undefined"?dfSupabase:null);}function user(){return typeof options.currentUser==="function"?options.currentUser():options.currentUser||(typeof dfCloudUser!=="undefined"?dfCloudUser:null);}
  function allowed(action){var api=window.DFMenuPermissions;return api?api.can('halfyear-reports',action,!!user()):!!user();}
  function needAction(action){if(!allowed(action))throw new Error('반기보고서 '+({create:'작성',update:'수정',delete:'삭제',upload:'업로드'}[action]||'열람')+' 권한이 없습니다.');}
  function companies(){if(typeof options.companies==="function")return options.companies()||[];if(Array.isArray(options.companies))return options.companies;try{return (typeof dfV75SourceCompanies==="function"?dfV75SourceCompanies():companyState.db.Companies)||[];}catch(e){return [];}}
  function profileModule(){return window.DF_HALFYEAR_COMPANY;}function model(){if(!window.DF_HALFYEAR_MODEL)throw new Error("반기자료 계산 모듈을 불러오지 못했습니다. 새로고침해주세요.");return window.DF_HALFYEAR_MODEL;}
  function findCompany(companyId){return companies().find(function(c){return id(c)===s(companyId);})||null;}
  function configure(value){options=Object.assign({},options,value||{});configureProfiles();return api;}
  function configureProfiles(){var p=profileModule();if(p&&p.configure)p.configure({database:db(),currentUser:user(),companies:companies,onChanged:function(){if(state.current)refreshBuild();}});}
  function remember(){try{sessionStorage.setItem(FILTER,JSON.stringify({year:state.year,half:state.half,query:state.query,filter:state.filter}));}catch(e){}}
  function restore(){try{var a=JSON.parse(sessionStorage.getItem(FILTER)||"null");if(a){if(a.year>=2000&&a.year<=2100)state.year=Number(a.year);if(Number(a.half)===1||Number(a.half)===2)state.half=Number(a.half);state.query=s(a.query);state.filter=s(a.filter)||"all";}}catch(e){}}
  function textError(e){var m=s(e&&e.message||e);if(/halfyear_profile|PGRST202|halfyear.*function/i.test(m))return "업체·시설 반기정보 저장 업데이트(SQL 37)를 먼저 적용해주세요.";return m||"처리하지 못했습니다. 다시 확인해주세요.";}
  function notice(message,error){var el=by("hy2Notice");if(el){el.textContent=message;el.className="hy2-notice"+(error?" warning":"");}else if(message&&error)window.alert(message);}
  async function pages(table,decorate){var d=db();if(!d)throw new Error("온라인 DB에 로그인해주세요.");var result=[],from=0;for(;;from+=1000){var q=d.from(table).select("*");if(decorate)q=decorate(q);var r=await q.range(from,from+999);if(r.error)throw r.error;result=result.concat(r.data||[]);if((r.data||[]).length<1000)return result;}}
  function dateOf(r){var snap=r&&r.form_data&&r.form_data.completion_snapshot,form=snap&&snap.form||r&&r.form_data||{};return s(r&&r.measurement_date||form.sampling&&form.sampling.date).slice(0,10);}
  function inPeriod(r,year,half){var date=dateOf(r),month=Number(date.slice(5,7));return Number(date.slice(0,4))===Number(year)&&(half===1?month>=1&&month<=6:month>=7&&month<=12);}
  async function loadReports(year){return pages("measurement_reports",function(q){return q.eq("report_year",year).eq("status","issued").is("archived_at",null).order("measurement_date",{ascending:true});}).then(function(rows){return rows.filter(function(r){return !retired(r);});});}
  async function loadRecords(year,half){return pages(TABLE,function(q){return q.eq("report_year",year).eq("half_year",half).is("archived_at",null).order("company_name",{ascending:true});});}
  async function refresh(){if(state.busy)return;state.busy=true;state.error="";if(root())root().innerHTML='<div class="hy2-loading">완료 성적서와 반기 보고서를 불러오고 있습니다.</div>';try{configureProfiles();var p=profileModule(),results=await Promise.allSettled([loadReports(state.year),loadRecords(state.year,state.half),p&&p.load?p.load(true):Promise.resolve()]);if(results[0].status!=="fulfilled")throw results[0].reason;if(results[1].status!=="fulfilled")throw results[1].reason;state.reports=results[0].value.filter(function(r){return inPeriod(r,state.year,state.half);});state.records=results[1].value;if(results[2].status!=="fulfilled")state.error=textError(results[2].reason);if(state.selected)selectGroup(state.selected);else render();}catch(e){state.error=textError(e);render();}finally{state.busy=false;}}
  function groups(){var map=new Map();state.reports.filter(function(r){return !retired(r);}).forEach(function(r){var key=s(r.company_id)||"unlinked:"+s(r.company_name);if(!map.has(key))map.set(key,{key:key,name:s(r.company_name)||"업체 미지정",company:findCompany(r.company_id),reports:[],record:null});map.get(key).reports.push(r);});state.records.forEach(function(r){var key=s(r.company_id)||"unlinked:"+s(r.company_name);if(!map.has(key))map.set(key,{key:key,name:s(r.company_name),company:findCompany(r.company_id),reports:[],record:null});map.get(key).record=r;});return Array.from(map.values()).sort(function(a,b){return a.name.localeCompare(b.name,"ko",{numeric:true});});}
  function currentGroup(){return groups().find(function(g){return g.key===state.selected;});}
  function blankManual(record){var f=record&&record.form_data||{};if(f.schema_version===2)return copy(f.manual||{});var old={};["company_name","representative","manager","phone","address","authority","business_class","submit_date","submitter"].forEach(function(k){if(s(f[k]))old[k]=f[k];});if(s(f.company_address))old.address=f.company_address;if(s(f.issue_date))old.submit_date=f.issue_date;if(s(f.prepared_by))old.submitter=f.prepared_by;return old;}
  function context(group,year,half){return {company:group.company,companyId:group.key,companyName:group.name,year:year,half:half,reports:group.reports,record:group.record,manual:blankManual(group.record),dirty:false,built:null};}
  function build(ctx){var p=profileModule();return model().build({reports:ctx.reports,company:ctx.company||{},facilityProfiles:p&&p.get?p.get.bind(p):{},year:ctx.year,half:ctx.half,manual:ctx.manual});}
  function signature(built){return JSON.stringify(built.fingerprintInput||built.sources||[]);}
  function selectGroup(key){state.selected=key;var group=currentGroup();if(!group){state.selected="";state.current=null;render();return;}state.current=context(group,state.year,state.half);refreshBuild();state.files=[];render();if(state.current.record)loadFiles(state.current.record.id);}
  function refreshBuild(){if(!state.current)return;try{if(state.current.record&&state.current.record.status==='complete'&&state.current.record.form_data&&state.current.record.form_data.generated_data){state.current.built={data:copy(state.current.record.form_data.generated_data),issues:copy(state.current.record.form_data.generation_issues||[]),ready:true,sources:copy(state.current.record.form_data.source_report_ids||[])};return;}state.current.built=build(state.current);}catch(e){state.current.built={data:{measurements:[]},issues:[textError(e)],ready:false,sources:[]};}}
  function button(label,action,primary,disabled){var write=state.current&&state.current.record?'update':'create';if(action==='save')disabled=disabled||!allowed(write);if(action==='generate')disabled=disabled||!allowed(write)||!allowed('upload');if(action==='complete')disabled=disabled||!allowed('update');if(action==='delete')disabled=disabled||!allowed('delete');if(action==='import')disabled=disabled||!allowed('upload');return '<button type="button" class="hy2-btn'+(primary?' primary':'')+'" data-hy2-action="'+action+'"'+(disabled?' disabled':'')+'>'+label+'</button>';}
  function heading(){return '<header class="hy2-head"><div><div class="hy2-eyebrow">성적서작성</div><h1>반기별 자가측정결과보고서</h1><p>작성완료한 성적서를 모아 원본 한글 양식으로 만듭니다.</p></div><div class="hy2-actions">'+button("거래처DB 가져오기","import")+button("새로고침","refresh")+'</div></header>';}
  function syncPermissionUI(){var host=root();if(!host||!state.current)return;var action=state.current.record?'update':'create';if(!allowed(action))host.querySelectorAll('[data-hy2-field],[data-hy2-facility]').forEach(function(el){el.disabled=true;});if(!allowed('upload')){var input=by('hy2FinalInput');if(input)input.disabled=true;}var api=window.DFMenuPermissions;if(api&&!api.can('company','update',false))host.querySelectorAll('[data-hy2-action="save-profile"]').forEach(function(el){el.disabled=true;});}
  function render(){Promise.resolve().then(syncPermissionUI);var host=root();if(!host)return;host.innerHTML='<div class="hy2-page">'+heading()+'<div id="hy2Notice" class="hy2-notice'+(state.error?' warning':'')+'">'+esc(state.error||"성적서 작성완료 → 반기 초안 자동 갱신 → 원본 HWPX 다운로드 → 한글에서 인쇄")+'</div>'+(state.current?editorHTML():listHTML())+'</div>';bind();if(state.current){renderFiles();bindBulk();}if(state.importer)renderImport();}
  function filteredGroups(all){return all.filter(function(g){if(state.query&&[g.name,g.company&&g.company.Address].join(" ").toLowerCase().indexOf(state.query.toLowerCase())<0)return false;if(state.filter==="saved"&&!g.record)return false;if(state.filter==="complete"&&(!g.record||g.record.status!=="complete"))return false;if(state.filter==="pending"&&g.record&&g.record.status==="complete")return false;return true;});}
  function folderRowsHTML(rows){return rows.map(function(g){return '<tr><td><span class="hy2-folder-icon">▰</span><button type="button" class="hy2-company-link" data-hy2-open="'+esc(g.key)+'">'+esc(g.name)+'</button><small>'+esc(g.company&&g.company.Address||(!g.company?'업체현황 연결 확인 필요':''))+'</small></td><td>'+g.reports.length+'건</td><td><span class="hy2-badge '+(g.record&&g.record.status==='complete'?'done':'')+'">'+(g.record?(g.record.status==='complete'?'작성완료':'작성중'):'작성 전')+'</span></td><td>'+esc(g.record&&formatDate(g.record.updated_at)||'—')+'</td><td><div class="hy2-actions">'+(g.record?'<button type="button" class="hy2-btn" data-hy2-delete="'+esc(g.record.id)+'"'+(!allowed('delete')?' disabled':'')+'>삭제</button>':'')+'</div></td></tr>';}).join('');}
  function listEmptyHTML(all){return all.length?'검색 조건에 맞는 업체가 없습니다.':'이 반기에 작성완료한 성적서가 없습니다.<br><small>성적서를 저장한 후 ‘작성완료’를 눌러주세요.</small>';}
  function listHTML(){var all=groups(),rows=filteredGroups(all),years="";for(var y=state.year-3;y<=state.year+2;y++)years+='<option value="'+y+'"'+(y===state.year?' selected':'')+'>'+y+'년</option>';return '<section class="hy2-panel"><div class="hy2-toolbar"><label>대상 연도<select id="hy2Year">'+years+'</select></label><label>반기<select id="hy2Half"><option value="1"'+(state.half===1?' selected':'')+'>상반기 · 1–6월</option><option value="2"'+(state.half===2?' selected':'')+'>하반기 · 7–12월</option></select></label><label>작성상태<select id="hy2Filter"><option value="all">전체</option><option value="pending">작성중 / 작성 전</option><option value="saved">저장본 있음</option><option value="complete">작성완료</option></select></label><label class="grow">업체 검색<input id="hy2Search" type="search" value="'+esc(state.query)+'" placeholder="업체명 또는 주소"></label></div><div class="hy2-list-title"><strong>업체 폴더 <span>'+all.length+'</span></strong><small>완료 성적서 '+state.reports.length+'건 · 업체명순</small></div><div class="hy2-scroll"><table class="hy2-table folders"><thead><tr><th>업체명</th><th>완료 성적서</th><th>작성상태</th><th>수정일</th><th></th></tr></thead><tbody id="hy2FolderRows">'+folderRowsHTML(rows)+'</tbody></table></div><div id="hy2ListEmpty" class="hy2-empty"'+(rows.length?' hidden':'')+'>'+listEmptyHTML(all)+'</div></section>';}
  function bindFolderRows(){var host=by('hy2FolderRows');if(!host)return;host.querySelectorAll('[data-hy2-open]').forEach(function(b){b.onclick=function(){if(!state.busy)selectGroup(b.dataset.hy2Open);};});host.querySelectorAll('[data-hy2-delete]').forEach(function(b){b.onclick=function(){deleteReport(b.dataset.hy2Delete);};});}
  function refreshFolderRows(){var host=by('hy2FolderRows');if(!host)return;var all=groups(),rows=filteredGroups(all);host.innerHTML=folderRowsHTML(rows);var empty=by('hy2ListEmpty');if(empty){empty.hidden=!!rows.length;empty.innerHTML=listEmptyHTML(all);}bindFolderRows();}
  function formatDate(v){if(!v)return "";var d=new Date(v);return Number.isNaN(d.getTime())?s(v):d.toLocaleString("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});}
  function field(key,label,data,type){return '<label>'+label+'<input data-hy2-field="'+key+'" type="'+(type||'text')+'" value="'+esc(data[key])+'"></label>';}
  function editorHTML(){var c=state.current,b=c.built||{data:{},issues:[]},data=b.data||{},rows=data.measurements||[],done=c.record&&c.record.status==='complete';return retiredNotice(c.record)+'<div class="hy2-editor-title"><div>'+button('← 업체 목록','back')+'<h2>'+esc(c.companyName)+' <span>'+c.year+'년 '+(c.half===1?'상반기':'하반기')+'</span></h2></div><div class="hy2-actions">'+button('초안 저장','save')+button('HWPX 생성·다운로드','generate',true,!b.ready)+button(done?'작성완료 해제':'작성완료','complete',false,!c.record)+(c.record?button('보고서 삭제','delete'): '')+'</div></div>'+(done?'<div class="hy2-notice">작성완료된 보고서입니다. 새 성적서는 자동으로 덮어쓰지 않습니다. 수정하려면 작성완료를 해제해주세요.</div>':'')+'<section class="hy2-panel"><div class="hy2-section-title"><h3>업체 기본정보</h3><span>이 보고서에 적용 · 공통 기본값은 업체현황에서 수정</span></div><div class="hy2-grid">'+field('company_name','업체명',data)+field('representative','대표자',data)+field('manager','환경기술인',data)+field('phone','전화번호',data)+field('address','사업장 주소',data)+field('business_class','사업장 종별',data)+field('authority','관할 지자체',data)+field('submitter','제출인',data)+field('submit_date','제출일',data,'date')+'</div></section><section class="hy2-panel"><div class="hy2-section-title"><h3>시설별 측정결과</h3><span>완료 성적서 기준 · 일일유량 자동계산</span></div><p class="hy2-help">일일유량 = 표준상태 유량 × 시간 단위 환산 × 하루 가동시간. 시설 종별은 사업장 종별과 별도로 관리합니다.</p><div class="hy2-scroll"><table class="hy2-table measurements"><thead><tr><th>시설 / 접수번호</th><th>측정일</th><th>가동시간<br>(시간/일)</th><th>시설 종별</th><th>표준유량 기준</th><th>일일유량<br>(S㎥/일)</th><th>측정결과</th></tr></thead><tbody>'+rows.map(measurementHTML).join('')+'</tbody></table></div>'+(!rows.length?'<div class="hy2-empty">집계할 완료 성적서가 없습니다.</div>':'')+'<div class="hy2-section-foot">'+button('시설 설정을 업체현황에 반영','save-profile',false,!rows.length)+'</div></section><section class="hy2-panel"><div class="hy2-section-title"><h3>작성 확인</h3><span id="hy2ReadyLabel">'+(b.ready?'HWPX 생성 가능':'입력 또는 연결 확인 필요')+'</span></div><div id="hy2Issues">'+issuesHTML(b.issues)+'</div></section><section class="hy2-panel"><div class="hy2-section-title"><h3>생성파일 · 최종 수정본</h3><span>파일은 새 버전으로 보관합니다</span></div><div class="hy2-bulk-controls"><label>받을 파일<select id="hy2BulkScope"><option value="latest">최신 HWPX 1개</option><option value="all">모든 HWPX 버전</option></select></label><button class="hy2-btn" type="button" id="hy2BulkDownload">HWPX 일괄 다운로드</button><span id="hy2BulkStatus" role="status" aria-live="polite"></span></div><details class="hy2-upload-details"><summary>수정한 파일 보관</summary><div class="hy2-drop" id="hy2FinalDrop" tabindex="0" role="button">수정한 HWPX 또는 최종 PDF를 여기에 끌어놓기 <span>또는 파일 선택 · 최대 50MB</span><input id="hy2FinalInput" type="file" accept=".hwpx,.pdf" multiple hidden></div></details><div id="hy2FileList"></div></section>';}
  function measurementHTML(r){var fid=s(r.facility_id),manual=state.current.manual.measurements&&state.current.manual.measurements[s(r.report_id)]||{},basis=s(manual.flow_basis||r.flow_basis)||'before',unit=s(manual.flow_unit||r.flow_unit)||'S㎥/분';return '<tr data-hy2-measurement="'+esc(r.report_id)+'"><td><label>보고서 시설 표기명<textarea rows="2" aria-label="보고서 시설 표기명" data-hy2-facility="'+esc(fid)+'" data-hy2-report="'+esc(r.report_id)+'" data-hy2-key="facility_name">'+esc(r.facility_name)+'</textarea></label><small>'+esc(r.receipt_no)+'</small></td><td>'+esc(r.measurement_date)+'</td><td><input aria-label="하루 가동시간" data-hy2-facility="'+esc(fid)+'" data-hy2-key="operating_hours" type="number" min="0" max="24" step="any" value="'+esc(r.operating_hours)+'"></td><td><select aria-label="시설 종별" data-hy2-facility="'+esc(fid)+'" data-hy2-key="facility_class"><option value="">확인 필요</option>'+[1,2,3,4,5].map(function(n){return '<option value="'+n+'"'+(s(r.facility_class).replace(/종$/,'')===String(n)?' selected':'')+'>'+n+'종</option>';}).join('')+['설치면제','면제'].map(function(v){return '<option value="'+v+'"'+(s(r.facility_class)===v?' selected':'')+'>'+v+'</option>';}).join('')+'</select></td><td><select aria-label="표준유량 기준" data-hy2-facility="'+esc(fid)+'" data-hy2-report="'+esc(r.report_id)+'" data-hy2-key="flow_basis"><option value="before"'+(basis==='before'?' selected':'')+'>산소보정 전</option><option value="after"'+(basis==='after'?' selected':'')+'>산소보정 후</option></select><div class="hy2-flow"><input aria-label="표준유량" data-hy2-facility="'+esc(fid)+'" data-hy2-report="'+esc(r.report_id)+'" data-hy2-key="flow_value" value="'+esc(r.flow_value)+'"><select aria-label="표준유량 단위" data-hy2-facility="'+esc(fid)+'" data-hy2-report="'+esc(r.report_id)+'" data-hy2-key="flow_unit">'+['S㎥/분','S㎥/시간','S㎥/일'].map(function(u){return '<option'+(unit===u?' selected':'')+'>'+u+'</option>';}).join('')+'</select></div></td><td><strong data-hy2-daily-flow>'+esc(r.daily_flow||r.daily_flow===0?r.daily_flow:'—')+'</strong></td><td>'+(r.results||[]).map(function(x){return '<div>'+esc(x.item)+' <b>'+esc(x.value)+'</b> '+esc(x.unit)+'</div>';}).join('')+'</td></tr>';}
  function issuesHTML(issues){return issues&&issues.length?'<ul class="hy2-issues">'+issues.map(function(x){return '<li>'+esc(typeof x==='string'?x:x.message||x.code||JSON.stringify(x))+'</li>';}).join('')+'</ul>':'<p class="hy2-success">필수값과 단위 연결을 확인했습니다.</p>';}
  function bind(){var host=root();host.querySelectorAll('[data-hy2-action]').forEach(function(b){b.onclick=function(){action(b.dataset.hy2Action);};});bindFolderRows();if(by('hy2Year'))by('hy2Year').onchange=function(e){state.year=Number(e.target.value);remember();refresh();};if(by('hy2Half'))by('hy2Half').onchange=function(e){state.half=Number(e.target.value);remember();refresh();};if(by('hy2Filter')){by('hy2Filter').value=state.filter;by('hy2Filter').onchange=function(e){state.filter=e.target.value;remember();refreshFolderRows();};}if(by('hy2Search')){var search=by('hy2Search'),composing=false;search.addEventListener('compositionstart',function(){composing=true;});search.addEventListener('compositionend',function(e){composing=false;state.query=e.target.value;remember();refreshFolderRows();});search.oninput=function(e){state.query=e.target.value;remember();if(!composing&&!e.isComposing)refreshFolderRows();};}
    host.querySelectorAll('[data-hy2-field]').forEach(function(el){el.oninput=el.onchange=function(){state.current.manual[el.dataset.hy2Field]=el.value;state.current.dirty=true;refreshBuild();updateDerivedView();};});host.querySelectorAll('[data-hy2-facility]').forEach(function(el){el.oninput=el.onchange=function(){var c=state.current,key=el.dataset.hy2Report||el.dataset.hy2Facility,scope=el.dataset.hy2Report?'measurements':'facilities';c.manual[scope]=c.manual[scope]||{};c.manual[scope][key]=c.manual[scope][key]||{};var patch=c.manual[scope][key],field=el.dataset.hy2Key;patch[field]=el.value;if(field==='flow_value'&&!patch.flow_unit)patch.flow_unit=el.parentElement.querySelector('select').value;if(field==='flow_basis'){delete patch.flow_value;delete patch.flow_unit;}c.dirty=true;refreshBuild();updateDerivedView();};});bindDrop(by('hy2FinalDrop'),by('hy2FinalInput'),uploadFinal);if(state.current&&state.current.record&&state.current.record.status==='complete'){host.querySelectorAll('[data-hy2-field],[data-hy2-facility],#hy2FinalInput').forEach(function(el){el.disabled=true;});host.querySelectorAll('[data-hy2-action="save"],[data-hy2-action="generate"],[data-hy2-action="save-profile"]').forEach(function(el){el.disabled=true;});}}
  function updateDerivedView(){
    var host=root(),c=state.current;if(!host||!c||!c.built)return;var built=c.built,rows=built.data.measurements||[],active=document.activeElement;
    host.querySelectorAll('[data-hy2-field]').forEach(function(el){if(el!==active)el.value=s(built.data[el.dataset.hy2Field]);});
    host.querySelectorAll('[data-hy2-facility]').forEach(function(el){if(el===active)return;var rid=el.dataset.hy2Report,fid=el.dataset.hy2Facility,row=rows.find(function(r){return rid?s(r.report_id)===rid:s(r.facility_id)===fid;});if(!row)return;var key=el.dataset.hy2Key,value=row[key];if(key==='facility_class')value=s(value).replace(/종$/,'');el.value=s(value);});
    host.querySelectorAll('[data-hy2-measurement]').forEach(function(tr){var row=rows.find(function(r){return s(r.report_id)===tr.dataset.hy2Measurement;}),out=tr.querySelector('[data-hy2-daily-flow]');if(row&&out)out.textContent=row.daily_flow||row.daily_flow===0?s(row.daily_flow):'—';});
    if(by('hy2Issues'))by('hy2Issues').innerHTML=issuesHTML(built.issues);if(by('hy2ReadyLabel'))by('hy2ReadyLabel').textContent=built.ready?'HWPX 생성 가능':'입력 또는 연결 확인 필요';var generate=host.querySelector('[data-hy2-action="generate"]');if(generate)generate.disabled=!built.ready||!!(c.record&&c.record.status==='complete')||!allowed(c.record?'update':'create')||!allowed('upload');
  }
  async function action(name){if(state.busy)return;if(name==='delete')return deleteReport(state.current&&state.current.record&&state.current.record.id);if(name==='import'){if(!allowed('upload')){notice('반기보고서 업로드 권한이 없습니다.',true);return;}state.importer=state.importer||{dataset:null,matched:null,overrides:{},plan:null,message:""};renderImport();return;}if(name==='refresh'){if(state.current&&state.current.dirty&&!window.confirm('저장하지 않은 입력을 다시 불러올까요?'))return;return refresh();}if(name==='back'){if(state.current&&state.current.dirty&&!window.confirm('저장하지 않은 입력이 있습니다. 업체 목록으로 돌아갈까요?'))return;state.current=null;state.selected='';state.files=[];render();return;}state.busy=true;try{if(name==='save'){assertEditable(state.current);refreshBuild();await saveContext(state.current);render();notice('반기 초안을 저장했습니다.');}if(name==='generate'){await generateCurrent();}if(name==='complete'){await toggleComplete();}if(name==='save-profile'){await saveProfiles();}}catch(e){notice(textError(e),true);}finally{state.busy=false;}}
  async function deleteReport(recordId){
    if(state.busy)return {status:'busy'};
    var record=state.records.find(function(r){return s(r.id)===s(recordId);})||(state.current&&state.current.record&&s(state.current.record.id)===s(recordId)?state.current.record:null),locked=[];
    if(!record)return {status:'missing'};
    state.busy=true;
    try{
      needAction('delete');if(!db()||!user())throw new Error('온라인 DB에 로그인해주세요.');
      var label=s(record.company_name)+' · '+record.report_year+'년 '+(Number(record.half_year)===1?'상반기':'하반기');
      if(!window.confirm(label+' 반기보고서를 삭제할까요?\n보고서와 보관 버전은 목록에서 제외됩니다. 완료 성적서·업체정보는 유지되며, 필요하면 업체 폴더에서 새로 작성할 수 있습니다.'+(state.current&&state.current.dirty?'\n저장하지 않은 현재 입력도 닫힙니다.':'')))return {status:'cancelled'};
      var host=root();if(host)host.querySelectorAll('[data-hy2-action="delete"],[data-hy2-delete]').forEach(function(el){locked.push({el:el,disabled:el.disabled});el.disabled=true;});
      var result=await db().from(TABLE).update({archived_at:new Date().toISOString(),archived_by:user().id,updated_by:user().id}).eq('id',record.id).eq('updated_at',record.updated_at).is('archived_at',null).select('*');
      if(result.error)throw result.error;
      var archived=Array.isArray(result.data)?result.data[0]:result.data;if(!archived)throw new Error('다른 사용자가 이 보고서를 수정하거나 삭제했습니다. 현재 입력은 유지했습니다. 새로고침 후 다시 확인해주세요.');
      state.records=state.records.filter(function(r){return s(r.id)!==s(record.id);});
      if(state.current&&state.current.record&&s(state.current.record.id)===s(record.id)){state.current=null;state.selected='';state.files=[];}
      render();notice('반기보고서를 삭제했습니다. 완료 성적서가 있는 업체 폴더는 작성 전으로 남아 있으며, 열기를 눌러 새로 작성할 수 있습니다. 삭제한 보고서는 자동으로 다시 생성하지 않습니다.');
      return {status:'deleted',recordId:record.id};
    }catch(e){notice(textError(e),true);return {status:'error',message:textError(e)};}
    finally{state.busy=false;locked.forEach(function(x){if(x.el.isConnected)x.el.disabled=x.disabled||!allowed('delete');});}
  }
  function assertEditable(ctx){if(!ctx)throw new Error('업체를 먼저 선택해주세요.');if(ctx.record&&ctx.record.status==='complete')throw new Error('작성완료를 해제한 뒤 수정해주세요. 최종 파일은 그대로 보관됩니다.');}
  function rowPayload(ctx,status){var b=ctx.built||build(ctx),retirement=ctx.clearRetired?{retired_source_receipts:[],requires_source_regeneration:false}:{};return {company_id:s(ctx.company&&id(ctx.company))||null,company_name:s(b.data&&b.data.company_name)||ctx.companyName,report_year:ctx.year,half_year:ctx.half,status:status||'draft',issue_date:s(b.data&&b.data.submit_date)||null,form_data:Object.assign({},ctx.record&&ctx.record.form_data||{},{schema_version:2,manual:copy(ctx.manual),generated_data:copy(b.data),source_report_ids:copy(b.sources||[]),source_signature:signature(b),generated_signature:ctx.generatedSignature!==undefined?ctx.generatedSignature:(ctx.record&&ctx.record.form_data&&ctx.record.form_data.generated_signature||''),generation_issues:copy(b.issues||[]),built_at:new Date().toISOString()},retirement),updated_by:user().id};}
  async function saveContext(ctx,status){needAction(ctx&&ctx.record?'update':'create');if(!db()||!user())throw new Error('온라인 DB에 로그인해주세요.');var payload=rowPayload(ctx,status),q;if(ctx.record){q=db().from(TABLE).update(payload).eq('id',ctx.record.id).eq('updated_at',ctx.record.updated_at).is('archived_at',null);}else{payload.created_by=user().id;q=db().from(TABLE).insert(payload);}var r=await q.select('*');if(r.error){if(r.error.code==='23505')throw new Error('다른 사용자가 이 반기 보고서를 먼저 만들었습니다. 새로고침 후 이어서 작성해주세요.');throw r.error;}var saved=Array.isArray(r.data)?r.data[0]:r.data;if(!saved)throw new Error('다른 사용자가 보고서를 수정하거나 삭제했습니다. 현재 입력을 확인하고 새로고침 후 다시 저장해주세요.');ctx.record=saved;ctx.dirty=false;if(saved.report_year===state.year&&saved.half_year===state.half){var at=state.records.findIndex(function(x){return x.id===saved.id;});if(at<0)state.records.push(saved);else state.records[at]=saved;}return saved;}
  async function generateCurrent(){needAction('upload');var c=state.current;needAction(c&&c.record?'update':'create');assertEditable(c);refreshBuild();if(!c.built.ready)throw new Error('작성 확인에 표시된 값을 먼저 확인해주세요.');if(!window.DF_HALFYEAR_HWPX)throw new Error('HWPX 생성 모듈을 불러오지 못했습니다.');var out=await window.DF_HALFYEAR_HWPX.generate(c.built.data),blob=out&&out.blob||out,creating=!c.record;if(creating)c.generatedSignature=signature(c.built);await saveContext(c);var name=fileName(c),file=await storeFile(c.record,blob,name,'application/hwp+zip');if(!creating){c.generatedSignature=signature(c.built);c.clearRetired=!containsRetired(c.built.data);await saveContext(c);}await loadFiles(c.record.id);downloadBlob(blob,name);render();notice('원본 양식 HWPX를 생성해 보관하고 다운로드했습니다. 한글에서 인쇄해주세요.');return file;}
  function fileName(c){return (c.year+'_'+(c.half===1?'상반기':'하반기')+'_'+s(c.companyName)+'_자가측정결과보고서_'+new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14)+'.hwpx').replace(/[\\/:*?"<>|]/g,'_').slice(0,240);}
  function uuid(){return window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'_'+Math.random().toString(36).slice(2);}
  async function storeFile(record,blob,name,mime){needAction('upload');if(!blob||typeof blob.size!=='number')throw new Error('생성된 파일을 확인하지 못했습니다.');var uid=uuid(),ext=/\.pdf$/i.test(name)?'.pdf':'.hwpx',path='report-writer/half-year/'+record.id+'/'+uid+ext,d=db(),u=user(),uploaded=await d.storage.from(BUCKET).upload(path,blob,{contentType:mime||blob.type||'application/octet-stream',upsert:false});if(uploaded.error)throw uploaded.error;var payload={report_id:record.id,file_name:name,storage_path:path,mime_type:mime||blob.type||'application/octet-stream',file_size:blob.size,created_by:u.id,updated_by:u.id};var saved=await d.from(FILES).insert(payload).select('*');if(saved.error){/* Network ambiguity: retain uploaded object, never remove earlier stored files. */throw saved.error;}return Array.isArray(saved.data)?saved.data[0]:saved.data;}
  async function toggleComplete(){var c=state.current;if(!c||!c.record)return;var done=c.record.status==='complete';if(!done){if(needsRegeneration(c.record))throw Error('삭제된 접수자료를 제외한 HWPX를 먼저 새로 생성해주세요.');refreshBuild();if(!c.built.ready)throw new Error('누락값을 확인한 뒤 작성완료해주세요.');if(!s(c.built.data.submit_date)||!s(c.built.data.submitter))throw new Error('제출일과 제출인을 입력한 뒤 작성완료해주세요.');if(!state.files.length)throw new Error('HWPX 생성 또는 최종 파일 업로드 후 작성완료해주세요.');if(c.record.form_data.generated_signature!==signature(c.built))throw new Error('입력 또는 완료 성적서가 변경되었습니다. 현재 내용으로 HWPX를 다시 생성하거나 최종 수정본을 올려주세요.');}await saveContext(c,done?'draft':'complete');refreshBuild();render();notice(done?'작성완료를 해제했습니다.':'반기 보고서를 작성완료로 표시했습니다.');}
  function downloadBlob(blob,name){if(options.downloadBlob)return options.downloadBlob(blob,name);var url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},30000);}
  async function loadFiles(reportId){try{var files=await pages(FILES,function(q){return q.eq('report_id',reportId).is('archived_at',null).order('updated_at',{ascending:false});});if(state.current&&state.current.record&&state.current.record.id===reportId){state.files=files;renderFiles();}return files;}catch(e){notice(textError(e),true);return [];}}
  async function fileBlob(file){var r=await db().storage.from(BUCKET).download(file.storage_path);if(r.error)throw r.error;return r.data;}
  function renderFiles(){
    var host=by('hy2FileList');if(!host)return;
    host.innerHTML=state.files.length?'<div class="hy2-files">'+state.files.map(function(f){var preview=/\.(pdf|hwpx)$/i.test(f.file_name);return '<div class="hy2-file"><span><strong>'+esc(f.file_name)+'</strong><small>'+formatDate(f.updated_at||f.created_at)+' · '+Math.max(1,Math.round(f.file_size/1024))+' KB</small>'+(staleFile(f)?'<small class="hy2-stale-file">삭제된 접수자료가 포함될 수 있는 이전 파일 · 새 버전을 사용해주세요.</small>':'')+'</span><div class="hy2-actions">'+(preview?'<button class="hy2-btn" data-hy2-file="'+esc(f.id)+'" data-file-action="preview">미리보기 · 인쇄</button>':'')+'<button class="hy2-btn" data-hy2-file="'+esc(f.id)+'" data-file-action="download">다운로드</button></div></div>';}).join('')+'</div>':'<div class="hy2-empty">아직 보관된 파일이 없습니다.</div>';
    host.querySelectorAll('[data-hy2-file]').forEach(function(b){b.onclick=async function(){try{needAction('view');var f=state.files.find(function(x){return x.id===b.dataset.hy2File;});if(!f)throw Error('파일을 찾지 못했습니다.');if(b.dataset.fileAction==='download'){downloadBlob(await fileBlob(f),f.file_name);return;}if(/\.hwpx$/i.test(f.file_name))return openHwpxPreview(f);var preview=window.DF_QUALITY_FILE_PREVIEW;if(!preview||!preview.open)throw Error('파일 미리보기 모듈을 불러오지 못했습니다.');await preview.open({name:f.file_name,mime:f.mime_type,size:f.file_size,load:function(){return fileBlob(f);}});}catch(e){notice(textError(e),true);}};});bindBulk();
  }
  function retired(row){var api=window.DF_RECEIPT_RETIREMENT;return !!(api&&api.isRetired(row));}
  function containsRetired(data){return !!(data&&data.measurements||[]).some(retired);}
  function needsRegeneration(record){var f=record&&record.form_data||{};return !!f.requires_source_regeneration||!!(f.retired_source_receipts||[]).length;}
  function retiredNotice(record){return needsRegeneration(record)?'<div class="hy2-notice warning">삭제된 접수자료가 포함된 기존 보고서입니다. 작성완료를 해제하고 HWPX를 새로 생성해주세요. 다른 시설 자료와 이전 파일은 그대로 보관합니다.</div>':'';}
  function staleFile(file){var record=state.current&&state.current.record,f=record&&record.form_data||{},cutoff=f.retired_sources_at;var created=file.created_at||file.updated_at;return needsRegeneration(record)||!!(cutoff&&(!created||new Date(created).getTime()<=new Date(cutoff).getTime()));}
  function bulkFiles(all){var rows=state.files.filter(function(f){return !f.archived_at&&/\.hwpx$/i.test(f.file_name);}).slice().sort(function(a,b){return s(b.created_at||b.updated_at).localeCompare(s(a.created_at||a.updated_at));});return all?rows:rows.slice(0,1);}
  function bindBulk(){var button=by('hy2BulkDownload'),scope=by('hy2BulkScope'),status=by('hy2BulkStatus');if(!button||!scope)return;function count(){var n=bulkFiles(scope.value==='all').length;button.disabled=state.bulkBusy||!n;scope.disabled=state.bulkBusy;if(status)status.textContent=n+'개 HWPX';}scope.onchange=count;button.onclick=function(){downloadAllHwpx(scope.value==='all',button,status);};count();}
  async function downloadAllHwpx(all,button,status){
    if(state.bulkBusy)return;state.bulkBusy=true;var label=button&&button.textContent,scope=by('hy2BulkScope');if(button)button.disabled=true;if(scope)scope.disabled=true;
    try{needAction('view');var current=state.current,files=bulkFiles(all),zipper=window.DF_REPORT_DOWNLOADS;if(!zipper)throw Error('일괄 다운로드 구성요소를 불러오지 못했습니다. 새로고침해주세요.');if(files.some(staleFile)&&!window.confirm('삭제 접수자료가 포함될 수 있는 이전 파일도 선택되어 있습니다. 그대로 다운로드할까요?'))return;var blob=await zipper.create({files:files,load:function(file){needAction('view');return fileBlob(file);},progress:function(done,total){if(button)button.textContent=done===total?'압축 중…':'받는 중 '+done+' / '+total;if(status)status.textContent=done+' / '+total+'개';}});downloadBlob(blob,zipper.safeName(current.companyName+'_'+current.year+'_'+(current.half===1?'상반기':'하반기')+'_보고서_'+(all?'모든버전':'최신')+'.zip'));if(status)status.textContent=files.length+'개 다운로드 완료';}catch(e){notice(textError(e),true);if(status)status.textContent='다운로드 중단';}finally{state.bulkBusy=false;if(button){button.disabled=false;button.textContent=label;}if(scope)scope.disabled=false;if(button!==by('hy2BulkDownload'))bindBulk();}
  }
  var previewClose=null;
  async function openHwpxPreview(file){
    var renderer=window.DF_HWPX_PREVIEW;if(!renderer)throw Error('HWPX 미리보기 구성요소를 불러오지 못했습니다.');var blob=await fileBlob(file),view=await renderer.render(blob,{name:file.file_name});if(previewClose)previewClose();var modal=document.createElement('div');modal.id='hy2HwpxPreview';modal.className='hy2-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('data-df-modal-root','');modal.setAttribute('aria-label',file.file_name);
    modal.innerHTML='<div class="hy2-modal-card"><header><div><h2>'+esc(file.file_name)+'</h2>'+(staleFile(file)?'<p>삭제된 접수자료가 포함될 수 있는 이전 파일입니다.</p>':'')+'</div><div class="hy2-actions"><button class="hy2-btn" data-preview-print>인쇄</button><button class="hy2-btn" data-preview-download>HWPX 다운로드</button><button class="hy2-btn" data-preview-close>닫기</button></div></header><div class="hy2-modal-body"></div></div>';modal.querySelector('.hy2-modal-body').appendChild(view.element);document.body.appendChild(modal);previewClose=function(){modal.remove();view.destroy();previewClose=null;};modal.querySelector('[data-preview-close]').onclick=previewClose;modal.querySelector('[data-preview-print]').onclick=function(){Promise.resolve(view.print()).catch(function(e){window.alert(e.message||e);});};modal.querySelector('[data-preview-download]').onclick=function(){downloadBlob(blob,file.file_name);};
  }
  function bindDrop(zone,input,handler){if(!zone||!input)return;zone.onclick=function(e){if(e.target!==input)input.click();};zone.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click();}};input.onchange=function(){handler(Array.from(input.files||[]));input.value='';};['dragenter','dragover','dragleave','drop'].forEach(function(type){zone.addEventListener(type,function(e){e.preventDefault();e.stopPropagation();zone.classList.toggle('dragging',type==='dragenter'||type==='dragover');if(type==='drop')handler(Array.from(e.dataTransfer&&e.dataTransfer.files||[]));});});}
  async function uploadFinal(files){if(state.busy)return;state.busy=true;try{needAction('upload');var c=state.current;assertEditable(c);var creating=!c.record;if(creating||c.dirty)needAction(creating?'create':'update');if(!files.length)return;for(var i=0;i<files.length;i++){var f=files[i];if(!/\.(hwpx|pdf)$/i.test(f.name)||f.size>50*1024*1024)throw new Error('50MB 이하의 HWPX 또는 PDF 파일을 선택해주세요.');}if(creating||c.dirty){refreshBuild();if(creating)c.generatedSignature=signature(c.built);await saveContext(c);}for(var j=0;j<files.length;j++)await storeFile(c.record,files[j],files[j].name,/\.pdf$/i.test(files[j].name)?'application/pdf':'application/hwp+zip');if(!creating&&allowed('update')){c.generatedSignature=signature(c.built);await saveContext(c);}await loadFiles(c.record.id);render();notice('수정본을 새 파일로 보관했습니다. 기존 파일도 계속 다운로드할 수 있습니다.');}catch(e){notice(textError(e),true);}finally{state.busy=false;}}
  async function saveProfiles(){var c=state.current,p=profileModule();if(!p||!p.previewEdits)throw new Error('시설 반기정보 저장 모듈을 불러오지 못했습니다.');var edits=Object.keys(c.manual.facilities||{}).map(function(fid){var m=c.manual.facilities[fid],changes={};['operating_hours','facility_class'].forEach(function(k){if(Object.prototype.hasOwnProperty.call(m,k))changes[k]=m[k];});return {company_id:id(c.company),facility_id:fid,changes:changes};}).filter(function(x){return Object.keys(x.changes).length;});if(!edits.length)throw new Error('변경한 가동시간 또는 시설 종별이 없습니다.');var plan=await p.previewEdits(edits);state.importer={dataset:null,matched:null,overrides:{},plan:plan,message:'시설별 설정 반영',edits:true};renderImport();}
  function importApi(){var a=window.DF_HALFYEAR_IMPORT;if(!a)throw new Error('거래처DB 가져오기 모듈을 불러오지 못했습니다.');return a;}
  async function readImport(files,seed){try{needAction('upload');var current=state.importer;if(!current)return;if(!seed&&(!files||files.length!==1))throw new Error('거래처DB가 들어있는 엑셀 파일 1개를 선택해주세요.');current.message='거래처DB를 확인하고 있습니다.';renderImport();var data=seed?await importApi().loadSeed():await importApi().parseFile(files[0]);current.dataset=data;current.page=0;current.overrides={};current.matched=importApi().match(data,companies(),{});current.plan=null;current.message='업체와 시설 연결을 확인한 후 반영해주세요.';renderImport();}catch(e){if(state.importer)state.importer.message=textError(e);renderImport();}}
  function importModal(){return by('hy2ImportModal');}
  function renderImport(){var current=state.importer;if(!current)return;var modal=importModal();if(!modal){modal=document.createElement('div');modal.id='hy2ImportModal';modal.className='hy2-modal';modal.setAttribute('role','dialog');modal.setAttribute('data-df-modal-root','');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','hy2ImportTitle');document.body.appendChild(modal);}var rows=current.matched&&current.matched.rows||[],plan=current.plan,pageSize=25;current.page=Math.min(Math.max(0,Number(current.page)||0),Math.max(0,Math.ceil(rows.length/pageSize)-1));var visibleRows=rows.slice(current.page*pageSize,(current.page+1)*pageSize);
    modal.innerHTML='<div class="hy2-modal-card"><header><div><h2 id="hy2ImportTitle">거래처DB · 시설 반기정보</h2><p>엑셀의 가동시간·사업장 종별·시설 종별·지자체를 연결합니다.</p></div><button type="button" class="hy2-btn" id="hy2ImportClose">닫기</button></header><div class="hy2-modal-body">'+(!current.edits?'<div class="hy2-actions"><button type="button" class="hy2-btn" id="hy2ImportSeed">첨부한 거래처DB 불러오기</button></div><div class="hy2-drop" id="hy2ImportDrop" tabindex="0" role="button">거래처DB 엑셀 파일 끌어놓기 <span>XLSX · XLSM · XLS</span><input id="hy2ImportInput" type="file" accept=".xlsx,.xlsm,.xls" hidden></div>':'')+'<div class="hy2-notice">'+esc(current.message||'내용을 확인하기 전에는 업체현황에 반영되지 않습니다.')+'</div>'+(rows.length?'<div class="hy2-scroll"><table class="hy2-table import"><thead><tr><th>엑셀 업체 / 시설</th><th>연결할 업체</th><th>연결할 시설</th><th>가동 / 종별</th><th>확인</th></tr></thead><tbody>'+visibleRows.map(importRowHTML).join('')+'</tbody></table></div><div class="hy2-import-pages"><button type="button" class="hy2-btn" id="hy2ImportPrev"'+(current.page===0?' disabled':'')+'>이전</button><span>'+(current.page+1)+' / '+Math.ceil(rows.length/pageSize)+'쪽 · 연결 '+(current.matched.counts&&current.matched.counts.matched||0)+' / '+rows.length+'건</span><button type="button" class="hy2-btn" id="hy2ImportNext"'+((current.page+1)*pageSize>=rows.length?' disabled':'')+'>다음</button></div>':'')+(plan?planHTML(plan):'')+'</div><footer><span>'+esc(rows.length?'시설 '+rows.length+'건':'')+'</span><div class="hy2-actions">'+(current.dataset?'<button type="button" class="hy2-btn" id="hy2ImportReview">변경내용 검토</button>':'')+'<button type="button" class="hy2-btn primary" id="hy2ImportApply"'+(!plan||!plan.ready||!(plan.changes||[]).length?' disabled':'')+'>확인한 내용 업체현황에 반영</button></div></footer></div>';
    if(by('hy2ImportPrev'))by('hy2ImportPrev').onclick=function(){current.page--;renderImport();};if(by('hy2ImportNext'))by('hy2ImportNext').onclick=function(){current.page++;renderImport();};by('hy2ImportClose').onclick=function(){modal.remove();state.importer=null;};if(by('hy2ImportSeed'))by('hy2ImportSeed').onclick=function(){readImport([],true);};bindDrop(by('hy2ImportDrop'),by('hy2ImportInput'),function(files){readImport(files,false);});modal.querySelectorAll('[data-import-company]').forEach(function(el){el.onchange=function(){var key=el.dataset.importCompany;current.overrides[key]={company_id:el.value,facility_id:''};rematchImport();};});modal.querySelectorAll('[data-import-facility]').forEach(function(el){el.onchange=function(){var key=el.dataset.importFacility,row=rows.find(function(x){return x.key===key;});current.overrides[key]={company_id:row.company_id||current.overrides[key]&&current.overrides[key].company_id,facility_id:el.value};rematchImport();};});modal.querySelectorAll('[data-import-skip]').forEach(function(el){el.onchange=function(){var key=el.dataset.importSkip;current.overrides[key]=Object.assign({},current.overrides[key]||{},{skip:el.checked});rematchImport();};});if(by('hy2ImportReview'))by('hy2ImportReview').onclick=reviewImport;if(by('hy2ImportApply'))by('hy2ImportApply').onclick=applyImport;
  }
  function importRowHTML(row){var c=findCompany(row.company_id),list=c&&c.Facilities||[],sc=row.source_company||{},sf=row.source_facility||{};return '<tr><td><strong>'+esc(sc.name)+'</strong><small>'+esc(sf.name)+'</small></td><td><select data-import-company="'+esc(row.key)+'"><option value="">업체 선택</option>'+companies().map(function(x){return '<option value="'+esc(id(x))+'"'+(id(x)===s(row.company_id)?' selected':'')+'>'+esc(x.Name||x.name)+' · '+esc(x.Address||id(x))+'</option>';}).join('')+'</select></td><td><select data-import-facility="'+esc(row.key)+'"><option value="">시설 선택</option>'+list.map(function(x){return '<option value="'+esc(id(x))+'"'+(id(x)===s(row.facility_id)?' selected':'')+'>'+esc(x.FacilityName||x.Name||x.PreventionFacility||id(x))+'</option>';}).join('')+'</select></td><td>'+esc(sf.hours_per_day)+'시간/일<small>사업장 '+esc(sc.company_class||'—')+' / 시설 '+esc(sf.facility_class||'—')+'</small></td><td><span class="hy2-badge '+(row.status==='matched'?'done':'')+'">'+esc({matched:'연결됨',unmatched:'연결 필요',review:'검토 필요',skipped:'제외'}[row.status]||row.status)+'</span><small>'+esc(row.reason||'')+'</small><label class="hy2-skip"><input type="checkbox" data-import-skip="'+esc(row.key)+'"'+(row.status==='skipped'?' checked':'')+'>이번에 제외</label></td></tr>';}
  function rematchImport(){var c=state.importer;c.matched=importApi().match(c.dataset,companies(),c.overrides);c.plan=null;renderImport();}
  function planHTML(plan){return '<section class="hy2-review"><h3>반영할 변경내용 '+(plan.changes||[]).length+'건</h3>'+issuesHTML(plan.issues||[])+'<div class="hy2-scroll"><table class="hy2-table"><thead><tr><th>업체 / 시설</th><th>항목</th><th>현재값</th><th>변경값</th></tr></thead><tbody>'+(plan.changes||[]).map(function(x){return '<tr'+(x.conflict?' class="hy2-conflict"':'')+'><td>'+esc(x.companyName)+'<small>'+esc(x.facilityName)+'</small></td><td>'+esc(x.label||x.field)+'</td><td>'+esc(x.before||'—')+'</td><td>'+esc(x.after)+' '+(x.conflict?'<small>기존값 변경</small>':'')+'</td></tr>';}).join('')+'</tbody></table></div></section>';}
  async function reviewImport(){try{var c=state.importer,p=profileModule();if(!p||!p.preview)throw new Error('반기정보 저장 모듈을 불러오지 못했습니다.');c.plan=await p.preview(c.matched.rows);c.message='아래 변경내용을 확인해주세요. 기존 값과 다른 항목은 강조 표시됩니다.';renderImport();}catch(e){state.importer.message=textError(e);renderImport();}}
  async function applyImport(){var c=state.importer;if(!c||!c.plan||!c.plan.ready)return;var b=by('hy2ImportApply');if(b)b.disabled=true;try{await profileModule().apply(Object.assign({},c.plan,{confirmed:true}));c.plan=null;c.message='선택한 가동시간·종별·지자체를 업체현황에 반영했습니다.';if(state.current){refreshBuild();render();}else renderImport();}catch(e){c.message=textError(e);renderImport();}}
  async function completeOne(report,changed){if(!report||retired(report)||(!changed&&report.status!=='issued'))return {status:'ignored',message:'작성완료한 성적서만 반기자료에 반영합니다.'};var date=dateOf(report),year=Number(date.slice(0,4)),half=Number(date.slice(5,7))<=6?1:2,cid=s(report.company_id),company=findCompany(cid);if(!company||!year)return {status:'review_required',message:'성적서의 업체·시설 연결을 확인한 뒤 반기보고서를 작성해주세요.'};configureProfiles();var p=profileModule();if(p&&p.load)await p.load(true);var values=await Promise.all([loadReports(year),pages(TABLE,function(q){return q.eq('report_year',year).eq('half_year',half).eq('company_id',cid).order('updated_at',{ascending:false});})]),record=values[1].find(function(x){return !x.archived_at;});if(!record&&values[1].some(function(x){return !!x.archived_at;}))return {status:'ignored',message:'삭제한 반기보고서는 자동으로 다시 만들지 않습니다. 반기보고서 메뉴의 업체 폴더에서 새로 작성해주세요.'};if(record&&record.status==='complete')return {status:'review_required',message:'이미 작성완료된 반기보고서가 있어 자동 변경하지 않았습니다. 반기보고서에서 새 성적서를 확인해주세요.'};var rows=values[0].filter(function(x){return s(x.company_id)===cid&&inPeriod(x,year,half);});if(changed&&!record)return {status:'ignored',message:'갱신할 반기 초안이 없습니다.'};if(!allowed(record?'update':'create')||!allowed('upload'))return {status:'permission_required',message:'성적서는 저장했습니다. 반기 자동생성에는 새 반기보고서에는 작성·업로드, 기존 반기보고서에는 수정·업로드 권한이 필요합니다.'};var ctx=context({company:company,key:cid,name:s(company.Name)||s(report.company_name),reports:rows,record:record},year,half);ctx.built=build(ctx);if(record&&!needsRegeneration(record)&&record.form_data&&record.form_data.generated_signature===signature(ctx.built)&&!record.form_data.generation_issues?.length)return {status:'unchanged',message:'반기자료에 이미 반영된 완료 성적서입니다.'};var creating=!record;if(creating&&ctx.built.ready)ctx.generatedSignature=signature(ctx.built);await saveContext(ctx);if(!ctx.built.ready)return {status:'needs_input',reportId:ctx.record.id,message:'반기 초안을 자동 저장했습니다. 가동시간·종별 등 누락값은 반기보고서에서 확인해주세요.',issues:ctx.built.issues};var output=await window.DF_HALFYEAR_HWPX.generate(ctx.built.data);await storeFile(ctx.record,output.blob||output,fileName(ctx),'application/hwp+zip');if(!creating){ctx.generatedSignature=signature(ctx.built);ctx.clearRetired=!containsRetired(ctx.built.data);await saveContext(ctx);}return {status:'generated',reportId:ctx.record.id,message:'반기보고서 HWPX를 자동 생성해 보관했습니다. 반기보고서 메뉴에서 확인·다운로드해주세요.'};}
  function enqueue(report,changed){var key=s(report&&report.company_id)+'|'+dateOf(report).slice(0,4)+'|'+(Number(dateOf(report).slice(5,7))<=6?1:2),previous=queues.get(key)||Promise.resolve();var pending=previous.catch(function(){}).then(function(){return completeOne(report,changed);}).catch(function(e){return {status:'error',message:'성적서는 작성완료되었습니다. 반기자료 자동생성은 다시 확인해주세요: '+textError(e)};});queues.set(key,pending);pending.finally(function(){if(queues.get(key)===pending)queues.delete(key);});return pending;}
  function onReportCompleted(report){return enqueue(report,false);}
  function onReportChanged(report){return enqueue(report,true);}
  function open(){if(!allowed('view')){if(root())root().textContent='반기보고서 열람 권한이 없습니다.';return;}return refresh();}
  function install(){if(window.DF_REPORT_WRITER)window.DF_REPORT_WRITER.openHalfYear=open;configureProfiles();}
  var api={version:VERSION,configure:configure,open:open,onReportCompleted:onReportCompleted,onReportChanged:onReportChanged,_test:{state:state,groups:groups,context:context,saveContext:saveContext,build:build,storeFile:storeFile,selectGroup:selectGroup,signature:signature,inPeriod:inPeriod,completeOne:completeOne,render:render,deleteReport:deleteReport,readImport:readImport,action:action,generateCurrent:generateCurrent,toggleComplete:toggleComplete,uploadFinal:uploadFinal,bulkFiles:bulkFiles,downloadAllHwpx:downloadAllHwpx,renderFiles:renderFiles,rowPayload:rowPayload,needsRegeneration:needsRegeneration,staleFile:staleFile}};window.DF_HALFYEAR_REPORT=api;restore();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();

