/* DREAMFOREN LEAVE APPROVAL · v120.37.29 · integrated draft form */
(function(){
 'use strict';const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const db=()=>{try{return dfSupabase}catch(_){return null}},me=()=>{try{return dfCloudUser?.id||''}catch(_){return ''}},admin=()=>{try{return dfCloudProfile?.role==='admin'}catch(_){return false}};
 const years=date=>{if(!date)return '-';const a=new Date(date),b=new Date();let y=b.getFullYear()-a.getFullYear();if(b<new Date(b.getFullYear(),a.getMonth(),a.getDate()))y--;return `${Math.max(0,y)+1}년차`};
 const weekdays=(a,b)=>{if(!a||!b)return 0;let n=0,d=new Date(a+'T00:00:00'),e=new Date(b+'T00:00:00');while(d<=e){const w=d.getDay();if(w!==0&&w!==6)n++;d.setDate(d.getDate()+1)}return n};
 const dateDigits=v=>String(v||'').replace(/\D/g,'').slice(0,8);
 const dateMask=v=>{const d=dateDigits(v);return d.length<=4?d:d.length<=6?`${d.slice(0,4)}-${d.slice(4)}`:`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6)}`};
 const validDate=v=>{const d=dateDigits(v);if(d.length!==8)return '';const iso=`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6)}`,x=new Date(iso+'T00:00:00');return !Number.isNaN(x.getTime())&&x.getFullYear()===Number(d.slice(0,4))&&x.getMonth()+1===Number(d.slice(4,6))&&x.getDate()===Number(d.slice(6))?iso:''};
 function bindDate(input,change){input.addEventListener('input',()=>{input.value=dateMask(input.value);change?.()});input.addEventListener('blur',()=>{const ok=!input.value||validDate(input.value);input.classList.toggle('invalid',!ok);input.setCustomValidity(ok?'':'날짜 8자리를 정확히 입력해주세요. 예: 20240616')})}
 async function people(){const r=await db().rpc('df_approval_people');if(r.error)throw r.error;return r.data||[]}
 function open(){if(typeof window.dfApprovalOpenTemplate==='function')window.dfApprovalOpenTemplate('annual_leave');else alert('내부결재 양식을 불러오지 못했습니다. 새로고침 후 다시 확인해주세요.')}
 async function loadAdmin(){if(!admin())return;const list=$('dfEmployeeLeaveList'),year=Number($('dfEmployeeLeaveYear').value||new Date().getFullYear());list.innerHTML='<div class="df-employees-empty">연차현황을 불러오는 중입니다.</div>';try{const [p,l]=await Promise.all([db().from('profiles').select('id,name,email,team,job_title,hire_date,annual_leave_days').eq('active',true).order('name'),db().from('leave_ledger').select('*').eq('leave_year',year)]);if(p.error)throw p.error;if(l.error)throw l.error;list.innerHTML=(p.data||[]).map(x=>{const rows=(l.data||[]).filter(y=>y.employee_id===x.id),granted=rows.filter(y=>Number(y.days)>0).reduce((a,b)=>a+Number(b.days),0),used=-rows.filter(y=>Number(y.days)<0).reduce((a,b)=>a+Number(b.days),0),balance=granted-used;return `<article data-leave-employee="${x.id}"><div><strong>${esc(x.name||x.email)}</strong><small>${esc(x.job_title||x.team||'소속 미지정')}</small><span>근속 ${years(x.hire_date)}</span></div><label>입사일<input type="date" data-hire value="${esc(x.hire_date||'')}"></label><label>연간 기준일수<input type="number" data-policy min="0" step="0.5" value="${Number(x.annual_leave_days||15)}"></label><div class="df-leave-numbers"><span>부여 <b>${granted}</b></span><span>사용 <b>${used}</b></span><span>잔여 <b>${balance}</b></span></div><button class="company-btn secondary" data-profile-save>기본정보 저장</button><button class="company-btn primary" data-grant>${year}년 기준일수 부여</button></article>`}).join('')||'<div class="df-employees-empty">사용 중인 직원이 없습니다.</div>';list.querySelectorAll('[data-leave-employee]').forEach(card=>{card.querySelector('[data-profile-save]').onclick=()=>saveProfile(card);card.querySelector('[data-grant]').onclick=()=>grant(card,year)})}catch(e){list.innerHTML=`<div class="df-employees-empty">연차관리 DB를 불러오지 못했습니다.<br>${esc(e.message||e)}</div>`}}
 async function saveProfile(card){const id=card.dataset.leaveEmployee,q=await db().from('profiles').update({hire_date:card.querySelector('[data-hire]').value||null,annual_leave_days:Number(card.querySelector('[data-policy]').value||0)}).eq('id',id);if(q.error)return alert(q.error.message);alert('입사일과 연차기준을 저장했습니다.');loadAdmin()}
 async function grant(card,year){const id=card.dataset.leaveEmployee,days=Number(card.querySelector('[data-policy]').value||0);if(!days||!confirm(`${year}년 연차 ${days}일을 부여할까요?\n이미 부여한 기록이 있다면 추가 부여됩니다.`))return;const q=await db().from('leave_ledger').insert({employee_id:id,leave_year:year,entry_type:'grant',days,note:`${year}년 관리자 연차 부여`,created_by:me()});if(q.error)return alert('연차 부여 실패\n'+q.error.message);loadAdmin()}
 document.addEventListener('DOMContentLoaded',()=>{$('dfLeaveNew')?.addEventListener('click',open);const y=$('dfEmployeeLeaveYear');const now=new Date().getFullYear();if(!y)return;y.innerHTML=[now-1,now,now+1].map(v=>`<option ${v===now?'selected':''}>${v}</option>`).join('');document.querySelectorAll('[data-employee-tab]').forEach(b=>b.onclick=()=>{const leave=b.dataset.employeeTab==='leave';$('dfEmployeeAccountsPanel').hidden=leave;$('dfEmployeeLeavePanel').hidden=!leave;document.querySelectorAll('[data-employee-tab]').forEach(x=>x.className='company-btn '+(x===b?'primary':'secondary'));if(leave)loadAdmin()});$('dfEmployeeLeaveRefresh').onclick=loadAdmin;y.onchange=loadAdmin},{once:true})
})();
