// DREAMFOREN v120.24 profile, dashboard attachments and corporate portal
(function(){
  'use strict';
  const BUCKET='dashboard-attachments',esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const titles=['대표이사','사장','이사','부장','차장','과장','대리','주임','사원'];
  let boardFiles=[];

  function refreshSession(){const p=dfCloudProfile;if(!p)return;const name=document.getElementById('dfUserSessionName'),title=document.getElementById('dfUserSessionTitle'),avatar=document.getElementById('dfProfileAvatar');if(name)name.textContent=p.name||p.email||'사용자';if(title)title.textContent=[p.job_title,p.team].filter(Boolean).join(' · ')||'프로필 보기';if(avatar)avatar.textContent=(p.name||'사').trim().slice(0,1)}
  const showSessionBase=dfShowSession;dfShowSession=function(){showSessionBase();refreshSession()};

  function profileModal(){let modal=document.getElementById('dfProfileModal');if(!modal){modal=document.createElement('div');modal.id='dfProfileModal';modal.className='company-modal-backdrop';modal.hidden=true;modal.innerHTML=`<div class="company-modal df-profile-modal"><div class="company-modal-head"><div><h2>내 프로필</h2><small>업무용 연락처를 관리합니다.</small></div><button class="company-modal-close" data-profile-close>×</button></div><div class="df-profile-form"><label>이름<input id="dfProfileName"></label><label>직급 <input id="dfProfileJob" readonly></label><label>전화번호<input id="dfProfilePhone" type="tel" placeholder="010-0000-0000"></label><label>연락 이메일<input id="dfProfileEmail" type="email" placeholder="name@example.com"></label><div class="df-profile-note">직급은 관리자가 직원관리에서만 부여할 수 있습니다. 이메일은 프로필 연락용이며 로그인 아이디는 변경되지 않습니다.</div><div class="df-doc-editor-actions"><button class="company-btn secondary" data-profile-close>취소</button><button class="company-btn primary" id="dfProfileSave">프로필 저장</button></div></div></div>`;document.body.appendChild(modal);modal.querySelectorAll('[data-profile-close]').forEach(b=>b.onclick=()=>{modal.hidden=true;modal.style.display='none'});modal.onclick=e=>{if(e.target===modal){modal.hidden=true;modal.style.display='none'}};document.getElementById('dfProfileSave').onclick=saveProfile}return modal}
  function openProfile(){if(!dfCloudProfile)return;const m=profileModal();document.getElementById('dfProfileName').value=dfCloudProfile.name||'';document.getElementById('dfProfileJob').value=dfCloudProfile.job_title||'미지정';document.getElementById('dfProfilePhone').value=dfCloudProfile.phone||'';document.getElementById('dfProfileEmail').value=dfCloudProfile.email||dfCloudUser?.email||'';m.hidden=false;m.style.display='flex'}
  async function saveProfile(){const b=document.getElementById('dfProfileSave'),payload={name:document.getElementById('dfProfileName').value.trim(),phone:document.getElementById('dfProfilePhone').value.trim(),email:document.getElementById('dfProfileEmail').value.trim()};if(!payload.name)return alert('이름을 입력해주세요.');b.disabled=true;b.textContent='저장 중...';try{const {data,error}=await dfSupabase.from('profiles').update(payload).eq('id',dfCloudUser.id).select('id,name,email,phone,job_title,role,team,active,board_permissions,access_permissions').single();if(error)throw error;dfCloudProfile=data;refreshSession();document.getElementById('dfProfileModal').hidden=true;document.getElementById('dfProfileModal').style.display='none';await dfHomeLoad();alert('프로필을 저장했습니다.')}catch(e){alert('프로필 저장 실패\n'+(e.message||e))}finally{b.disabled=false;b.textContent='프로필 저장'}}

  function fileNames(){const box=document.getElementById('dfBoardFileNames');if(box)box.textContent=boardFiles.length?boardFiles.map(f=>`${f.name} (${(f.size/1024/1024).toFixed(1)}MB)`).join(' · '):'선택된 파일이 없습니다.'}
  const openWriteBase=dfV1129OpenBoardWrite;dfV1129OpenBoardWrite=function(cat){openWriteBase(cat);boardFiles=[];const input=document.getElementById('dfBoardFiles'),field=document.getElementById('dfBoardFileField'),list=document.getElementById('dfBoardAttachments');if(input){input.value='';input.disabled=false}if(field)field.hidden=false;if(list){list.hidden=true;list.innerHTML=''}fileNames()};
  const openReadBase=dfV1129OpenBoardRead;dfV1129OpenBoardRead=function(post){openReadBase(post);const field=document.getElementById('dfBoardFileField'),list=document.getElementById('dfBoardAttachments'),files=Array.isArray(post.attachments)?post.attachments:[];if(field)field.hidden=true;if(list){list.hidden=!files.length;list.innerHTML=files.length?'<b>첨부파일</b>'+files.map((f,i)=>`<button type="button" data-board-download="${i}">📎 ${esc(f.name||'첨부파일')}</button>`).join(''):'';list._files=files}};
  const renderPostsBase=dfHomeRenderPosts;dfHomeRenderPosts=function(cat,rows){renderPostsBase(cat,rows);const map={notice:'dfHomeNotice',method:'dfHomeMethod',board:'dfHomeBoard'},box=document.getElementById(map[cat]);box?.querySelectorAll('[data-home-open]').forEach(button=>{const post=(box._posts||[]).find(x=>String(x.id)===String(button.dataset.homeOpen));if(Array.isArray(post?.attachments)&&post.attachments.length){const title=button.querySelector('.df-board-title');if(title)title.insertAdjacentHTML('beforeend',` <small class="df-board-file-count">📎 ${post.attachments.length}</small>`)}})};
  async function uploadFiles(){const saved=[];for(const file of boardFiles){const path=`${dfCloudUser.id}/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID?.()||Date.now()}_${file.name.replace(/[^0-9A-Za-z._-]/g,'_')}`,q=await dfSupabase.storage.from(BUCKET).upload(path,file,{contentType:file.type||'application/octet-stream'});if(q.error)throw q.error;saved.push({name:file.name,path,mime:file.type||'',size:file.size})}return saved}
  dfV1129BoardSave=async function(){if(dfV1129BoardMode!=='write')return;const title=document.getElementById('dfBoardTitle')?.value.trim()||'',content=document.getElementById('dfBoardContent')?.value.trim()||'';if(!title)return alert('제목을 입력해주세요.');if(!dfSupabase||!dfCloudUser)return alert('온라인 DB에 연결되어 있지 않습니다.');const b=document.getElementById('dfBoardSave');b.disabled=true;b.textContent=boardFiles.length?'첨부파일 저장 중...':'등록 중...';let attachments=[];try{attachments=await uploadFiles();const {error}=await dfSupabase.from(DF_HOME_POST_TABLE).insert({category:dfV1129BoardCat,title,content,attachments,created_by:dfCloudUser.id});if(error)throw error;dfV1129CloseBoardModal();await dfHomeLoad();alert('게시글을 등록했습니다.')}catch(e){if(attachments.length)await dfSupabase.storage.from(BUCKET).remove(attachments.map(x=>x.path));alert('게시글 등록 실패\n'+(e.message||e))}finally{b.disabled=false;b.textContent='등록'}};
  dfHomeLoad=async function(){const welcome=document.getElementById('dfHomeWelcome');if(welcome)welcome.textContent=`${dfCloudProfile?.name||'사용자'}님, 오늘의 공지와 측정 진행상황입니다.`;dfHomeRenderProgress();if(!dfSupabase||!dfCloudUser){['notice','method','board'].forEach(c=>dfHomeRenderPosts(c,[]));return}try{const {data,error}=await dfSupabase.from(DF_HOME_POST_TABLE).select('id,category,title,content,attachments,created_at,created_by').order('created_at',{ascending:false}).limit(60);if(error)throw error;['notice','method','board'].forEach(c=>dfHomeRenderPosts(c,data||[]))}catch(e){const msg=e.message?.includes('attachments')?'20_v12024_profile_board_attachments.sql 설치가 필요합니다.':'게시판을 불러오지 못했습니다: '+e.message;['dfHomeNotice','dfHomeMethod','dfHomeBoard'].forEach(id=>{const x=document.getElementById(id);if(x)x.innerHTML=`<div class="df-home-empty">${esc(msg)}</div>`})}};

  if(typeof dfEmployeesFetch==='function')dfEmployeesFetch=async function(){if(!dfSupabase)throw Error('온라인 DB에 연결되어 있지 않습니다.');if(!dfV68IsAdmin())throw Error('관리자만 직원관리를 사용할 수 있습니다.');const {data,error}=await dfSupabase.from('profiles').select('id,name,email,phone,job_title,role,team,active,board_permissions,access_permissions').order('active',{ascending:true}).order('name',{ascending:true});if(error)throw error;return data||[]};
  if(typeof dfEmployeesRender==='function'){const base=dfEmployeesRender;dfEmployeesRender=function(rows){base(rows);document.querySelectorAll('[data-employee-id]').forEach(card=>{const row=rows.find(x=>String(x.id)===card.dataset.employeeId);if(!row||card.querySelector('[data-emp-title]'))return;const field=document.createElement('div');field.className='df-employee-field';field.innerHTML=`<label>직급</label><select data-emp-title><option value="">미지정</option>${titles.map(t=>`<option value="${t}" ${row.job_title===t?'selected':''}>${t}</option>`).join('')}</select>`;card.querySelector('.df-access-details')?.before(field)})}};
  if(typeof dfEmployeesSaveCard==='function'){const base=dfEmployeesSaveCard;dfEmployeesSaveCard=async function(card,id,approve){const job=card.querySelector('[data-emp-title]')?.value||null;await base(card,id,approve);const {error}=await dfSupabase.from('profiles').update({job_title:job}).eq('id',id);if(error)return dfEmployeesMsg('직급 저장 실패: '+error.message,'bad');dfEmployeesMsg(approve?'승인과 직급을 저장했습니다.':'권한과 직급을 저장했습니다.','ok');await dfEmployeesLoad()}};

  document.addEventListener('DOMContentLoaded',()=>{document.getElementById('dfProfileOpen')?.addEventListener('click',openProfile);document.getElementById('dfBoardFiles')?.addEventListener('change',e=>{const files=[...e.target.files];if(files.length>5)return alert('첨부파일은 최대 5개까지 선택할 수 있습니다.');if(files.some(f=>f.size>20*1024*1024))return alert('파일당 20MB 이하만 첨부할 수 있습니다.');boardFiles=files;fileNames()});setTimeout(refreshSession,900);window.DF_DIAG?.info('PORTAL-12024','프로필·게시판 첨부·기관배너 준비 완료')},{once:true});
  document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-board-download]');if(b){const f=b.closest('#dfBoardAttachments')?._files?.[Number(b.dataset.boardDownload)];if(!f)return;try{const {data,error}=await dfSupabase.storage.from(BUCKET).createSignedUrl(f.path,300);if(error)throw error;window.open(data.signedUrl,'_blank','noopener')}catch(err){alert('첨부파일 열기 실패\n'+(err.message||err))}return}if(e.target.closest?.('#dfBoardDelete')){const files=Array.isArray(dfV1129BoardPost?.attachments)?dfV1129BoardPost.attachments:[];if(files.length)dfSupabase.storage.from(BUCKET).remove(files.map(x=>x.path)).then(({error})=>{if(error)window.DF_DIAG?.warn('BOARD-FILE-DELETE','첨부파일 정리 실패',error.message)})}},true);
})();
