// DREAMFOREN v120.24 profile, dashboard attachments and corporate portal
(function(){
  'use strict';
  const BUCKET='dashboard-attachments',esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const titles=['대표이사','사장','이사','부장','차장','과장','대리','주임','사원'];
  let boardFiles=[];

  function refreshSession(){const p=dfCloudProfile;if(!p)return;const set=(id,value)=>{const x=document.getElementById(id);if(x)x.textContent=value||'-'};set('dfUserSessionTitle',p.job_title||'미지정');set('dfUserSessionName',p.name||'사용자');set('dfUserSessionPhone',p.phone||'-');set('dfUserSessionEmail',p.email||dfCloudUser?.email||'-');const box=document.getElementById('dfUserSession'),badge=document.getElementById('dfRoleBadge');if(box&&badge&&badge.nextElementSibling!==box)badge.insertAdjacentElement('afterend',box)}
  const showSessionBase=dfShowSession;dfShowSession=function(){showSessionBase();refreshSession()};

  function profileModal(){let modal=document.getElementById('dfProfileModal');if(!modal){modal=document.createElement('div');modal.id='dfProfileModal';modal.className='company-modal-backdrop';modal.hidden=true;modal.innerHTML=`<div class="company-modal df-profile-modal"><div class="company-modal-head"><div><h2>내 프로필</h2><small>업무용 연락처를 관리합니다.</small></div><button class="company-modal-close" data-profile-close>×</button></div><div class="df-profile-form"><label>이름<input id="dfProfileName"></label><label>직급 <input id="dfProfileJob" readonly></label><label>전화번호<input id="dfProfilePhone" type="tel" placeholder="010-0000-0000"></label><label>연락 이메일<input id="dfProfileEmail" type="email" placeholder="name@example.com"></label><div class="df-profile-note">직급은 관리자가 직원관리에서만 부여할 수 있습니다. 이메일은 프로필 연락용이며 로그인 아이디는 변경되지 않습니다.</div><div class="df-doc-editor-actions"><button class="company-btn secondary" data-profile-close>취소</button><button class="company-btn primary" id="dfProfileSave">프로필 저장</button></div></div></div>`;document.body.appendChild(modal);modal.querySelectorAll('[data-profile-close]').forEach(b=>b.onclick=()=>{modal.hidden=true;modal.style.display='none'});modal.onclick=e=>{if(e.target===modal){modal.hidden=true;modal.style.display='none'}};document.getElementById('dfProfileSave').onclick=saveProfile}return modal}
  function openProfile(){if(!dfCloudProfile)return;const m=profileModal();document.getElementById('dfProfileName').value=dfCloudProfile.name||'';document.getElementById('dfProfileJob').value=dfCloudProfile.job_title||'미지정';document.getElementById('dfProfilePhone').value=dfCloudProfile.phone||'';document.getElementById('dfProfileEmail').value=dfCloudProfile.email||dfCloudUser?.email||'';m.hidden=false;m.style.display='flex'}
  async function saveProfile(){const b=document.getElementById('dfProfileSave'),payload={name:document.getElementById('dfProfileName').value.trim(),phone:document.getElementById('dfProfilePhone').value.trim(),email:document.getElementById('dfProfileEmail').value.trim()};if(!payload.name)return alert('이름을 입력해주세요.');b.disabled=true;b.textContent='저장 중...';try{const {data,error}=await dfSupabase.from('profiles').update(payload).eq('id',dfCloudUser.id).select('id,name,email,phone,job_title,role,team,active,board_permissions,access_permissions').single();if(error)throw error;dfCloudProfile=data;refreshSession();document.getElementById('dfProfileModal').hidden=true;document.getElementById('dfProfileModal').style.display='none';await dfHomeLoad();alert('프로필을 저장했습니다.')}catch(e){alert('프로필 저장 실패\n'+(e.message||e))}finally{b.disabled=false;b.textContent='프로필 저장'}}

  function fileNames(){const box=document.getElementById('dfBoardFileNames');if(box)box.textContent=boardFiles.length?boardFiles.map(f=>`${f.name} (${(f.size/1024/1024).toFixed(1)}MB)`).join(' · '):'선택된 파일이 없습니다.'}
  const openWriteBase=dfV1129OpenBoardWrite;dfV1129OpenBoardWrite=function(cat){openWriteBase(cat);boardFiles=[];const input=document.getElementById('dfBoardFiles'),field=document.getElementById('dfBoardFileField'),list=document.getElementById('dfBoardAttachments');if(input){input.value='';input.disabled=false}if(field)field.hidden=false;if(list){list.hidden=true;list.innerHTML=''}fileNames()};
  const openReadBase=dfV1129OpenBoardRead;dfV1129OpenBoardRead=function(post){openReadBase(post);const field=document.getElementById('dfBoardFileField'),list=document.getElementById('dfBoardAttachments'),files=Array.isArray(post.attachments)?post.attachments:[];if(field)field.hidden=true;if(list){list.hidden=!files.length;list.innerHTML=files.length?'<b>첨부파일</b>'+files.map((f,i)=>`<button type="button" data-board-download="${i}">📎 ${esc(f.name||'첨부파일')}</button>`).join(''):'';list._files=files}};
  const renderPostsBase=dfHomeRenderPosts;dfHomeRenderPosts=function(cat,rows){renderPostsBase(cat,rows);const map={notice:'dfHomeNotice',method:'dfHomeMethod',board:'dfHomeBoard'},box=document.getElementById(map[cat]);box?.querySelectorAll('[data-home-open]').forEach(button=>{const post=(box._posts||[]).find(x=>String(x.id)===String(button.dataset.homeOpen));if(Array.isArray(post?.attachments)&&post.attachments.length){const title=button.querySelector('.df-board-title');if(title)title.insertAdjacentHTML('beforeend',` <small class="df-board-file-count">📎 ${post.attachments.length}</small>`)}})};
  async function uploadFiles(){const saved=[];for(const file of boardFiles){const path=`${dfCloudUser.id}/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID?.()||Date.now()}_${file.name.replace(/[^0-9A-Za-z._-]/g,'_')}`,q=await dfSupabase.storage.from(BUCKET).upload(path,file,{contentType:file.type||'application/octet-stream'});if(q.error)throw q.error;saved.push({name:file.name,path,mime:file.type||'',size:file.size})}return saved}
  dfV1129BoardSave=async function(){if(dfV1129BoardMode!=='write')return;const title=document.getElementById('dfBoardTitle')?.value.trim()||'',content=document.getElementById('dfBoardContent')?.value.trim()||'';if(!title)return alert('제목을 입력해주세요.');if(!dfSupabase||!dfCloudUser)return alert('온라인 DB에 연결되어 있지 않습니다.');const b=document.getElementById('dfBoardSave');b.disabled=true;b.textContent=boardFiles.length?'첨부파일 저장 중...':'등록 중...';let attachments=[];try{attachments=await uploadFiles();const {error}=await dfSupabase.from(DF_HOME_POST_TABLE).insert({category:dfV1129BoardCat,title,content,attachments,created_by:dfCloudUser.id});if(error)throw error;dfV1129CloseBoardModal();await dfHomeLoad();alert('게시글을 등록했습니다.')}catch(e){if(attachments.length)await dfSupabase.storage.from(BUCKET).remove(attachments.map(x=>x.path));alert('게시글 등록 실패\n'+(e.message||e))}finally{b.disabled=false;b.textContent='등록'}};
  dfHomeLoad=async function(){const welcome=document.getElementById('dfHomeWelcome');if(welcome)welcome.textContent=`${dfCloudProfile?.name||'사용자'}님, 오늘의 공지와 측정 진행상황입니다.`;dfHomeRenderProgress();if(!dfSupabase||!dfCloudUser){['notice','method','board'].forEach(c=>dfHomeRenderPosts(c,[]));return}try{const {data,error}=await dfSupabase.from(DF_HOME_POST_TABLE).select('id,category,title,content,attachments,created_at,created_by').order('created_at',{ascending:false}).limit(60);if(error)throw error;['notice','method','board'].forEach(c=>dfHomeRenderPosts(c,data||[]))}catch(e){const msg=e.message?.includes('attachments')?'20_v12024_profile_board_attachments.sql 설치가 필요합니다.':'게시판을 불러오지 못했습니다: '+e.message;['dfHomeNotice','dfHomeMethod','dfHomeBoard'].forEach(id=>{const x=document.getElementById(id);if(x)x.innerHTML=`<div class="df-home-empty">${esc(msg)}</div>`})}};

  if(typeof dfEmployeesFetch==='function')dfEmployeesFetch=async function(){if(!dfSupabase)throw Error('온라인 DB에 연결되어 있지 않습니다.');if(!dfV68IsAdmin())throw Error('관리자만 직원관리를 사용할 수 있습니다.');let q=await dfSupabase.from('profiles').select('*').order('active',{ascending:true}).order('name',{ascending:true});if(q.error){q=await dfSupabase.from('profiles').select('id,name,email,role,team,active,board_permissions,access_permissions').order('active',{ascending:true}).order('name',{ascending:true})}if(q.error)throw q.error;return(q.data||[]).map(x=>({phone:'',job_title:'',...x}))};
  if(typeof dfEmployeesRender==='function'){const base=dfEmployeesRender;dfEmployeesRender=function(rows){base(rows);document.querySelectorAll('[data-employee-id]').forEach(card=>{const row=rows.find(x=>String(x.id)===card.dataset.employeeId);if(!row||card.querySelector('[data-emp-title]'))return;const field=document.createElement('div');field.className='df-employee-field';field.innerHTML=`<label>직급</label><select data-emp-title><option value="">미지정</option>${titles.map(t=>`<option value="${t}" ${row.job_title===t?'selected':''}>${t}</option>`).join('')}</select>`;card.querySelector('.df-access-details')?.before(field)})}};
  if(typeof dfEmployeesSaveCard==='function'){const base=dfEmployeesSaveCard;dfEmployeesSaveCard=async function(card,id,approve){const job=card.querySelector('[data-emp-title]')?.value||null;await base(card,id,approve);const {error}=await dfSupabase.from('profiles').update({job_title:job}).eq('id',id);if(error)return dfEmployeesMsg('직급 저장 실패: '+error.message,'bad');dfEmployeesMsg(approve?'승인과 직급을 저장했습니다.':'권한과 직급을 저장했습니다.','ok');await dfEmployeesLoad()}};

  async function mobileRefresh(){if(!dfSupabase||!dfCloudUser)return;try{const q=await dfSupabase.from('profiles').select('*').eq('id',dfCloudUser.id).maybeSingle();if(!q.error&&q.data){dfCloudProfile=q.data;refreshSession()}const view=(location.hash||'').slice(1);if(view==='home')await dfHomeLoad();if(view==='repository')await window.dfRepositorySync?.({quiet:true});if(view==='billing')document.getElementById('dfErpRefresh')?.click()}catch(e){window.DF_DIAG?.warn('MOBILE-SYNC','휴대폰 최신화 실패',e.message||e)}}
  document.addEventListener('DOMContentLoaded',()=>{document.getElementById('dfProfileOpen')?.addEventListener('click',openProfile);document.getElementById('dfBoardFiles')?.addEventListener('change',e=>{const files=[...e.target.files];if(files.length>5)return alert('첨부파일은 최대 5개까지 선택할 수 있습니다.');if(files.some(f=>f.size>20*1024*1024))return alert('파일당 20MB 이하만 첨부할 수 있습니다.');boardFiles=files;fileNames()});setTimeout(refreshSession,900);setTimeout(mobileRefresh,1400);window.addEventListener('pageshow',mobileRefresh);window.addEventListener('online',mobileRefresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)mobileRefresh()});window.DF_DIAG?.info('PORTAL-120241','프로필 상시표시·휴대폰 최신화·푸터 배치 준비 완료')},{once:true});
  document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-board-download]');if(b){const f=b.closest('#dfBoardAttachments')?._files?.[Number(b.dataset.boardDownload)];if(!f)return;try{const {data,error}=await dfSupabase.storage.from(BUCKET).createSignedUrl(f.path,300);if(error)throw error;window.open(data.signedUrl,'_blank','noopener')}catch(err){alert('첨부파일 열기 실패\n'+(err.message||err))}return}if(e.target.closest?.('#dfBoardDelete')){const files=Array.isArray(dfV1129BoardPost?.attachments)?dfV1129BoardPost.attachments:[];if(files.length)dfSupabase.storage.from(BUCKET).remove(files.map(x=>x.path)).then(({error})=>{if(error)window.DF_DIAG?.warn('BOARD-FILE-DELETE','첨부파일 정리 실패',error.message)})}},true);
})();

// v120.25 database-driven organization chart
(function(){
  'use strict';
  const TABLE='dreampoen_organization_nodes',esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let nodes=[],profiles=[];
  const admin=()=>typeof dfV68IsAdmin==='function'&&dfV68IsAdmin();
  const msg=(t,bad=false)=>{const e=document.getElementById('dfOrganizationMessage');if(e){e.textContent=t||'';e.classList.toggle('bad',bad)}};
  function levelOf(n,seen=new Set()){if(!n?.parent_id||seen.has(n.id))return 0;seen.add(n.id);const p=nodes.find(x=>x.id===n.parent_id);return p?levelOf(p,seen)+Math.max(0,Number(n.row_offset??1)):0}
  function profileOf(n){return profiles.find(p=>p.id===n.profile_id)}
  function render(){
    const box=document.getElementById('dfOrganizationChart');if(!box)return;
    if(!nodes.length){box.innerHTML=`<div class="df-organization-empty">${admin()?'등록된 조직이 없습니다. ‘최상위 조직 추가’로 시작하세요.':'등록된 조직도가 없습니다.'}</div>`;return}
    const levels=[...new Set(nodes.map(levelOf))].sort((a,b)=>a-b);
    box.innerHTML='<svg class="df-org-lines" aria-hidden="true"></svg><div class="df-org-rows">'+levels.map(l=>`<div class="df-org-row" data-org-level="${l}">${nodes.filter(n=>levelOf(n)===l).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)||a.name.localeCompare(b.name,'ko')).map(n=>{const p=profileOf(n),sub=n.node_type==='person'&&p?[p.job_title,p.name].filter(Boolean).join(' · '):n.description;return `<article class="df-org-node type-${esc(n.node_type)}" data-org-id="${n.id}" style="--org-color:${esc(n.color||'#4f9b43')}"><strong>${esc(n.name)}</strong>${sub?`<small>${esc(sub)}</small>`:''}${p&&n.node_type!=='person'?`<small class="person">${esc([p.job_title,p.name].filter(Boolean).join(' · '))}</small>`:''}${admin()?`<div class="df-org-node-actions"><button data-org-edit>편집</button><button data-org-sibling>같은 줄 추가</button><button data-org-child>하위 추가</button></div>`:''}</article>`}).join('')}</div>`).join('')+'</div>';
    requestAnimationFrame(drawLines);
  }
  function drawLines(){const box=document.getElementById('dfOrganizationChart'),svg=box?.querySelector('.df-org-lines');if(!box||!svg)return;const br=box.getBoundingClientRect();svg.setAttribute('width',box.scrollWidth);svg.setAttribute('height',box.scrollHeight);svg.setAttribute('viewBox',`0 0 ${box.scrollWidth} ${box.scrollHeight}`);svg.innerHTML=nodes.filter(n=>n.parent_id).map(n=>{const a=box.querySelector(`[data-org-id="${n.parent_id}"]`),b=box.querySelector(`[data-org-id="${n.id}"]`);if(!a||!b)return'';const ar=a.getBoundingClientRect(),cr=b.getBoundingClientRect(),x1=ar.left-br.left+box.scrollLeft+ar.width/2,y1=ar.bottom-br.top+box.scrollTop,x2=cr.left-br.left+box.scrollLeft+cr.width/2,y2=cr.top-br.top+box.scrollTop,ym=y1+(y2-y1)/2;return `<path d="M ${x1} ${y1} V ${ym} H ${x2} V ${y2}"/>`}).join('')}
  async function load(){if(!dfSupabase)return msg('온라인 DB 연결이 필요합니다.',true);msg('조직도를 불러오는 중입니다.');try{const [a,b]=await Promise.all([dfSupabase.from(TABLE).select('*').eq('active',true).order('sort_order'),dfSupabase.from('profiles').select('id,name,job_title,team,active').eq('active',true).order('name')]);if(a.error)throw a.error;nodes=a.data||[];profiles=b.error?[]:(b.data||[]);msg('');render()}catch(e){const install=/relation|schema cache|does not exist/i.test(e.message||'');msg((install?'21_v12025_dynamic_organization.sql을 먼저 실행해주세요. · ':'조직도 불러오기 실패 · ')+(e.message||e),true);document.getElementById('dfOrganizationChart').innerHTML='<div class="df-organization-empty">조직도 DB 준비가 필요합니다.</div>'}}
  function open(){const quality=document.getElementById('dfViewQuality'),hub=quality?.querySelector('.df-module-hub'),panel=document.getElementById('dfOrganizationPanel');if(!quality||!panel)return;hub.hidden=true;panel.hidden=false;quality.appendChild(panel);quality.hidden=false;quality.style.setProperty('display','block','important');load()}
  function close(){const quality=document.getElementById('dfViewQuality'),hub=quality?.querySelector('.df-module-hub'),panel=document.getElementById('dfOrganizationPanel');if(panel)panel.hidden=true;if(hub)hub.hidden=false}
  function descendants(id){const out=new Set();let changed=true;while(changed){changed=false;nodes.forEach(n=>{if((n.parent_id===id||out.has(n.parent_id))&&!out.has(n.id)){out.add(n.id);changed=true}})}return out}
  function editor(seed={}){if(!admin())return;const editing=!!seed.id,blocked=editing?descendants(seed.id):new Set();let m=document.getElementById('dfOrganizationModal');if(!m){m=document.createElement('div');m.id='dfOrganizationModal';m.className='company-modal-backdrop';document.body.appendChild(m)}const parentOptions=nodes.filter(n=>n.id!==seed.id&&!blocked.has(n.id)).map(n=>`<option value="${n.id}" ${seed.parent_id===n.id?'selected':''}>${'　'.repeat(levelOf(n))}${esc(n.name)}</option>`).join('');m.innerHTML=`<div class="company-modal df-org-editor"><div class="company-modal-head"><div><h2>${editing?'조직 항목 편집':'조직 항목 추가'}</h2><small>상위 조직과 표시 줄을 지정하면 조직도가 자동 배치됩니다.</small></div><button class="company-modal-close" data-org-close>×</button></div><div class="df-org-form"><label>명칭<input id="dfOrgName" value="${esc(seed.name||'')}" placeholder="예: 환경사업부"></label><label>구분<select id="dfOrgType">${[['position','직책'],['department','부서'],['team','팀'],['person','직원']].map(([v,l])=>`<option value="${v}" ${seed.node_type===v?'selected':''}>${l}</option>`).join('')}</select></label><label>상위 조직<select id="dfOrgParent"><option value="">없음 (최상위)</option>${parentOptions}</select></label><label>배치<select id="dfOrgRow"><option value="1" ${Number(seed.row_offset??1)===1?'selected':''}>상위 조직 아래 줄</option><option value="0" ${Number(seed.row_offset)===0?'selected':''}>상위 조직과 같은 줄</option>${[2,3,4].map(x=>`<option value="${x}" ${Number(seed.row_offset)===x?'selected':''}>${x}단계 아래 줄</option>`).join('')}</select></label><label>연결 직원<select id="dfOrgProfile"><option value="">연결 안 함</option>${profiles.map(p=>`<option value="${p.id}" ${seed.profile_id===p.id?'selected':''}>${esc(p.name||'이름 없음')} · ${esc(p.job_title||p.team||'')}</option>`).join('')}</select></label><label>표시 순서<input id="dfOrgSort" type="number" value="${Number(seed.sort_order||0)}"></label><label>색상<input id="dfOrgColor" type="color" value="${/^#[0-9a-f]{6}$/i.test(seed.color||'')?seed.color:'#4f9b43'}"></label><label class="wide">업무·설명<textarea id="dfOrgDescription" rows="4" placeholder="한 줄에 하나씩 입력할 수 있습니다.">${esc(seed.description||'')}</textarea></label><div class="df-org-form-actions">${editing?'<button class="company-btn danger" id="dfOrgDelete">삭제</button>':''}<span></span><button class="company-btn secondary" data-org-close>취소</button><button class="company-btn primary" id="dfOrgSave">저장</button></div></div></div>`;m.hidden=false;m.style.display='flex';m.querySelectorAll('[data-org-close]').forEach(b=>b.onclick=()=>{m.hidden=true;m.style.display='none'});m.onclick=e=>{if(e.target===m){m.hidden=true;m.style.display='none'}};document.getElementById('dfOrgSave').onclick=()=>save(seed);document.getElementById('dfOrgDelete')?.addEventListener('click',()=>remove(seed))}
  async function save(seed){const payload={name:document.getElementById('dfOrgName').value.trim(),node_type:document.getElementById('dfOrgType').value,parent_id:document.getElementById('dfOrgParent').value||null,row_offset:Number(document.getElementById('dfOrgRow').value),profile_id:document.getElementById('dfOrgProfile').value||null,sort_order:Number(document.getElementById('dfOrgSort').value||0),color:document.getElementById('dfOrgColor').value,description:document.getElementById('dfOrgDescription').value.trim()};if(!payload.name)return alert('명칭을 입력해주세요.');const b=document.getElementById('dfOrgSave');b.disabled=true;b.textContent='저장 중...';try{const q=seed.id?await dfSupabase.from(TABLE).update(payload).eq('id',seed.id):await dfSupabase.from(TABLE).insert(payload);if(q.error)throw q.error;document.getElementById('dfOrganizationModal').hidden=true;document.getElementById('dfOrganizationModal').style.display='none';await load()}catch(e){alert('조직도 저장 실패\n'+(e.message||e))}finally{b.disabled=false;b.textContent='저장'}}
  async function remove(seed){const childCount=nodes.filter(n=>n.parent_id===seed.id).length;if(!confirm(`“${seed.name}”을 삭제할까요?${childCount?'\n하위 조직 '+childCount+'개도 함께 삭제됩니다.':''}`))return;const {error}=await dfSupabase.from(TABLE).delete().eq('id',seed.id);if(error)return alert('삭제 실패\n'+error.message);document.getElementById('dfOrganizationModal').hidden=true;document.getElementById('dfOrganizationModal').style.display='none';load()}
  document.addEventListener('click',e=>{const org=e.target.closest?.('[data-doc-category="organization"]');if(org){e.preventDefault();e.stopImmediatePropagation();open();return}const card=e.target.closest?.('[data-org-id]');if(!card)return;const row=nodes.find(n=>n.id===card.dataset.orgId);if(e.target.closest('[data-org-edit]'))editor(row);else if(e.target.closest('[data-org-sibling]'))editor({parent_id:row.parent_id,row_offset:row.row_offset,sort_order:(row.sort_order||0)+1,color:row.color});else if(e.target.closest('[data-org-child]'))editor({parent_id:row.id,row_offset:1,sort_order:0,color:'#4f9b43'})},true);
  document.addEventListener('DOMContentLoaded',()=>{document.getElementById('dfOrganizationBack')?.addEventListener('click',close);document.getElementById('dfOrganizationAddRoot')?.addEventListener('click',()=>editor({parent_id:null,row_offset:0,node_type:'position',color:'#aeb4b8'}));document.getElementById('dfOrganizationPrint')?.addEventListener('click',()=>window.print());window.addEventListener('resize',()=>requestAnimationFrame(drawLines));window.DF_DIAG?.info('ORGANIZATION-12025','동적 조직도 준비 완료')},{once:true});
})();
