/* DREAMFOREN QMS SECTION CONTROL · v120.29.0 */
(function(){
  'use strict';
  const PDF='assets/quality_manual_rev02.pdf', $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
  const st={sections:[],revisions:[],mode:'original',selected:null};
  const db=()=>{try{return dfSupabase}catch(_){return null}},me=()=>{try{return dfCloudUser?.id||''}catch(_){return ''}},admin=()=>{try{return String(dfCloudProfile?.role||'')==='admin'}catch(_){return false}};
  const baseSection=code=>window.DF_QMS_EMBEDDED_MANUAL?.sections?.find(x=>x.code===code);
  const message=(x,type='ok')=>{const e=$('dfQmsMessage');if(e){e.textContent=x;e.className='df-qms-message '+type}};
  const nextRev=v=>String((Number(String(v||'0').replace(/\D/g,''))||0)+1).padStart(2,'0');
  async function load(){
    st.sections=[];st.revisions=[];
    try{const a=await db().from('quality_manual_sections').select('*').eq('active',true).order('section_code');if(a.error)throw a.error;st.sections=a.data||[];const ids=st.sections.map(x=>x.id);if(ids.length){const r=await db().from('quality_section_revisions').select('*').in('section_id',ids).order('created_at',{ascending:false});if(r.error)throw r.error;st.revisions=r.data||[]}message('원본 PDF와 장별 개정상태를 불러왔습니다.','ok')}
    catch(e){message('장별 개정관리 DB 설치가 필요합니다. 원본 PDF는 그대로 열람할 수 있습니다. · 23_v12029_quality_sections_leave.sql','bad');window.DF_DIAG?.error('QMS-SECTION','장별 개정관리 조회 실패',e.message||String(e))}
    render()
  }
  function summary(){const active=st.revisions.filter(x=>x.status==='active').length,draft=st.revisions.filter(x=>x.status==='draft'||x.status==='submitted').length;$('dfQmsSummary').innerHTML=`<div><span>기준 원본</span><strong>PDF 38페이지</strong></div><div><span>전체 장</span><strong>${st.sections.length||20}개</strong></div><div><span>장별 승인본</span><strong>${active}개</strong></div><div><span>개정 진행</span><strong>${draft}개</strong></div><div><span>원본 상태</span><strong>Rev.02 확인본</strong></div>`}
  function render(){summary();const rev=document.querySelector('.df-qms-revision'),work=document.querySelector('.df-qms-workspace'),toc=$('dfQmsToc'),paper=$('dfQmsPaper');$('dfQmsRegister').hidden=true;$('dfQmsRevise').hidden=true;$('dfQmsApprove').hidden=true;
    $('dfQmsOriginalMode').className='company-btn '+(st.mode==='original'?'primary':'secondary');$('dfQmsSectionMode').className='company-btn '+(st.mode==='sections'?'primary':'secondary');
    if(st.mode==='original'){rev.hidden=true;work.style.gridTemplateColumns='1fr';document.querySelector('.df-qms-toc').hidden=true;paper.className='df-qms-paper df-qms-pdf-paper';paper.innerHTML=`<div class="df-qms-pdf-tools"><b>품질 매뉴얼 원본 · Rev.02 · 38페이지</b><a class="company-btn secondary" href="${PDF}" target="_blank">새 창에서 열기</a></div><iframe class="df-qms-pdf-frame" src="${PDF}#page=1&view=FitH" title="품질 매뉴얼 원본 PDF"></iframe>`;return}
    rev.hidden=false;work.style.gridTemplateColumns='260px minmax(0,1fr)';document.querySelector('.df-qms-toc').hidden=false;paper.className='df-qms-paper df-qms-section-paper';
    toc.innerHTML=st.sections.map(s=>`<button type="button" data-qms-section="${esc(s.id)}"><span>${esc(s.section_no)}</span>${esc(s.title)}</button>`).join('')||'<p>SQL 설치 후 장별 목록이 표시됩니다.</p>';
    paper.innerHTML=st.sections.map(card).join('')||`<div class="df-doc-empty"><b>장별 관리 DB가 아직 준비되지 않았습니다.</b><br>원본 PDF 보기에서는 현재 문서를 그대로 확인할 수 있습니다.</div>`;select(st.selected||st.sections[0]?.id)
  }
  function card(s){const rs=st.revisions.filter(x=>x.section_id===s.id),current=rs.find(x=>x.status==='active'),draft=rs.find(x=>x.status==='draft'||x.status==='submitted');return `<article class="df-qms-section-card" data-section-card="${esc(s.id)}"><header><div><span>${esc(s.section_no)}</span><h2>${esc(s.title)}</h2></div><b>${esc(s.section_code)}</b></header><div class="df-qms-section-status"><span>현재 Rev.<strong>${esc(current?.revision||s.current_revision)}</strong></span><span>원본 PDF <strong>${s.pdf_start_page}${s.pdf_end_page>s.pdf_start_page?'~'+s.pdf_end_page:''}쪽</strong></span><span>개정상태 <strong>${draft?(draft.status==='submitted'?'결재중':'초안 작성중'):'최신본'}</strong></span></div><div class="df-qms-section-actions"><button class="company-btn secondary" data-source-page="${s.pdf_start_page}">원본 확인</button>${current?'<button class="company-btn secondary" data-revision-view="'+esc(current.id)+'">현재 개정내용</button>':''}${admin()?`<button class="company-btn primary" data-section-edit>${draft?'초안 계속 작성':'이 장 개정'}</button>`:''}</div>${draft?`<div class="df-qms-draft-note">Rev.${esc(draft.revision)} · ${esc(draft.change_reason||'변경사유 미입력')}</div>`:''}</article>`}
  function select(id){st.selected=id;document.querySelectorAll('[data-section-card]').forEach(x=>x.classList.toggle('selected',x.dataset.sectionCard===id));document.querySelectorAll('[data-qms-section]').forEach(x=>x.classList.toggle('active',x.dataset.qmsSection===id));const s=st.sections.find(x=>x.id===id);if(!s)return;const rs=st.revisions.filter(x=>x.section_id===id);$('dfQmsHistory').innerHTML=rs.length?rs.map(x=>`<tr><td><b>${esc(x.revision)}</b></td><td>${esc(String(x.approved_at||x.created_at).slice(0,10))}</td><td>${esc(s.section_no)} ${esc(s.title)}</td><td>${esc(x.change_reason)} · ${x.status==='active'?'승인본':x.status==='obsolete'?'구본':x.status==='submitted'?'결재중':x.status==='rejected'?'반려':'초안'}</td></tr>`).join(''):`<tr><td>${esc(s.current_revision)}</td><td>-</td><td>${esc(s.section_no)} ${esc(s.title)}</td><td>원본 PDF 기준</td></tr>`}
  function sourcePage(page){window.open(`${PDF}#page=${page}&view=FitH`,'_blank','noopener')}
  function edit(s){let r=st.revisions.find(x=>x.section_id===s.id&&x.status==='draft'),m=$('dfQmsSectionModal');if(!m){m=document.createElement('div');m.id='dfQmsSectionModal';m.className='company-modal-backdrop';document.body.appendChild(m)}const base=r?.content||(baseSection(s.section_code)?.paragraphs||[]).join('\n\n'),rev=r?.revision||nextRev(s.current_revision);m.hidden=false;m.style.display='flex';m.innerHTML=`<div class="company-modal df-qms-section-editor"><div class="company-modal-head"><div><h2>${esc(s.section_no)} ${esc(s.title)}</h2><small>${esc(s.section_code)} · Rev.${esc(rev)} 개정초안</small></div><button class="company-modal-close" data-close>×</button></div><div class="df-qms-original-reminder"><b>원본 확인사항</b> PDF ${s.pdf_start_page}${s.pdf_end_page>s.pdf_start_page?'~'+s.pdf_end_page:''}쪽을 기준으로 수정합니다. <button data-pdf>원본 열기</button></div><label>개정 본문<textarea id="dfQmsSectionContent">${esc(base)}</textarea></label><label>변경 사유<input id="dfQmsSectionReason" value="${esc(r?.change_reason||'')}" placeholder="변경 위치와 사유를 구체적으로 입력하세요."></label><div class="df-qms-editor-actions"><button class="company-btn secondary" data-close>취소</button><button class="company-btn secondary" data-save>초안 저장</button><button class="company-btn primary" data-submit>저장 후 결재상신</button></div></div>`;const close=()=>{m.hidden=true;m.style.display='none'};m.querySelectorAll('[data-close]').forEach(x=>x.onclick=close);m.querySelector('[data-pdf]').onclick=()=>sourcePage(s.pdf_start_page);m.querySelector('[data-save]').onclick=()=>save(s,r,rev,false,m);m.querySelector('[data-submit]').onclick=()=>save(s,r,rev,true,m)}
  async function save(s,r,rev,submit,m){const content=$('dfQmsSectionContent').value.trim(),reason=$('dfQmsSectionReason').value.trim();if(!content||!reason)return alert('개정 본문과 변경 사유를 입력해주세요.');try{if(r){const q=await db().from('quality_section_revisions').update({content,change_reason:reason,updated_at:new Date().toISOString()}).eq('id',r.id).select().single();if(q.error)throw q.error;r=q.data}else{const q=await db().from('quality_section_revisions').insert({section_id:s.id,revision:rev,status:'draft',content,change_reason:reason,created_by:me()}).select().single();if(q.error)throw q.error;r=q.data}m.hidden=true;m.style.display='none';await load();if(submit){if(typeof window.dfApprovalOpenPreset!=='function')throw Error('내부결재 모듈을 불러오지 못했습니다.');window.dfApprovalOpenPreset({doc_type:'quality_document',title:`${s.section_no} ${s.title} Rev.${rev} 개정 승인`,content:`문서번호: ${s.section_code}\n개정대상: ${s.section_no} ${s.title}\n개정번호: Rev.${rev}\n변경사유: ${reason}`,quality_section_revision_id:r.id,locked:true})}}catch(e){alert('장별 개정 저장 실패\n'+(e.message||e));window.DF_DIAG?.error('QMS-SECTION','장별 개정 저장 실패',e.message||String(e))}}
  window.dfQmsSectionOpen=()=>{window.v62ShowOnly?.('quality-manual');load()};
  document.addEventListener('click',e=>{const link=e.target.closest('#dfQmsToc a');if(link){e.preventDefault();e.stopImmediatePropagation();const id=link.dataset.qmsLink,el=document.getElementById('qms-'+id);el?.scrollIntoView({behavior:'smooth',block:'start'})}const back=e.target.closest('#dfDocBack');if(back){e.preventDefault();e.stopImmediatePropagation();window.v62ShowOnly?.('quality')}},{capture:true});
  document.addEventListener('DOMContentLoaded',()=>{$('dfQmsOriginalMode').onclick=()=>{st.mode='original';render()};$('dfQmsSectionMode').onclick=()=>{st.mode='sections';render()};$('dfQmsPrint').onclick=()=>sourcePage(1);$('dfQmsToc').addEventListener('click',e=>{const b=e.target.closest('[data-qms-section]');if(b){select(b.dataset.qmsSection);document.querySelector(`[data-section-card="${b.dataset.qmsSection}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}});$('dfQmsPaper').addEventListener('click',e=>{const c=e.target.closest('[data-section-card]'),s=st.sections.find(x=>x.id===c?.dataset.sectionCard);if(!s)return;if(e.target.closest('[data-source-page]'))sourcePage(s.pdf_start_page);else if(e.target.closest('[data-section-edit]'))edit(s);else select(s.id)})},{once:true});
})();
