/* Beta 3.11 · DFEN-QPF-13-01 (00) · Original document editing workspace. */
(function(){'use strict';
 const CODE='DFEN-QPF-13-01 (00)',BUCKET='quality-equipment-ledgers',FILES='quality_equipment_ledger_files',TABLE='quality_equipment_ledgers';
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clone=x=>JSON.parse(JSON.stringify(x)),num=(v,min=0,max=500)=>Math.max(min,Math.min(max,Number(v)||0)),hex=v=>/^#[a-f0-9]{6}$/i.test(v)?v:'#000000';
 const me=()=>typeof dfCloudUser==='undefined'?null:dfCloudUser,db=()=>typeof dfSupabase==='undefined'?null:dfSupabase;
 const can=a=>!!me()&&!!window.DFMenuPermissions?.can('quality-forms',a,false);
 const S={active:false,identity:null,busy:false,ready:false,token:0,records:[],equipment:[],files:[],attachments:[],current:null,dirty:false,query:'',scope:'all',year:new Date().getFullYear(),fit:true,sources:new Map(),images:new Map(),pending:null,message:'',bad:false};
 function context(id=S.identity){if(!id||me()?.id!==id||!can('view')||!db())throw Error('로그인과 작성용 품질문서 권한을 확인해주세요.');return db();}
 const result=async p=>{const r=await p;if(r.error)throw r.error;return r.data;},sha=async b=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),x=>x.toString(16).padStart(2,'0')).join('');
 function say(text,bad=false){S.message=text;S.bad=bad;if($('eqlMessage')){$('eqlMessage').textContent=text;$('eqlMessage').className=bad?'bad':'ok';}}
 function failure(e){say(/PGRST20[25]|42P01|schema cache/.test((e.code||'')+' '+e.message)?'49_beta311_equipment_ledger.sql을 먼저 실행해주세요.':e.message||String(e),true);}
 const run=fn=>(...a)=>Promise.resolve().then(()=>fn(...a)).catch(failure);
 const equipment=()=>S.equipment.find(e=>e.id===S.current?.equipment_id),field=(doc,key)=>doc?.table?.cells?.[doc.fields?.[key]]?.text||'';
 function discard(){if(S.busy){say('진행 중인 작업을 마친 뒤 이동해주세요.',true);return false;}return !(S.dirty||S.pending)||confirm('저장하지 않은 작성 내용 또는 업로드 대기가 있습니다. 버리고 이동할까요?');}
 async function pages(table){let all=[];for(let from=0;;from+=100){const rows=await result(context().from(table).select('*').order('id').range(from,from+99));all.push(...rows);if(rows.length<100)return all;}}
 async function reload(){const id=S.identity,t=++S.token;const [records,equip,files,attachments]=await Promise.all([pages(TABLE),pages('quality_equipment'),pages(FILES),pages('quality_equipment_attachments')]);context(id);if(t!==S.token||!S.active)return;Object.assign(S,{records:records.filter(r=>!r.archived_at),equipment:equip.filter(r=>!r.archived_at),files,attachments:attachments.filter(a=>a.kind==='photo'&&!a.archived_at),ready:true});}
 async function blank(eqid=''){const r=await fetch('assets/equipment_ledger_blank.json?v=beta311');if(!r.ok)throw Error('장비관리대장 기본 양식을 불러오지 못했습니다.');const data=await r.json();S.current={id:null,equipment_id:eqid,record_year:S.year,lock_version:null,data};if(eqid)pull(false);S.dirty=!!eqid;S.pending=null;render();}
 function header(){window.DF_QPF_FORMS.state.view='qpf-equipment-ledger';$('dfDocTitle').textContent=CODE+' 장비관리대장';$('dfDocDescription').textContent='원본 한글 양식 불러오기 · 장비별 웹 수정·저장 · 미리보기·인쇄';$('dfDocBack').textContent='← 작성용 품질문서';}
 function ensure(){if($('eqlPane'))return;const el=document.createElement('section');el.id='eqlPane';el.className='qic-pane';el.hidden=true;el.innerHTML=`<div class="qic-toolbar"><label>작성 연도<select id="eqlYear"></select></label><label class="qic-search-label">장비·관리번호 검색<input id="eqlSearch" type="search" placeholder="관리번호 · 장비명 · 모델명"></label><button class="qpf-button" id="eqlReload">새로고침</button><button class="qpf-button" id="eqlNew">+ 새 대장</button><button class="qpf-button primary" id="eqlSave">저장</button><button class="qpf-button danger" id="eqlDelete">대장 삭제</button><button class="qpf-button" id="eqlPreview">미리보기</button><button class="qpf-button" id="eqlPrint">인쇄</button><button class="qpf-button active" id="eqlFit">화면 맞춤</button></div><div class="qic-status"><span id="eqlMessage" role="status" aria-live="polite"></span><span id="eqlMeta"></span></div><div class="qic-layout"><aside class="qic-side-stack"><section class="qic-file-panel"><div class="qic-record-head"><strong>장비관리대장 원본</strong><span>HWP</span></div><div id="eqlDrop" class="qic-drop-zone" tabindex="0" role="button" aria-label="장비관리대장 HWP 업로드"><b>한글 파일을 여기에 끌어놓기</b><small>원본 양식의 글자·표·사진을 불러와 편집합니다.<br>DFEN-QPF-13-01 양식 · HWP 5 · 20MB 이내</small><button id="eqlChoose" class="qpf-button">파일 선택</button><input id="eqlInput" type="file" accept=".hwp" data-df-drop="off" hidden></div><p class="qic-file-message">원본 HWP는 그대로 보관하며, 수정본은 아래 작성자료로 저장합니다.</p><button id="eqlRetry" class="qpf-button" hidden>실패한 업로드 다시 시도</button><div id="eqlFiles" class="qic-file-list"></div></section><section class="qic-record-panel"><div class="qic-record-head"><strong>등록대장 연계</strong></div><div class="eql-link"><label>연결 장비<select id="eqlEquipment"></select></label><button class="qpf-button" id="eqlPull">등록대장 정보·사진 불러오기</button><small>용도·금액·부서·제원·검교정 이력은 유지합니다.</small></div></section><section class="qic-record-panel"><div class="qic-record-head"><strong>웹 작성자료</strong><select id="eqlScope" aria-label="조회 범위"><option value="all">전체 연도</option><option value="year">선택 연도</option></select></div><div id="eqlRecords" class="qic-record-list"></div></section></aside><main class="qic-form-panel"><div class="qic-form-scroll"><div id="eqlStage" class="eql-stage"><div id="eqlDocument"></div></div></div><p class="eql-edit-hint">문서의 글자를 눌러 수정한 뒤 저장하세요. 관리번호는 연결 장비를 따릅니다.</p></main></div>`;$('dfQualityFormWorkspace').append(el);
  $('eqlSearch').oninput=e=>{S.query=e.target.value;renderLists();};$('eqlScope').onchange=e=>{S.scope=e.target.value;renderLists();};
  $('eqlYear').onchange=run(async e=>{if(!discard()){e.target.value=S.year;return;}S.year=Number(e.target.value);await blank(S.current?.equipment_id||'');renderLists();});
  $('eqlEquipment').onchange=run(async e=>{if(!discard()){e.target.value=S.current?.equipment_id||'';return;}const id=e.target.value,old=S.records.find(r=>r.equipment_id===id&&r.record_year===S.year);if(old)select(old.id);else await blank(id);});
  $('eqlNew').onclick=run(async()=>{if(discard())await blank(S.current?.equipment_id||'');});$('eqlReload').onclick=run(async()=>{if(!discard())return;S.busy=true;render();try{const id=S.current?.id;S.pending=null;await reload();if(id&&S.records.some(r=>r.id===id)){S.current=clone(S.records.find(r=>r.id===id));S.dirty=false;}else await blank();say('최신 자료를 불러왔습니다.');}finally{S.busy=false;render();}});
  $('eqlSave').onclick=run(save);$('eqlDelete').onclick=run(remove);$('eqlPull').onclick=()=>pull(true);$('eqlPreview').onclick=run(()=>preview(false));$('eqlPrint').onclick=run(()=>preview(true));$('eqlFit').onclick=()=>{S.fit=!S.fit;fit();};$('eqlRetry').onclick=run(commitImport);
  $('eqlChoose').onclick=e=>{e.stopPropagation();if(!S.busy&&can('upload'))$('eqlInput').click();};$('eqlDrop').onclick=e=>{if(e.target!==$('eqlInput')&&e.target!==$('eqlChoose')&&!S.busy&&can('upload'))$('eqlInput').click();};$('eqlDrop').onkeydown=e=>{if(e.target===$('eqlDrop')&&['Enter',' '].includes(e.key)){e.preventDefault();$('eqlChoose').click();}};
  $('eqlInput').onchange=run(e=>{const f=e.target.files[0];e.target.value='';return importFile(f);});const drop=$('eqlDrop');drop.ondragover=e=>{e.preventDefault();e.stopPropagation();drop.classList.toggle('dragging',!S.busy&&can('upload'));};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();e.stopPropagation();drop.classList.remove('dragging');const files=[...e.dataTransfer.files];if(files.length!==1){say('장비관리대장 HWP 파일을 한 개씩 선택해주세요.',true);return;}run(importFile)(files[0]);};
  el.addEventListener('click',run(async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.eqlRecord)select(b.dataset.eqlRecord);if(b.dataset.eqlFile)await original(b.dataset.eqlFile,b.hasAttribute('data-download'));}));
  $('eqlDocument').oninput=e=>{const cell=e.target.closest('[data-eql-cell]');if(!cell||!S.current||S.busy||!can(S.current.id?'update':'create'))return;S.current.data.table.cells[Number(cell.dataset.eqlCell)].text=cell.innerText.replace(/\r/g,'').replace(/\n$/,'');S.dirty=true;meta();shrink(cell);};
  $('eqlDocument').onpaste=e=>{if(!e.target.closest('[contenteditable=true]'))return;e.preventDefault();const selection=getSelection();if(!selection.rangeCount)return;const range=selection.getRangeAt(0);range.deleteContents();const node=document.createTextNode(e.clipboardData.getData('text/plain'));range.insertNode(node);range.setStartAfter(node);range.collapse(true);selection.removeAllRanges();selection.addRange(range);e.target.dispatchEvent(new Event('input',{bubbles:true}));};
  new ResizeObserver(fit).observe(el.querySelector('.qic-form-scroll'));
 }
 function meta(){$('eqlMeta').textContent=S.current?.id?(S.dirty?'저장하지 않은 수정내용 · ':'')+'최근 저장 '+new Date(S.current.updated_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):(S.dirty?'저장 전 작성내용':'새 대장');}
 function renderLists(){if(!$('eqlPane'))return;const q=S.query.trim().toLowerCase();const match=r=>!q||JSON.stringify(r).toLowerCase().includes(q);$('eqlFiles').innerHTML=S.files.filter(f=>(!S.current?.equipment_id||f.equipment_id===S.current.equipment_id)&&match(f)).sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(f=>`<article class="qic-file-item"><div class="qic-file-info"><strong>${esc(f.name)}</strong><small>${esc(f.created_at.slice(0,10))} · ${(f.size/1024/1024).toFixed(1)}MB</small></div><div class="qic-file-actions"><button data-eql-file="${esc(f.id)}">원본 보기</button><button data-eql-file="${esc(f.id)}" data-download>원본 받기</button></div></article>`).join('')||'<div class="qic-file-empty">보관된 원본이 없습니다.</div>';
  $('eqlRecords').innerHTML=S.records.filter(r=>(S.scope==='all'||r.record_year===S.year)&&match(r.data)).sort((a,b)=>b.record_year-a.record_year||field(a.data,'equipment_code').localeCompare(field(b.data,'equipment_code'),'ko',{numeric:true})).map(r=>`<button class="qic-record-item ${r.id===S.current?.id?'selected':''}" data-eql-record="${esc(r.id)}"><strong>${esc(field(r.data,'equipment_code'))} · ${r.record_year}년</strong><span>${esc(field(r.data,'equipment_name').replace(/\n/g,' '))}</span><small>${esc(r.updated_at.slice(0,10))}</small></button>`).join('')||'<div class="qic-file-empty">저장된 장비관리대장이 없습니다.</div>';}
 function render(){if(!$('eqlPane')||!S.active)return;const write=!!S.current&&can(S.current.id?'update':'create')&&!S.busy;const currentYear=new Date().getFullYear();$('eqlYear').innerHTML=Array.from(new Set([S.year,...S.records.map(r=>r.record_year),...Array.from({length:16},(_,i)=>currentYear-10+i)])).sort((a,b)=>b-a).map(y=>`<option ${y===S.year?'selected':''}>${y}</option>`).join('');$('eqlYear').disabled=S.busy;
  $('eqlEquipment').innerHTML='<option value="">장비를 선택하세요</option>'+S.equipment.slice().sort((a,b)=>a.equipment_code.localeCompare(b.equipment_code,'ko',{numeric:true})).map(e=>`<option value="${esc(e.id)}" ${e.id===S.current?.equipment_id?'selected':''}>${esc(e.equipment_code+' · '+e.data.equipment_name)}</option>`).join('');$('eqlEquipment').disabled=S.busy||!!S.current?.id;
  for(const id of ['eqlReload','eqlPreview','eqlPrint','eqlFit'])$(id).disabled=S.busy||!S.ready;
  $('eqlSave').disabled=!write||!equipment();$('eqlDelete').disabled=S.busy||!S.current?.id||!can('delete');$('eqlNew').disabled=S.busy||!S.ready||!can('create');$('eqlPull').disabled=!write||!equipment();$('eqlChoose').disabled=S.busy||!S.ready||!can('upload');$('eqlDrop').classList.toggle('disabled',$('eqlChoose').disabled);$('eqlRetry').hidden=!S.pending;$('eqlRetry').disabled=S.busy;say(S.message,S.bad);meta();renderLists();paint(write);
 }
 function cellStyle(c,t){const edges=c.style?.edges||[],styles=['left','right','top','bottom'].map((side,i)=>{const e=edges[i];return e?`border-${side}:${num(e.width,0,1)}mm ${['solid','none','double','dotted','dashed'].includes(e.kind)?e.kind:'solid'} ${hex(e.color)}`:'';}).join(';');return `left:${num(t.xs[c.c])}mm;top:${num(t.ys[c.r])}mm;width:${num(t.xs[c.c+c.cs]-t.xs[c.c],0,210)}mm;height:${num(t.ys[c.r+c.rs]-t.ys[c.r],0,290)}mm;background:${hex(c.style?.background||'#ffffff')};${styles}`;}
 function sheet(doc,write){const t=doc.table;return `<article class="eql-paper"><div class="eql-table" style="left:${num(doc.page.left)}mm;top:${num(doc.page.top)}mm;width:${num(t.xs.at(-1))}mm;height:${num(t.ys.at(-1))}mm">${t.cells.map((c,i)=>`<div class="eql-cell" style="${cellStyle(c,t)}">${c.picture?`<div class="eql-picture" data-eql-picture="${i}">${c.picture.kind==='empty'?'<span>장비 사진</span>':'<span>사진을 불러오는 중입니다…</span>'}</div>`:`<div data-eql-cell="${i}" ${c.r!==1&&c.r!==3&&c.r!==14?`contenteditable="${write&&i!==doc.fields.equipment_code}" role="textbox" aria-label="${esc(Object.entries(doc.fields).find(([,v])=>v===i)?.[0]||'문서 '+(c.r+1)+'행 '+(c.c+1)+'열')}" spellcheck="false"`:''} class="eql-cell-content" data-font="${num(c.style?.font||9,5,28)}" style="font-size:${num(c.style?.font||9,5,28)}pt;font-weight:${c.style?.bold?700:400};color:${hex(c.style?.color)};text-align:${['left','right','center','justify'].includes(c.style?.align)?c.style.align:'center'}">${esc(c.text)}</div>`}</div>`).join('')}<img class="eql-logo" src="assets/dreamforen_ci.jpg" alt="드림포이엔"></div><footer class="eql-footer">${doc.footer.filter(Boolean).map(v=>`<span>${esc(v)}</span>`).join('')}</footer></article>`;}
 function paint(write){if(!S.current)return;$('eqlDocument').innerHTML=sheet(S.current.data,write);fit();$('eqlDocument').querySelectorAll('[data-eql-cell]').forEach(shrink);const token=++S.paintToken||1;S.paintToken=token;const current=S.current;S.pictureError=false;S.pictureTask=Promise.all(current.data.table.cells.map((c,i)=>c.picture&&c.picture.kind!=='empty'?hydrate(c.picture,i,token,current):null)).catch(e=>{if(token===S.paintToken){failure(e);S.pictureError=true;}});}
 function shrink(el){let pt=num(el.dataset.font||9,5,28);el.style.fontSize=pt+'pt';const parent=el.parentElement,css=getComputedStyle(parent),height=parent.clientHeight-parseFloat(css.paddingTop)-parseFloat(css.paddingBottom),overflow=()=>el.scrollHeight>height+1||el.scrollWidth>el.clientWidth+1;while(pt>6&&overflow()){pt-=.5;el.style.fontSize=pt+'pt';}el.classList.toggle('eql-overflow',overflow());}
 function fit(){const paper=$('eqlDocument')?.querySelector('.eql-paper'),stage=$('eqlStage');if(!paper||!stage)return;const available=Math.max(150,$('eqlPane').querySelector('.qic-form-scroll').clientWidth-20),scale=S.fit?Math.min(1,available/(210*96/25.4)):1;paper.style.transform=`scale(${scale})`;stage.style.width=(210*96/25.4*scale)+'px';stage.style.height=(297*96/25.4*scale)+'px';$('eqlFit').classList.toggle('active',S.fit);}
 async function verified(f,bucket){const id=S.identity,b=await result(context(id).storage.from(bucket).download(f.path));context(id);if(await sha(await b.arrayBuffer())!==f.sha256)throw Error('원본 파일 확인에 실패했습니다: '+f.name);return b;}
 async function source(fid){context();if(S.sources.has(fid))return S.sources.get(fid);const f=S.files.find(f=>f.id===fid);if(!f)throw Error('연결된 HWP 원본을 찾을 수 없습니다.');const id=S.identity,b=await verified(f,BUCKET),r=await DF_EQ_LEDGER_IMPORT.parse(new File([b],f.name));context(id);S.sources.set(fid,r);return r;}
 async function imageData(pic){context();const key=JSON.stringify(pic);if(S.images.has(key))return S.images.get(key);const id=S.identity;let b;if(pic.kind==='source'){b=(await source(pic.file_id)).pictures.get(pic.bin);}else{const f=S.attachments.find(f=>f.id===pic.attachment_id);if(!f)throw Error('등록대장의 사진이 삭제되었거나 조회할 수 없습니다. 사진을 다시 불러와주세요.');b=await verified(f,'quality-equipment-attachments');}if(!b)throw Error('문서 사진을 찾을 수 없습니다.');const image=await createImageBitmap(b),size={w:image.width,h:image.height};image.close();const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(b);});context(id);const value={...size,data};S.images.set(key,value);return value;}
 async function hydrate(pic,i,token,current){const im=await imageData(pic);if(token!==S.paintToken||current!==S.current||!S.active)return;const host=$('eqlDocument').querySelector('[data-eql-picture="'+i+'"]');if(!host)return;const [x,y,cw,ch]=pic.crop||[0,0,1,1],sw=num(cw,0.01,1)*im.w,sh=num(ch,0.01,1)*im.h,angle=num(pic.angle,0,359),rad=angle*Math.PI/180,w=Math.abs(Math.cos(rad))*sw+Math.abs(Math.sin(rad))*sh,h=Math.abs(Math.sin(rad))*sw+Math.abs(Math.cos(rad))*sh;host.innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${-w/2} ${-h/2} ${w} ${h}" preserveAspectRatio="xMidYMid meet" aria-label="장비 사진"><g transform="rotate(${angle})"><svg x="${-sw/2}" y="${-sh/2}" width="${sw}" height="${sh}" viewBox="${num(x,0,1)*im.w} ${num(y,0,1)*im.h} ${sw} ${sh}" overflow="hidden"><image href="${esc(im.data)}" width="${im.w}" height="${im.h}"/></svg></g></svg>`;}
 function select(id){if(!discard())return;const r=S.records.find(r=>r.id===id);if(!r)return;S.current=clone(r);S.year=r.record_year;S.dirty=false;S.pending=null;S.pictureError=false;S.message='저장한 장비관리대장을 열었습니다.';render();}
 function pull(ask){const e=equipment();if(!e||!S.current||S.busy)return;if(ask&&!confirm('등록대장의 기본정보와 사진을 현재 대장에 반영할까요?\n용도·금액·부서·제원·검교정 이력은 유지합니다.\n내용을 확인한 뒤 저장해주세요.'))return;const d=S.current.data;for(const k of ['equipment_code','equipment_name','model','serial_no','manufacturer','purchase_date','last_inspection','next_inspection']){const c=d.table.cells[d.fields[k]];if(c)c.text=e.data[k]||'';}const photos=S.attachments.filter(a=>a.equipment_id===e.id).sort((a,b)=>b.created_at.localeCompare(a.created_at)||a.id.localeCompare(b.id));let n=0;for(const c of d.table.cells)if(c.picture){if(photos[n])c.picture={kind:'equipment',attachment_id:photos[n].id,angle:0,crop:[0,0,1,1]};n++;}S.dirty=true;S.pictureError=false;if(ask){say('등록대장 정보를 불러왔습니다. 확인 후 저장해주세요.');render();}}
 async function importFile(file){if(!file||S.busy||!S.ready||!can('upload')||!discard())return;S.busy=true;render();try{const id=S.identity,p=await DF_EQ_LEDGER_IMPORT.parse(file);context(id);const eq=S.equipment.find(e=>e.equipment_code===p.code);if(!eq)throw Error(p.code+' 장비가 시험장비등록대장에 없습니다. 먼저 장비를 등록해주세요.');const existing=S.records.find(r=>r.equipment_id===eq.id&&r.record_year===S.year);if(!can(existing?'update':'create'))throw Error('이 장비관리대장을 작성할 권한이 없습니다.');if(existing&&!confirm(p.code+'의 '+S.year+'년 대장이 있습니다. 업로드한 문서로 편집을 시작할까요?\n저장을 누르기 전에는 기존 작성자료가 바뀌지 않습니다.'))return;S.pending={parsed:p,equipment:eq.id,existing:existing?clone(existing):null,identity:id,id:crypto.randomUUID(),hash:await sha(p.raw),uploaded:false};}finally{S.busy=false;render();}if(S.pending)await commitImport();}
 async function commitImport(){const p=S.pending;if(!p||S.busy)return;context(p.identity);S.busy=true;render();try{const path=`${p.equipment}/${p.identity}/${p.id}.hwp`;if(!p.uploaded){const r=await context(p.identity).storage.from(BUCKET).upload(path,p.parsed.file,{contentType:'application/x-hwp',upsert:false});if(r.error){if(String(r.error.statusCode||r.error.status)!=='409'&&!/duplicate|already exists/i.test(r.error.message||''))throw r.error;const b=await result(context(p.identity).storage.from(BUCKET).download(path));if(await sha(await b.arrayBuffer())!==p.hash)throw Error('업로드 원본이 일치하지 않습니다.');}p.uploaded=true;}const f=await result(context(p.identity).rpc('df_equipment_ledger_file_add',{p_equipment:p.equipment,p_file:{id:p.id,path,name:p.parsed.file.name,size:p.parsed.file.size,sha256:p.hash}}));context(p.identity);if(!S.files.some(v=>v.id===f.id))S.files.unshift(f);S.sources.set(f.id,p.parsed);const data=clone(p.parsed.doc);for(const c of data.table.cells)if(c.picture)c.picture.file_id=f.id;S.current={...(p.existing||{id:null,lock_version:null}),equipment_id:p.equipment,record_year:S.year,data};S.dirty=true;S.pending=null;S.pictureError=false;say('원본의 표·내용·사진을 불러왔습니다. 문서를 수정한 뒤 저장해주세요.');}finally{S.busy=false;render();}}
 async function save(){if(S.busy||!S.current||!equipment())return;const r=S.current,id=S.identity;if(!can(r.id?'update':'create'))throw Error('저장 권한이 없습니다.');S.busy=true;render();try{const saved=await result(context(id).rpc('df_equipment_ledger_save',{p_id:r.id,p_version:r.lock_version,p_equipment:r.equipment_id,p_year:r.record_year,p_data:r.data}));context(id);S.current=saved;S.records=S.records.filter(r=>r.id!==saved.id);S.records.push(saved);S.dirty=false;say('장비관리대장을 저장했습니다.');}finally{S.busy=false;render();}}
 async function remove(){const r=S.current;if(!r?.id||S.busy||!can('delete'))return;if(!confirm(field(r.data,'equipment_code')+' · '+r.record_year+'년 장비관리대장을 삭제할까요?\n시험장비등록대장과 사진·성적서는 그대로 유지됩니다.'))return;const id=S.identity;S.busy=true;render();try{await result(context(id).rpc('df_equipment_ledger_archive',{p_id:r.id,p_version:r.lock_version}));context(id);S.records=S.records.filter(x=>x.id!==r.id);await blank(r.equipment_id);S.dirty=false;say('장비관리대장 작성자료를 삭제했습니다.');}finally{S.busy=false;render();}}
 async function original(fid,download){const f=S.files.find(f=>f.id===fid);if(!f)return;const b=await verified(f,BUCKET);if(!download)return DF_QUALITY_FILE_PREVIEW.open({name:f.name,mime:'application/x-hwp',size:f.size,load:()=>Promise.resolve(b)});const a=document.createElement('a'),url=URL.createObjectURL(b);a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 async function preview(print){if(!S.current)return;context();const popup=window.open('','_blank');if(!popup)throw Error('팝업 차단을 해제해주세요.');popup.document.write('<p>문서와 사진을 준비하고 있습니다…</p>');try{await S.pictureTask;if(S.pictureError)throw Error('사진을 모두 불러온 뒤 다시 시도해주세요.');$('eqlDocument').querySelectorAll('[data-eql-cell]').forEach(shrink);if($('eqlDocument').querySelector('.eql-overflow'))throw Error('입력 내용이 칸을 넘었습니다. 붉은 테두리 칸의 문구를 줄인 뒤 인쇄해주세요.');const page=$('eqlDocument').querySelector('.eql-paper').cloneNode(true);page.style.transform='none';const logo=page.querySelector('.eql-logo');if(logo){const response=await fetch(new URL(logo.getAttribute('src'),document.baseURI));if(!response.ok)throw Error('인쇄할 회사 로고를 불러오지 못했습니다.');const b=await response.blob();logo.src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(b);});}page.querySelectorAll('[contenteditable]').forEach(e=>e.removeAttribute('contenteditable'));const base=new URL('.',document.baseURI).href,css=Array.from(document.styleSheets).filter(s=>s.href?.includes('qpf_equipment_ledger.css')).map(s=>Array.from(s.cssRules).map(r=>r.cssText).join('\n')).join('\n');popup.document.open();popup.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><base href="${esc(base)}"><title>${esc(field(S.current.data,'equipment_code'))} 장비관리대장</title><style>${css}</style></head><body class="eql-print"><nav><span>${S.dirty?'저장 전 작성내용':'저장된 장비관리대장'}</span><button onclick="window.print()">인쇄 / PDF 저장</button></nav>${page.outerHTML}</body></html>`);popup.document.close();await new Promise(resolve=>{if(popup.document.readyState==='complete')resolve();else popup.addEventListener('load',resolve,{once:true});});await popup.document.fonts.ready;if(print)popup.print();}catch(e){popup.close();throw e;}}
 async function open(){if(S.busy)return;if(!can('view'))throw Error('작성용 품질문서 조회 권한이 없습니다.');window.DF_QPF_FORMS.open();ensure();S.sources.clear();S.images.clear();Object.assign(S,{active:true,identity:me().id,ready:false,current:null,dirty:false,pending:null,query:'',message:'장비관리대장을 불러오는 중입니다…',pictureError:false});$('eqlPane').hidden=false;$('qpfFolderPane').hidden=true;$('qpfLedgerPane').hidden=true;header();await reload();await blank();say('한글 원본을 업로드하거나 연결 장비를 선택해 새 대장을 작성하세요.');}
 function close(){S.active=false;S.token++;S.paintToken++;if($('eqlPane'))$('eqlPane').hidden=true;}
 const navigation={capture(){return {identity:S.identity,current:S.current?clone(S.current):null,year:S.year,dirty:S.dirty,query:S.query};},canLeave(){return !S.busy;},restore:run(async v=>{if(v?.identity!==me()?.id)throw Error('장비관리대장을 다시 열어주세요.');ensure();S.active=true;S.identity=v.identity;await reload();Object.assign(S,v);$('eqlPane').hidden=false;header();render();})};
 document.addEventListener('df:menu-permissions-changed',()=>{if(!can('view')){close();S.current=null;S.records=[];S.files=[];S.sources.clear();S.images.clear();}else if(S.active)render();});addEventListener('beforeunload',e=>{if(S.active&&(S.dirty||S.busy||S.pending)){e.preventDefault();e.returnValue='';}});
 window.DF_EQ_LEDGER={open:run(open),close,confirmDiscard:discard,navigation,state:S,_test:{sheet,field,source,parse:()=>DF_EQ_LEDGER_IMPORT.parse}};
})();
