/* Beta 3.11 · Import the original HWP 5 equipment-ledger table, cells and pictures. */
(function(){'use strict';
 const unit=n=>n*25.4/7200,decoder=new TextDecoder('utf-16le');
 const dv=a=>new DataView(a.buffer,a.byteOffset,a.byteLength),color=(a,o)=>'#'+[a[o],a[o+1],a[o+2]].map(x=>(x||0).toString(16).padStart(2,'0')).join('');
 function records(a){const out=[];let p=0;while(p<a.length){if(p+4>a.length)throw Error('HWP 레코드가 손상되었습니다.');const h=dv(a).getUint32(p,true);p+=4;let n=h>>>20;if(n===4095){if(p+4>a.length)throw Error('HWP 레코드를 확인해주세요.');n=dv(a).getUint32(p,true);p+=4;}if(p+n>a.length||out.length>50000)throw Error('HWP 구성요소 범위를 확인해주세요.');out.push({tag:h&1023,level:(h>>>10)&1023,bytes:a.subarray(p,p+n)});p+=n;}return out;}
 async function rawInflate(bytes){const reader=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader();const chunks=[];let total=0;try{while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>50*1024*1024)throw Error('압축 해제된 HWP 구성요소가 너무 큽니다.');chunks.push(value);}}finally{await reader.cancel().catch(()=>{});}const a=new Uint8Array(total);let p=0;for(const c of chunks){a.set(c,p);p+=c.length;}return a;}
 async function inflate(bytes){try{return await rawInflate(bytes);}catch(e){if(!/Junk found after end/.test(e.message)||bytes.length<9)throw e;const expected=dv(bytes).getUint32(bytes.length-4,true);if(expected>50*1024*1024)throw Error('압축 해제 크기가 너무 큽니다.');const out=await rawInflate(bytes.subarray(0,-8));if(out.length!==expected)throw Error('HWP 압축 크기가 일치하지 않습니다.');return out;}}
 function text(a){let out='';for(let p=0;p+1<a.length;){const c=dv(a).getUint16(p,true);if(c<32){if(c===10)out+='\n';if(c===9||c===30||c===31)out+=' ';if(c===24)out+='-';p+=[1,2,3,4,5,6,7,8,9,11,12,14,15,16,17,18,19,20,21,22,23].includes(c)?16:2;}else{out+=String.fromCharCode(c===0xf09e?0xb7:c);p+=2;}}return out;}
 const normalized=s=>String(s).replace(/[\s·.\-\/]/g,'');
 const labels={equipment_name:'장비명',equipment_code:'관리번호',model:'모델명',serial_no:'SNo',purpose:'용도',manufacturer:'제조사',purchase_date:'구입일자',purchase_price:'구입금액',department:'관리부서',last_inspection:'검교정일자',next_inspection:'차기검교정일자',specification:'제원및사양'};
 function fieldMap(cells){const map={};for(const [k,label] of Object.entries(labels)){const cell=cells.find(c=>normalized(c.text)===label);if(cell){const value=cells.find(c=>c.r===cell.r&&c.c===cell.c+cell.cs);if(value)map[k]=cells.indexOf(value);}}return map;}
 function bounds(cells,n,key,span,size){const edges=cells.filter(c=>c[size]>0).sort((a,b)=>a[span]-b[span]),out=Array(n+1).fill(null);out[0]=0;for(let pass=0;pass<n+2;pass++){for(const c of edges){const a=c[key],b=a+c[span];if(b>n)throw Error('표의 병합 범위를 확인해주세요.');if(out[a]!==null&&out[b]===null)out[b]=out[a]+c[size];else if(out[b]!==null&&out[a]===null)out[a]=out[b]-c[size];}}if(out[n]===null)throw Error('이 문서의 표 크기를 해석하지 못했습니다.');for(let a=0;a<n;){let b=a+1;while(b<=n&&out[b]===null)b++;for(let j=a+1;j<b;j++)out[j]=out[a]+(out[b]-out[a])*(j-a)/(b-a);a=b;}if(out.some((x,i)=>i&&x<out[i-1]))throw Error('이 문서의 표 배치를 해석하지 못했습니다.');return out;}
 async function parse(file){
  if(!/\.hwp$/i.test(file.name)||!file.size||file.size>20*1024*1024)throw Error('20MB 이내 HWP 장비관리대장을 선택해주세요.');
  if(!window.XLSX?.CFB)throw Error('한글 읽기 구성요소를 불러오지 못했습니다. 새로고침해주세요.');
  const raw=new Uint8Array(await file.arrayBuffer()),cfb=XLSX.CFB.read(raw,{type:'array'}),entries=cfb.FileIndex.map((v,i)=>({name:(cfb.FullPaths[i]||v.name).replace(/^[^/]+\//,''),bytes:new Uint8Array(v.content||[])}));
  const get=n=>entries.find(e=>e.name===n)?.bytes,header=get('FileHeader');if(!header||new TextDecoder().decode(header.subarray(0,17))!=='HWP Document File')throw Error('HWP 5 형식의 장비관리대장이 아닙니다.');
  const flags=dv(header).getUint32(36,true);if(flags&6)throw Error('암호 또는 배포용 보호를 해제한 HWP 파일을 사용해주세요.');const decompress=async a=>flags&1?inflate(a):a;
  const docInfo=records(await decompress(get('DocInfo'))),borders=[],chars=[],paras=[];
  const weights=[.1,.12,.15,.2,.25,.3,.4,.5,.6,.7,1,1.5,2,3,4,5];
  for(const r of docInfo){const a=r.bytes,v=dv(a);if(r.tag===20){const edges=[];for(let i=0;i<4;i++){const o=2+i*6;edges.push({kind:a[o]===0?'none':a[o]>=8?'double':a[o]===3?'dotted':a[o]===2?'dashed':'solid',width:weights[a[o+1]]||.1,color:color(a,o+2)});}borders.push({edges,background:a.length>=40&&(v.getUint32(32,true)&1)?color(a,36):'#ffffff'});}else if(r.tag===21&&a.length>=56)chars.push({font:Math.max(5,Math.min(28,v.getInt32(42,true)/100)),bold:!!(v.getUint32(46,true)&2),color:color(a,52)});else if(r.tag===25)paras.push({align:['justify','left','right','center'][v.getUint32(0,true)>>>2&7]||'left'});}
  const sections=entries.filter(e=>/^BodyText\/Section\d+$/.test(e.name));if(sections.length!==1)throw Error('현재 장비관리대장은 원본과 같은 단일 구역의 A4 양식을 지원합니다.');
  const recs=records(await decompress(sections[0].bytes));let active=null,cell=null,shape=null,para=0;const tables=[];
  for(const r of recs){const a=r.bytes,v=dv(a);if(active&&r.level<active.level){active=null;cell=null;}if(r.tag===77){active={level:r.level,rows:v.getUint16(4,true),cols:v.getUint16(6,true),cells:[]};tables.push(active);cell=null;}else if(active&&r.tag===72&&r.level===active.level&&a.length>=34){cell={r:v.getUint16(10,true),c:v.getUint16(8,true),cs:v.getUint16(12,true),rs:v.getUint16(14,true),w:unit(v.getUint32(16,true)),h:unit(v.getUint32(20,true)),text:'',paragraphs:[],style:{...(borders[v.getUint16(32,true)-1]||{})},picture:null};active.cells.push(cell);}else if(cell&&r.tag===66&&r.level===active.level){para=v.getUint16(8,true);cell.style.align=paras[para]?.align||'center';}else if(cell&&r.tag===67&&r.level===active.level+1){cell.paragraphs.push(text(a));}else if(cell&&r.tag===68&&r.level===active.level+1&&a.length>=8){Object.assign(cell.style,chars[v.getUint32(4,true)]||{});}else if(cell&&r.tag===69&&r.level===active.level+1&&a.length>=36&&cell.h===0){cell.h=unit(v.getInt32(4,true)+v.getInt32(8,true)+282);}else if(r.tag===76&&a.length>=46){const base=a[0]===a[4]&&a[1]===a[5]?8:4;shape={angle:v.getUint16(base+32,true)%360};}else if(cell&&r.tag===85&&a.length>=73){const w=v.getInt32(20,true),h=v.getInt32(32,true),crop=[v.getInt32(44,true),v.getInt32(48,true),v.getInt32(52,true),v.getInt32(56,true)];cell.picture={kind:'source',bin:v.getUint16(71,true),angle:shape?.angle||0,crop:w>0&&h>0?[crop[0]/w,crop[1]/h,(crop[2]-crop[0])/w,(crop[3]-crop[1])/h]:[0,0,1,1]};}}
  for(const t of tables)for(const c of t.cells){c.text=c.paragraphs.join('\n').trim();delete c.paragraphs;}
  const main=tables.find(t=>t.cells.some(c=>normalized(c.text)==='장비관리대장'));
  if(!main||main.cells.length>250||main.rows>80||main.cols>30)throw Error('DFEN-QPF-13-01 장비관리대장 양식을 확인해주세요.');
  const fields=fieldMap(main.cells);if(Object.keys(fields).length!==Object.keys(labels).length)throw Error('원본의 장비명·관리번호·검교정일·제원 등 필수 칸을 찾지 못했습니다.');
  main.cells[fields.purchase_price].text=main.cells[fields.purchase_price].text.replace(/^\\(?=\s*\d)/,'₩');
  const xs=bounds(main.cells,main.cols,'c','cs','w'),ys=bounds(main.cells,main.rows,'r','rs','h');
  const used=new Set(main.cells.filter(c=>c.picture).map(c=>c.picture.bin)),pictures=new Map();let total=0;
  for(const bin of used){const item=entries.find(e=>new RegExp('^BinData/BIN'+bin.toString(16).padStart(4,'0')+'\\.','i').test(e.name));if(!item)throw Error('문서 안의 사진 원본이 없습니다.');const a=await decompress(item.bytes);total+=a.length;if(total>70*1024*1024)throw Error('문서 사진 크기가 너무 큽니다.');pictures.set(bin,new Blob([a],{type:a[0]===66&&a[1]===77?'image/bmp':a[0]===137?'image/png':'image/jpeg'}));}
  const footer=tables.find(t=>t!==main&&t.cells.some(c=>c.text.includes('DFEN-QPF-13-01')))?.cells.map(c=>c.text).filter(Boolean)||['DFEN-QPF-13-01','Rev. 00','- 주식회사 드림포이엔 -','A4(210×297mm)'];
  const doc={schema:1,page:{width:210,height:297,left:13,top:15.4},table:{rows:main.rows,cols:main.cols,xs,ys,cells:main.cells},fields,footer};if(xs.at(-1)>190||ys.at(-1)>264)throw Error('A4 한 페이지 범위를 벗어나는 양식입니다.');
  return {doc,pictures,raw,file,preview:get('PrvImage'),code:main.cells[fields.equipment_code].text.trim().toUpperCase()};
 }
 window.DF_EQ_LEDGER_IMPORT={parse,fieldMap,_test:{records,text,bounds}};
})();
