/* Beta 3.10.1 · Per-equipment photographs and calibration/test certificates. */
(function(){'use strict';
 const BUCKET='quality-equipment-attachments',TABLE='quality_equipment_attachments';
 const types={pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',hwp:'application/x-hwp',hwpx:'application/zip',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'};
 const S={host:null,equipment:null,identity:null,rows:[],ready:false,busy:false,token:0,photo:'',year:'all',date:'',message:'',urls:new Map(),blobs:new Map(),pending:null};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const me=()=>typeof dfCloudUser==='undefined'?null:dfCloudUser,db=()=>typeof dfSupabase==='undefined'?null:dfSupabase,profile=()=>typeof dfCloudProfile==='undefined'?null:dfCloudProfile;
 const can=a=>!!me()&&(window.DFMenuPermissions?.can('quality-forms',a,a==='view'||profile()?.role==='admin'||profile()?.access_permissions?.quality_edit===true)??false);
 function context(identity=S.identity){if(!identity||me()?.id!==identity||!can('view')||!db())throw Error('로그인과 작성용 품질문서 권한을 확인해주세요.');return db();}
 const result=async p=>{const r=await p;if(r.error)throw r.error;return r.data;};
 const sha=async b=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),x=>x.toString(16).padStart(2,'0')).join('');
 function message(v,bad=false){S.message=v;if(S.host){const el=S.host.querySelector('[data-eqa-status]');if(el){el.textContent=v;el.classList.toggle('bad',bad);}}}
 function failure(e){message(/PGRST202|42P01|schema cache/.test((e.code||'')+' '+e.message)?'47_beta310_equipment_cycles_assets.sql을 먼저 실행해주세요.':e.message||String(e),true);}
 const run=fn=>(...a)=>Promise.resolve().then(()=>fn(...a)).catch(failure);
 function clearURLs(){for(const u of S.urls.values())URL.revokeObjectURL(u);S.urls.clear();S.blobs.clear();}
 function reset(){S.token++;clearURLs();Object.assign(S,{host:null,equipment:null,identity:null,rows:[],ready:false,photo:'',pending:null,message:'',year:'all'});}
 function unmount(){S.host=null;}
 const year=f=>(f.inspection_date||f.created_at||'').slice(0,4);
 function uploadAllowed(){return S.ready&&!S.busy&&!window.DF_QPF_EQUIPMENT?.state.busy&&can('upload');}
 function photoCard(photo,index){
  if(!photo)return `<article class="eq-photo-card eq-photo-empty"><div class="eq-photo-stage"><b>사진 ${index+1}</b><p>사진을 여기에 끌어놓으세요</p></div></article>`;
  return `<article class="eq-photo-card"><div class="eq-photo-stage"><img data-eqa-photo="${esc(photo.id)}" alt="${esc(S.equipment.data.equipment_name+' · '+photo.name)}" ${S.urls.has(photo.id)?`src="${esc(S.urls.get(photo.id))}"`:''}><span data-eqa-photo-status="${esc(photo.id)}">${S.urls.has(photo.id)?'':'사진을 불러오는 중입니다…'}</span></div><div class="eq-photo-caption"><strong>${esc(photo.name)}</strong><div class="eq-photo-actions"><button data-eqa-open="${esc(photo.id)}">크게 보기</button><button data-eqa-download="${esc(photo.id)}">원본 받기</button>${can('delete')?`<button data-eqa-remove="${esc(photo.id)}" ${S.busy?'disabled':''}>사진 삭제</button>`:''}</div></div></article>`;
 }
 function render(){
  const h=S.host;if(!h?.isConnected)return;const photos=S.rows.filter(f=>f.kind==='photo'),certs=S.rows.filter(f=>f.kind==='certificate'),years=[...new Set(certs.map(year))].sort().reverse(),disabled=!uploadAllowed();
  const slots=photos.slice();while(slots.length<2)slots.push(null);
  h.innerHTML=`<div class="eq-asset-heading"><h3>장비 사진 <small>${photos.length}장</small></h3><button data-eqa-pick="photo" ${disabled?'disabled':''}>사진 추가</button></div>
   <section class="eq-asset-drop eq-photo-drop" data-eqa-drop="photo" aria-label="장비 사진 끌어놓기" aria-disabled="${disabled}"><p class="eq-drop-hint">사진을 끌어놓거나 ‘사진 추가’를 누르세요. <span>JPG · PNG · WebP / 2장씩 나란히 표시</span></p><div class="eq-photo-grid">${slots.map(photoCard).join('')}</div></section>
   <div class="eq-asset-heading"><h3>검교정성적서 <small>${certs.length}건</small></h3><button data-eqa-pick="certificate" ${disabled?'disabled':''}>성적서 업로드</button></div><div class="eq-asset-toolbar"><label>검사일 (선택)<input data-eqa-date type="date" value="${esc(S.date)}" ${S.busy?'disabled':''}></label><label>조회 연도<select data-eqa-year><option value="all">전체 연도</option>${years.map(y=>`<option ${S.year===y?'selected':''}>${y}</option>`).join('')}</select></label><button data-eqa-refresh ${S.busy?'disabled':''}>첨부 새로고침</button></div>
   <section class="eq-asset-drop eq-certificate-drop" data-eqa-drop="certificate" aria-label="검교정성적서 끌어놓기" aria-disabled="${disabled}"><b>검교정성적서를 여기에 끌어놓으세요</b><p class="eq-hint">또는 위의 ‘성적서 업로드’로 선택하세요.<br>PDF · 이미지 · HWP/HWPX · XLSX · DOCX / 파일당 20MB, 한 번에 10개<br>검사일을 함께 기록해 연도별로 보관할 수 있습니다.</p></section>
   <div class="eq-cert-list">${certs.filter(f=>S.year==='all'||year(f)===S.year).map(f=>`<article><div><strong>${esc(f.name)}</strong><small>${f.inspection_date?'검사일 '+esc(f.inspection_date.slice(0,10)):'검사일 미입력'} · 업로드 ${esc(f.created_at.slice(0,10))} · ${(f.size/1024).toFixed(0)} KB</small></div><div class="eq-cert-actions"><button data-eqa-open="${esc(f.id)}">미리보기</button><button data-eqa-download="${esc(f.id)}">원본 받기</button>${can('delete')?`<button data-eqa-remove="${esc(f.id)}" ${S.busy?'disabled':''}>삭제</button>`:''}</div></article>`).join('')||'<p class="eq-empty">보관된 검교정성적서가 없습니다.</p>'}</div><p data-eqa-status role="status" aria-live="polite">${esc(S.message)}</p>${S.pending?`<button data-eqa-retry ${S.busy?'disabled':''}>실패한 업로드 다시 시도</button>`:''}<input data-eqa-input="photo" data-df-drop="off" type="file" accept=".jpg,.jpeg,.png,.webp" multiple hidden><input data-eqa-input="certificate" data-df-drop="off" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.hwp,.hwpx,.xlsx,.docx" multiple hidden>`;
  h.onclick=run(async e=>{const b=e.target.closest('button');if(!b)return;e.stopPropagation();if(b.dataset.eqaPick){if(!uploadAllowed())return;h.querySelector('[data-eqa-input="'+b.dataset.eqaPick+'"]').click();}else if(b.dataset.eqaOpen)await openFile(b.dataset.eqaOpen);else if(b.dataset.eqaDownload)await openFile(b.dataset.eqaDownload,true);else if(b.dataset.eqaRemove)await remove(b.dataset.eqaRemove);else if(b.hasAttribute('data-eqa-refresh'))await load();else if(b.hasAttribute('data-eqa-retry'))await uploadPending();});
  h.onchange=run(async e=>{e.stopPropagation();if(e.target.dataset.eqaInput){const files=[...e.target.files];e.target.value='';await upload(files,e.target.dataset.eqaInput);}else if(e.target.hasAttribute('data-eqa-year')){S.year=e.target.value;render();}else if(e.target.hasAttribute('data-eqa-date'))S.date=e.target.value;});
  const zone=e=>{const z=e.target.closest?.('[data-eqa-drop]');return z&&h.contains(z)?z:null;},hasFiles=e=>[...e.dataTransfer?.types||[]].includes('Files');
  h.ondragenter=h.ondragover=e=>{const z=zone(e);if(!z||!hasFiles(e))return;e.preventDefault();e.stopPropagation();const allowed=uploadAllowed();z.classList.toggle('dragging',allowed);e.dataTransfer.dropEffect=allowed?'copy':'none';};
  h.ondragleave=e=>{const z=zone(e);if(z&&!z.contains(e.relatedTarget))z.classList.remove('dragging');};
  h.ondragend=()=>h.querySelectorAll('.dragging').forEach(z=>z.classList.remove('dragging'));
  h.ondrop=e=>{const z=zone(e);if(!z||!hasFiles(e))return;e.preventDefault();e.stopPropagation();z.classList.remove('dragging');if(!uploadAllowed()){message(S.busy?'업로드가 끝난 뒤 다시 시도해주세요.':'파일 등록 권한 또는 불러오기 상태를 확인해주세요.',true);return;}const files=[...e.dataTransfer.files],kind=z.dataset.eqaDrop;run(upload)(files,kind);};
  photos.filter(photo=>!S.urls.has(photo.id)).forEach(photo=>run(hydrate)(photo,S.token,S.equipment.id,S.identity));
 }
 async function load(){const identity=S.identity,id=S.equipment?.id,token=++S.token;if(!id)return;S.ready=false;render();try{let rows=[];for(let from=0;;from+=500){const r=await result(context(identity).from(TABLE).select('*').eq('equipment_id',id).is('archived_at',null).order('created_at',{ascending:false}).order('id').range(from,from+499));context(identity);rows.push(...r);if(r.length<500)break;}if(token!==S.token||id!==S.equipment?.id)return;S.rows=rows;S.ready=true;render();}catch(e){if(token===S.token)failure(e);}}
 function mount(host,equipment){const identity=me()?.id;if(identity!==S.identity||equipment.id!==S.equipment?.id){if(S.busy)return;reset();Object.assign(S,{host,equipment,identity,date:/^\d{4}-\d{2}-\d{2}$/.test(equipment.data.last_inspection)?equipment.data.last_inspection:'',year:'all'});run(load)();}else{S.host=host;S.equipment=equipment;render();}}
 async function blob(f,identity=S.identity){context(identity);if(S.blobs.has(f.id))return S.blobs.get(f.id);const original=await result(context(identity).storage.from(BUCKET).download(f.path));context(identity);const bytes=await original.arrayBuffer();if(await sha(bytes)!==f.sha256)throw Error('첨부 원본 확인에 실패했습니다: '+f.name);context(identity);const b=new Blob([bytes],{type:f.mime});S.blobs.set(f.id,b);return b;}
 async function hydrate(f,token,equipment,identity){const b=await blob(f,identity);if(S.token!==token||S.equipment?.id!==equipment||S.identity!==identity||!S.host?.isConnected)return;const image=S.host.querySelector('[data-eqa-photo="'+f.id+'"]');if(!image)return;let url=S.urls.get(f.id);if(!url){url=URL.createObjectURL(b);S.urls.set(f.id,url);}image.src=url;const text=S.host.querySelector('[data-eqa-photo-status="'+f.id+'"]');if(text)text.textContent='';}
 async function openFile(id,download=false){const f=S.rows.find(f=>f.id===id);if(!f)return;const identity=S.identity,b=await blob(f,identity);context(identity);if(!download&&window.DF_QUALITY_FILE_PREVIEW)return DF_QUALITY_FILE_PREVIEW.open({name:f.name,mime:f.mime,size:f.size,load:()=>Promise.resolve(b)});const url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 async function validateFile(file,kind){
  const ext=file.name.split('.').pop().toLowerCase(),mime=types[ext];if(!mime||!file.size||file.size>20*1024*1024||file.name.length>240||kind==='photo'&&!/^image\//.test(mime))throw Error('파일 형식 또는 크기를 확인해주세요: '+file.name);
  const bytes=await file.arrayBuffer(),a=new Uint8Array(bytes),starts=seq=>seq.every((v,i)=>a[i]===v);
  if(ext==='pdf'&&!new TextDecoder().decode(a.slice(0,8)).startsWith('%PDF-'))throw Error('PDF 원본이 아닙니다: '+file.name);
  if(ext==='hwp'&&!starts([208,207,17,224,161,177,26,225]))throw Error('HWP 원본이 아닙니다: '+file.name);
  if(['hwpx','xlsx','docx'].includes(ext)&&!starts([80,75,3,4]))throw Error('문서 원본 형식을 확인해주세요: '+file.name);
  if(/^image\//.test(mime)){const img=await createImageBitmap(new Blob([bytes],{type:mime}));img.close();}
  return {id:crypto.randomUUID(),file,ext,mime,sha256:await sha(bytes),uploaded:false};
 }
 async function upload(files,kind){if(!files.length||S.busy||!S.ready||!can('upload'))return;context();if(files.length>10||files.reduce((n,f)=>n+f.size,0)>100*1024*1024)throw Error('한 번에 10개, 합계 100MB 이내로 선택해주세요.');if(S.pending&&!confirm('실패한 업로드 대기를 취소하고 새 파일을 선택할까요?'))return;const identity=S.identity,equipment=S.equipment.id;S.busy=true;render();try{const items=[];for(const f of files)items.push(await validateFile(f,kind));context(identity);S.pending={items,kind,identity,equipment,date:S.date||null,done:0,skipped:0};}finally{S.busy=false;render();}await uploadPending();}
 async function uploadPending(){const p=S.pending;if(!p||S.busy||!can('upload'))return;context(p.identity);if(p.equipment!==S.equipment?.id)throw Error('장비를 다시 선택해주세요.');S.busy=true;render();try{
  for(const f of p.items){if(f.done)continue;context(p.identity);if(S.rows.some(x=>x.kind===p.kind&&x.sha256===f.sha256)){f.done=true;p.skipped++;continue;}
   const path=`${p.equipment}/${p.identity}/${f.id}.${f.ext}`;
   if(!f.uploaded){const r=await context(p.identity).storage.from(BUCKET).upload(path,f.file,{contentType:f.mime,upsert:false});if(r.error){if(String(r.error.statusCode||r.error.status)!=='409'&&!/already exists|duplicate/i.test(r.error.message||''))throw r.error;const b=await result(context(p.identity).storage.from(BUCKET).download(path));if(await sha(await b.arrayBuffer())!==f.sha256)throw Error('동일 경로의 원본이 다릅니다.');}context(p.identity);f.uploaded=true;}
   const r=await result(context(p.identity).rpc('df_equipment_attachment_add',{p_equipment:p.equipment,p_file:{id:f.id,name:f.file.name,kind:p.kind,path,mime:f.mime,size:f.file.size,sha256:f.sha256,inspection_date:p.kind==='certificate'?p.date:null}}));context(p.identity);f.done=true;p.done++;if(!S.rows.some(x=>x.id===r.id))S.rows.unshift(r);message(`${p.done}개 보관 완료`);
  }
  S.pending=null;S.message=`${p.done}개 보관 완료${p.skipped?' · 같은 원본 '+p.skipped+'개 유지':''}`;await load();
 }catch(e){S.message=`${p.done}개 보관 완료 · ${e.message||e} (다시 시도할 수 있습니다.)`;throw e;}finally{S.busy=false;render();}}
 async function remove(id){if(S.busy||!can('delete'))return;const f=S.rows.find(f=>f.id===id);if(!f||!confirm('이 장비의 첨부목록에서 삭제할까요?\n'+f.name))return;const identity=S.identity;context(identity);S.busy=true;render();try{await result(context(identity).rpc('df_equipment_attachment_archive',{p_id:id}));context(identity);const u=S.urls.get(id);if(u)URL.revokeObjectURL(u);S.urls.delete(id);S.blobs.delete(id);S.message='첨부목록에서 삭제했습니다.';await load();}finally{S.busy=false;render();}}
 document.addEventListener('df:menu-permissions-changed',()=>{if(!can('view'))reset();else render();});
 window.DF_EQ_ASSETS={mount,unmount,reset,busy:()=>S.busy,hasPending:()=>!!S.pending,_test:{state:S,validateFile}};
})();
