/* DFEN-QPF-02-02 · Approval-backed document establishment, revision and abolition. */
(function(){'use strict';
 const CODE='DFEN-QPF-02-02',BUCKET='quality-change-files';
 const OPS={establish:'제정',revise:'개정',abolish:'폐지'},ROLES={application:'신청서 원본',before:'변경 전',after:'변경 후',attachment:'기타 첨부'};
 const STATUS={draft:'임시저장',submitted:'결재요청',in_review:'검토 중',approved:'최종승인',rejected:'반려',cancelled:'취소'};
 const STEPS=['담당자','책임기술자','품질책임자'];
 const REQUEST_FIELDS='id,operation,doc_code,title,category,request_date,author_name,page_text,from_revision,to_revision,reason,before_text,after_text,applied_at,created_by,lock_version,created_at,updated_at';
 const S={active:false,busy:false,ready:false,identity:null,rows:[],docs:[],files:[],people:[],catalog:[],form:null,row:null,steps:[],pending:[],urls:new Map(),blobs:new Map(),year:new Date().getFullYear(),scope:'all',query:'',baseline:'',load:0,fit:true};
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const db=()=>typeof dfSupabase!=='undefined'?dfSupabase:null,me=()=>typeof dfCloudUser!=='undefined'?dfCloudUser:null,profile=()=>typeof dfCloudProfile!=='undefined'?dfCloudProfile:null;
 const can=a=>!!me()&&(window.DFMenuPermissions?.can('quality-forms',a,a==='view'||profile()?.role==='admin'||profile()?.access_permissions?.quality_edit===true)??false);
 function context(id=S.identity){if(!db()||!id||me()?.id!==id||!can('view'))throw Error('로그인과 작성용 품질문서 권한을 확인하고 다시 열어주세요.');return db();}
 const result=async p=>{const r=await p;if(r.error)throw r.error;return r.data;};
 const pad=n=>n===null||n===undefined||n===''?'미확인':String(n).padStart(2,'0');
 const date=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'});
 const category=code=>code.startsWith('DFEN-QM-')?'quality_manual':code.startsWith('DFEN-QP-')?'quality_procedure':code.startsWith('DFEN-QI-')?'quality_instruction':'quality_form';
 const cleanCode=v=>String(v||'').trim().toUpperCase().replace(/\s*\(\d+\)\s*$/,'');
 const fieldKeys=['operation','doc_code','title','category','request_date','author_name','page_text','from_revision','to_revision','reason','before_text','after_text'];
 const fields=r=>Object.fromEntries(fieldKeys.map(k=>[k,r[k]??'']));
 const blank=()=>({operation:'revise',doc_code:'',title:'',category:'quality_form',request_date:date(),author_name:profile()?.name||'',page_text:'',from_revision:'',to_revision:'',reason:'',before_text:'',after_text:''});
 const digest=async b=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),x=>x.toString(16).padStart(2,'0')).join('');
 const doc=()=>S.docs.find(x=>x.id===S.row?.id),editable=()=>S.ready&&can(S.row?'update':'create')&&(!S.row||doc()?.status==='draft'&&S.row.created_by===S.identity);
 const serialized=()=>JSON.stringify([S.form,S.steps.map(x=>({step_name:x.step_name,approver_id:x.approver_id||''}))]);
 const dirty=()=>!!S.pending.length||!!S.form&&serialized()!==S.baseline;
 function discard(){return !S.busy&&(!dirty()||confirm('저장하지 않은 신청 내용과 파일 선택을 취소하고 이동할까요?'));}
 function say(v,bad=false){if($('qcrStatus')){$('qcrStatus').textContent=v;$('qcrStatus').className=bad?'bad':'ok';}}
 const run=fn=>(...args)=>Promise.resolve().then(()=>fn(...args)).catch(e=>{say(/PGRST202|42P01|schema cache|df_qcr_/.test((e.code||'')+' '+e.message)?'제·개·폐 신청서 DB 설치가 필요합니다. 44_beta36_quality_change_requests.sql을 먼저 실행하세요.':e.message||String(e),true);});
 function newForm(){S.row=null;S.form=blank();S.steps=STEPS.map((step_name,i)=>({step_name,approver_id:i===0?S.identity:''}));S.pending=[];S.baseline=serialized();}
 async function paged(table,configure=q=>q){let rows=[];for(let from=0;;from+=500){const list=await result(configure(context().from(table).select(table==='quality_change_requests'?REQUEST_FIELDS:'*')).range(from,from+499));context();rows.push(...list);if(list.length<500)return rows;}}
 async function reload(){
  const identity=S.identity,token=++S.load,api=context(identity);
  const [rows,people,catalog]=await Promise.all([paged('quality_change_requests',q=>q.order('created_at',{ascending:false}).order('id')),result(api.rpc('df_approval_people')),result(api.rpc('df_qcr_catalog'))]);
  const docs=[],files=[],steps=[];
  for(let i=0;i<rows.length;i+=150){const ids=rows.slice(i,i+150).map(x=>x.id);const batch=await Promise.all([paged('approval_documents',q=>q.in('id',ids).order('id')),paged('quality_change_files',q=>q.in('request_id',ids).order('created_at').order('id')),paged('approval_steps',q=>q.in('document_id',ids).order('step_order').order('id'))]);docs.push(...batch[0]);files.push(...batch[1]);steps.push(...batch[2]);}
  context(identity);if(token!==S.load||!S.active)return;
  S.rows=rows.filter(r=>docs.some(d=>d.id===r.id&&!d.deleted_at));S.docs=docs;S.files=files;S.allSteps=steps;S.people=people;
  const map=new Map();for(const x of catalog||[])map.set(x.doc_code,{...map.get(x.doc_code),...x});if(!map.has('DFEN-QPF-14-01'))map.set('DFEN-QPF-14-01',{doc_code:'DFEN-QPF-14-01',title:'대기시료채취기록지',category:'quality_form',revision:null,status:'unregistered'});
  S.catalog=[...map.values()].sort((a,b)=>a.doc_code.localeCompare(b.doc_code));S.ready=true;
 }
 function resetUrls(){for(const url of S.urls.values())URL.revokeObjectURL(url);S.urls.clear();S.blobs.clear();}
 function currentFiles(){return S.files.filter(f=>f.request_id===S.row?.id).concat(S.pending);}
 function fileHtml(f,print=false){const url=S.urls.get(f.id),ext=f.name.split('.').pop().toLowerCase(),image=/^(png|jpg|jpeg|webp|gif|hwpx)$/.test(ext);return `<figure class="qcr-evidence" data-evidence="${esc(f.id)}">${url&&image?`<img src="${esc(url)}" alt="${esc(ROLES[f.role]+' · '+f.name)}">`:url&&ext==='pdf'&&!print?`<iframe title="${esc(f.name)}" src="${esc(url)}#toolbar=0"></iframe>`:''}<figcaption>${esc(f.name)}${f.file?' · 저장 전':''}</figcaption>${print?'':`<button type="button" data-qcr-preview="${esc(f.id)}">열기 / 받기</button>${editable()&&!S.busy?`<button type="button" data-qcr-remove="${esc(f.id)}">제외</button>`:''}`}</figure>`;}
 const person=id=>S.people.find(x=>x.id===id)?.name||'결재자';
 function sheet(print=false,record=S.form,options={}){
  const f=record||blank(),write=!print&&editable()&&!S.busy;
  const input=(k,type='text')=>print?`<span>${esc(f[k])}</span>`:`<input data-qcr-field="${k}" type="${type}" value="${esc(f[k])}" ${write?'':'disabled'} ${['from_revision','to_revision'].includes(k)?'min="0" max="9999"':'maxlength="160"'} ${k==='to_revision'?'readonly':''}>`;
  const area=k=>print?`<div class="qcr-text">${esc(f[k])}</div>`:`<textarea data-qcr-field="${k}" maxlength="8000" ${write?'':'disabled'}>${esc(f[k])}</textarea>`;
  const selected=options.files||currentFiles(),line=(options.steps||S.steps).map((s,i)=>`<td>${print||!write?`<b>${esc(s.approver_id?(s.approver?.name||person(s.approver_id)):'미지정')}</b>`:`<select data-qcr-step="${i}" aria-label="${esc(s.step_name)}"><option value="">선택</option>${S.people.map(p=>`<option value="${esc(p.id)}" ${p.id===s.approver_id?'selected':''}>${esc(p.name||p.email)}</option>`).join('')}</select>`}<small>${s.status==='approved'?'승인':s.status==='rejected'?'반려':s.status==='pending'?'결재대기':''}${s.acted_at?' · '+esc(s.acted_at.slice(0,10)):''}</small>${s.opinion?`<small>${esc(s.opinion)}</small>`:''}</td>`).join('');
  return `<article class="qcr-sheet"><header><img src="assets/dreamforen_ci.jpg" alt="드림포이엔"><h2>품질문서 [제·개·폐] 신청서</h2></header><div class="qcr-sheet-top"><div><label>신청일자 ${input('request_date','date')}</label><p>다음과 같이 품질문서를<br><b>${esc(OPS[f.operation])}</b> 하고자 합니다.</p></div><table class="qcr-line"><tr><th rowspan="2">결<br>재</th>${STEPS.map(x=>'<th>'+x+'</th>').join('')}</tr><tr>${line}</tr></table></div><table class="qcr-body"><colgroup><col style="width:17%"><col style="width:33%"><col style="width:8.5%"><col style="width:8.5%"><col style="width:33%"></colgroup><tbody><tr><th>품질문서명</th><td>${input('title')}</td><th colspan="2">페이지</th><td>${input('page_text')}</td></tr><tr><th>문서번호</th><td>${input('doc_code')}</td><th colspan="2">작성자</th><td>${input('author_name')}</td></tr><tr><th>현재 REV</th><td>${input('from_revision','number')}</td><th colspan="2">${f.operation==='abolish'?'폐지 REV':'적용 REV'}</th><td>${input('to_revision','number')}</td></tr><tr><th>사유</th><td colspan="4">${area('reason')}</td></tr><tr><th rowspan="2">내용 요약</th><th colspan="2">변경 전</th><th colspan="2">변경 후</th></tr><tr><td colspan="2" class="qcr-compare">${area('before_text')}<div data-qcr-evidence="before">${selected.filter(x=>x.role==='before').map(x=>fileHtml(x,print)).join('')}</div>${write?'<button type="button" data-qcr-add="before">+ 변경 전 파일</button>':''}</td><td colspan="2" class="qcr-compare">${area('after_text')}<div data-qcr-evidence="after">${selected.filter(x=>x.role==='after').map(x=>fileHtml(x,print)).join('')}</div>${write?'<button type="button" data-qcr-add="after">+ 변경 후 파일</button>':''}</td></tr><tr><td colspan="5"><b>첨부</b><div class="qcr-other-files">${selected.filter(x=>['application','attachment'].includes(x.role)).map(x=>fileHtml(x,print)).join('')||'<span>첨부파일 없음</span>'}</div></td></tr></tbody></table><footer><span>${CODE}</span><span>Rev.${esc(window.DF_DOCUMENT_REVISIONS?.rev(CODE,'01')||'01')}</span><span>A4(210×297mm)</span></footer></article>`;
 }
 function filteredRows(){return S.rows.filter(r=>(S.scope==='all'||Number(r.request_date.slice(0,4))===S.year)&&(!S.query||[r.title,r.doc_code,r.author_name,OPS[r.operation],r.request_date].join(' ').toLowerCase().includes(S.query.toLowerCase())));}
 function lists(){
  const rows=filteredRows();$('qcrCount').textContent=rows.length+'건';$('qcrRecords').innerHTML=rows.map(r=>`<button type="button" class="qic-record-item ${r.id===S.row?.id?'selected':''}" data-qcr-record="${esc(r.id)}"><strong>${esc(OPS[r.operation]+' · '+r.title)}</strong><span>${esc(r.doc_code)} · ${r.operation==='establish'?'신규':'Rev.'+pad(r.from_revision)} → ${r.operation==='abolish'?'폐지':'Rev.'+pad(r.to_revision)}</span><small>${esc(r.request_date)} · ${esc(STATUS[S.docs.find(d=>d.id===r.id)?.status]||'')} · ${esc(r.author_name)}</small></button>`).join('')||'<div class="qic-file-empty">신청서가 없습니다.</div>';
  const ids=new Set(rows.map(r=>r.id)),files=S.files.filter(f=>ids.has(f.request_id));$('qcrArchiveCount').textContent=files.length+'건';
  $('qcrArchiveFiles').innerHTML=files.map(f=>`<article class="qic-file-item"><div class="qic-file-info" title="${esc(f.name)}"><strong>${esc(f.name)}</strong><small>${esc(ROLES[f.role])} · ${(f.size/1024).toFixed(1)} KB</small></div><div class="qic-file-actions"><button type="button" data-qcr-preview="${esc(f.id)}">미리보기</button><button type="button" data-qcr-record="${esc(f.request_id)}">신청서</button></div></article>`).join('')||'<div class="qic-file-empty">업로드 파일이 없습니다.</div>';
 }
 function render(){
  if(!$('qcrPane'))return;lists();const write=editable()&&!S.busy;
  $('qcrOperation').value=S.form?.operation||'revise';$('qcrOperation').disabled=!write;
  $('qcrTarget').innerHTML='<option value="">문서 선택 / 문서번호 직접 입력</option>'+S.catalog.map(x=>`<option value="${esc(x.doc_code)}" ${x.doc_code===S.form?.doc_code?'selected':''}>${esc(x.doc_code+' · '+x.title+' · '+(x.status==='obsolete'?'폐지':'Rev.'+pad(x.revision)))}</option>`).join('');$('qcrTarget').disabled=!write;
  $('qcrSave').disabled=!write;$('qcrSubmit').disabled=!write;$('qcrNew').disabled=S.busy||!S.ready||!can('create');$('qcrCopy').disabled=S.busy||!S.row||!can('create');$('qcrReview').disabled=S.busy||!S.row;$('qcrRefresh').disabled=S.busy;$('qcrChoose').disabled=!write||!can('upload');
  $('qcrPrint').disabled=S.busy||!S.ready;$('qcrUploadRole').disabled=!write;$('qcrFileInput').disabled=!write||!can('upload');
  $('qcrState').textContent=(S.row?STATUS[doc()?.status]||'조회':'새 신청서')+(S.row?.applied_at?' · REV 반영 완료':dirty()?' · 저장 전 변경사항':'');
  $('qcrPaper').innerHTML=sheet();fit();hydrate();
 }
 function fit(){requestAnimationFrame(()=>{const paper=$('qcrPaper')?.querySelector('.qcr-sheet'),stage=$('qcrPaper'),scroller=$('qcrScroller');if(!paper||!scroller.clientWidth)return;const scale=S.fit?Math.min(1,(scroller.clientWidth-24)/794):1;paper.style.transform='scale('+Math.max(.1,scale)+')';stage.style.width=794*scale+'px';stage.style.height=paper.offsetHeight*scale+'px';});}
 async function blob(f,identity=me()?.id){if(!identity||me()?.id!==identity||!db())throw Error('로그인이 변경되었습니다.');if(S.blobs.has(f.id))return S.blobs.get(f.id);const data=f.file||await result(db().storage.from(BUCKET).download(f.path));if(me()?.id!==identity)throw Error('로그인이 변경되었습니다.');if(f.sha256&&await digest(await data.arrayBuffer())!==f.sha256)throw Error('첨부 원본 확인 실패: '+f.name);S.blobs.set(f.id,data);return data;}
 async function previewUrl(f){
  if(S.urls.has(f.id))return S.urls.get(f.id);const ext=f.name.split('.').pop().toLowerCase();if(!/^(png|jpg|jpeg|webp|gif|pdf|hwpx)$/.test(ext))return '';
  let b=await blob(f);if(ext==='pdf')b=new Blob([await b.arrayBuffer()],{type:'application/pdf'});if(ext==='hwpx'){if(!window.JSZip)return '';const zip=await JSZip.loadAsync(b),entry=zip.file('Preview/PrvImage.png');if(!entry||entry._data?.uncompressedSize>20*1024*1024)return '';b=new Blob([await entry.async('uint8array')],{type:'image/png'});}const url=URL.createObjectURL(b);S.urls.set(f.id,url);return url;
 }
 async function hydrate(){const token=S.load,id=S.row?.id;for(const f of currentFiles()){try{const url=await previewUrl(f);if(!S.active||token!==S.load||id!==S.row?.id)return;if(url){const el=$('qcrPaper')?.querySelector('[data-evidence="'+f.id+'"]');if(el)el.outerHTML=fileHtml(f);}}catch(e){say(e.message,true);}}fit();}
 async function preview(id){const f=S.files.concat(S.pending).find(x=>x.id===id);if(!f)return;const b=await blob(f);const ext=f.name.split('.').pop().toLowerCase();if(/^(png|jpg|jpeg|webp|gif)$/.test(ext)){const modal=document.createElement('div');modal.className='qcr-image-modal';const url=await previewUrl(f);modal.innerHTML=`<button type="button">닫기</button><img src="${esc(url)}" alt="${esc(f.name)}">`;modal.querySelector('button').onclick=()=>modal.remove();document.body.append(modal);return;}
  if(window.DF_QUALITY_FILE_PREVIEW)return window.DF_QUALITY_FILE_PREVIEW.open({name:f.name,mime:f.mime,size:f.size,load:()=>Promise.resolve(b)});
  download(b,f.name);
 }
 function download(b,name){const url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function recalculate(){const f=S.form;f.category=category(f.doc_code);f.from_revision=f.operation==='establish'?'':f.from_revision;f.to_revision=f.operation==='establish'?0:f.from_revision===''?'':Number(f.from_revision)+(f.operation==='revise'?1:0);}
 function chooseTarget(code){S.form.doc_code=cleanCode(code);const t=S.catalog.find(x=>x.doc_code===S.form.doc_code);if(t){if(t.conflict)throw Error('동일 문서번호에 서로 다른 REV가 등록되어 있습니다. 기준문서를 먼저 확인하세요.');S.form.title=t.title;S.form.from_revision=t.revision??'';}recalculate();render();if(S.form.from_revision===''&&S.form.operation!=='establish')say('등록된 현재 REV가 없습니다. 사용 중인 원본을 확인한 후 현재 REV를 입력하세요.');else if(t?.working_revision)say('작업실 Rev.'+pad(t.working_revision)+' 개정안은 상신 시 고정되고 이 신청서의 최종결재로 반영됩니다.');}
 async function prepare(files,role){if(!editable()||S.busy||!can('upload'))return;context();if(currentFiles().length+files.length>30)throw Error('신청서당 최대 30개 파일을 선택하세요.');if(currentFiles().concat(files).reduce((n,f)=>n+f.size,0)>100*1024*1024)throw Error('신청서당 첨부 합계는 100MB 이내로 선택하세요.');for(const file of files){if(!file.size||file.size>20*1024*1024)throw Error('파일당 20MB 이내로 등록하세요.');if(!/\.(png|jpe?g|webp|gif|pdf|hwp|hwpx|docx|xlsx)$/i.test(file.name)||/[\\/]/.test(file.name)||file.name.length>240)throw Error('이미지, PDF, HWP/HWPX, DOCX, XLSX 파일을 선택하세요.');}
  for(const file of files)S.pending.push({id:crypto.randomUUID(),name:file.name,size:file.size,mime:file.type||'application/octet-stream',role,file});render();say('선택한 파일을 미리보기로 확인하고 저장하세요.');
 }
 async function removeFile(id){if(!editable()||S.busy)return;const pending=S.pending.find(f=>f.id===id);if(pending)S.pending=S.pending.filter(f=>f.id!==id);else{if(!confirm('이 첨부를 신청서에서 제외할까요?'))return;await result(context().rpc('df_qcr_remove_file',{p_id:id}));S.files=S.files.filter(f=>f.id!==id);}const url=S.urls.get(id);if(url)URL.revokeObjectURL(url);S.urls.delete(id);S.blobs.delete(id);render();}
 function validForm(){const f=S.form;f.doc_code=cleanCode(f.doc_code);f.title=f.title.trim();recalculate();if(!/^DFEN-Q(M|P|I|PF|IF)-\d{2}(-\d{2})?$/.test(f.doc_code)||!f.title)throw Error('대상 품질문서명과 문서번호를 입력하세요.');if(!/^\d{4}-\d{2}-\d{2}$/.test(f.request_date))throw Error('신청일을 확인하세요.');if(f.to_revision!==''&&(!Number.isInteger(Number(f.to_revision))||Number(f.to_revision)<0||Number(f.to_revision)>9999))throw Error('REV는 0~9999 정수로 입력하세요.');}
 async function save(submit=false){
  if(S.busy||!editable())return;validForm();const identity=S.identity,api=context(identity),id=S.row?.id||S.draftId||crypto.randomUUID();S.draftId=id;
  if(submit){if(!S.form.reason.trim()||!S.form.author_name.trim())throw Error('신청 사유와 작성자를 입력하세요.');if(S.steps.some(s=>!s.approver_id)||new Set(S.steps.map(s=>s.approver_id)).size!==3)throw Error('담당자·책임기술자·품질책임자를 각각 지정하세요.');if(!confirm('신청서와 비교 첨부를 결재 상신할까요? 최종승인 후 REV가 반영됩니다.'))return;}
  S.busy=true;render();say('신청서 저장 중…');
  try{
   const payload={...S.form},steps=S.steps.map(s=>({step_name:s.step_name,approver_id:s.approver_id||''}));
   let row;
   try{row=await result(api.rpc('df_qcr_save',{p_id:id,p_expected:S.row?.lock_version??null,p_form:payload,p_steps:steps}));}
   catch(e){const check=await api.from('quality_change_requests').select('*').eq('id',id).maybeSingle();const actual=check.data;if(!actual||fieldKeys.some(k=>String(actual[k]??'')!==String(payload[k]??'')))throw e;const line=await result(api.from('approval_steps').select('*').eq('document_id',id).order('step_order'));if(JSON.stringify(line.map(x=>({step_name:x.step_name,approver_id:x.approver_id})))!==JSON.stringify(steps.filter(x=>x.approver_id)))throw e;row=actual;}
   context(identity);S.row=Array.isArray(row)?row[0]:row;S.draftId=null;if(!S.docs.some(d=>d.id===id))S.docs.push({id,status:'draft',requester_id:identity});
   for(const f of S.pending.slice()){
    f.sha256=f.sha256||await digest(await f.file.arrayBuffer());const ext=f.name.split('.').pop().toLowerCase(),path=id+'/'+f.id+'.'+ext;f.path=path;
    if(!f.uploaded){const up=await api.storage.from(BUCKET).upload(path,f.file,{contentType:f.mime,upsert:false});if(up.error){const original=await api.storage.from(BUCKET).download(path);if(original.error||await digest(await original.data.arrayBuffer())!==f.sha256)throw up.error;}f.uploaded=true;}
    context(identity);const stored=await result(api.rpc('df_qcr_file',{p_id:f.id,p_request:id,p_role:f.role,p_name:f.name,p_mime:f.mime,p_size:f.size,p_sha:f.sha256,p_ext:ext}));S.files.push(Array.isArray(stored)?stored[0]:stored);S.pending=S.pending.filter(x=>x.id!==f.id);
   }
   if(submit)await result(api.rpc('df_qcr_submit',{p_id:id,p_expected:S.row.lock_version}));
   context(identity);S.baseline=serialized();await reload();selectSaved(id);say(submit?'결재 상신 완료 · 최종승인 전까지 현재 REV가 유지됩니다.':'신청서와 첨부를 저장했습니다.');
  }finally{S.busy=false;render();}
 }
 function selectSaved(id){const row=S.rows.find(r=>r.id===id);if(!row)return;S.row=row;S.form=fields(row);S.steps=STEPS.map((step_name,i)=>({...S.allSteps.find(s=>s.document_id===id&&s.step_order===i+1),step_name}));S.pending=[];S.baseline=serialized();}
 async function select(id){if(!discard())return;S.load++;selectSaved(id);render();say(S.row?.applied_at?'최종승인되어 문서 REV에 반영된 신청서입니다.':'신청 내용을 확인하세요.');}
 async function print(){context();await hydrate();const w=window.open('about:blank','_blank');if(!w)throw Error('미리보기 팝업을 허용해주세요.');const css=Array.from(document.styleSheets).map(s=>{try{return Array.from(s.cssRules).map(r=>r.cssText).join('\n');}catch{return '';}}).filter(s=>s.includes('.qcr-sheet')).join('\n'),base=new URL('.',document.baseURI).href;w.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><base href="${esc(base)}"><title>품질문서 제·개·폐 신청서</title><style>${css}</style></head><body class="qcr-print"><nav><button onclick="print()">인쇄 / PDF</button></nav>${sheet(true)}</body></html>`);w.document.close();}
 function ensure(){if($('qcrPane'))return;const pane=document.createElement('section');pane.id='qcrPane';pane.className='qic-pane';pane.hidden=true;pane.innerHTML=`<div class="qic-toolbar"><label>조회 연도<select id="qcrYear">${Array.from({length:15},(_,i)=>new Date().getFullYear()+2-i).map(y=>`<option value="${y}" ${y===S.year?'selected':''}>${y}년</option>`).join('')}</select></label><label>조회 범위<select id="qcrScope"><option value="all">전체 연도</option><option value="year">선택 연도</option></select></label><label class="qic-search-label">신청서 찾기<input id="qcrSearch" type="search" placeholder="문서명 · 문서번호 · 작성자"></label><button class="qpf-button" id="qcrRefresh">새로고침</button><button class="qpf-button" id="qcrNew">+ 새 신청서</button><button class="qpf-button" id="qcrCopy">복사하여 새 신청</button><button class="qpf-button primary" id="qcrSave">저장</button><button class="qpf-button primary" id="qcrSubmit">결재 상신</button><button class="qpf-button" id="qcrReview">내부결재</button><button class="qpf-button" id="qcrPrint">미리보기 / 인쇄</button><button class="qpf-button active" id="qcrFit">화면 맞춤</button></div><div class="qic-status"><span id="qcrStatus" role="status" aria-live="polite"></span><span id="qcrState"></span></div><div class="qcr-target-bar"><label>신청 구분<select id="qcrOperation">${Object.entries(OPS).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>대상 품질문서<select id="qcrTarget"></select></label><small>문서번호로 연결합니다. 변경 전·후 첨부는 비교자료이며, 최종승인 시 관리 REV·상태가 반영됩니다.</small></div><div class="qic-layout"><aside class="qic-side-stack"><section class="qic-file-panel"><div class="qic-record-head"><strong>업로드 파일 전체조회</strong><span id="qcrArchiveCount"></span></div><label class="qcr-upload-label">업로드 구분<select id="qcrUploadRole">${Object.entries(ROLES).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><div id="qcrDrop" class="qic-drop-zone" role="button" tabindex="0" aria-label="선택한 구분으로 파일 업로드"><b>파일을 여기에 끌어놓기</b><small>이미지 · PDF · HWP/HWPX · DOCX · XLSX<br>파일당 20MB</small><button type="button" class="qpf-button" id="qcrChoose">파일 선택</button><input id="qcrFileInput" type="file" accept=".png,.jpg,.jpeg,.webp,.gif,.pdf,.hwp,.hwpx,.docx,.xlsx" multiple hidden></div><div class="qic-file-message">선택한 파일은 현재 신청서에 첨부됩니다.</div><div id="qcrArchiveFiles" class="qic-file-list"></div><p class="qcr-reference">기존 신청서도 구분 선택 후 ‘신청서 원본’으로 첨부할 수 있습니다.</p></section><section class="qic-record-panel"><div class="qic-record-head"><strong>신청서 목록</strong><span id="qcrCount"></span></div><div id="qcrRecords" class="qic-record-list"></div></section></aside><main class="qic-form-panel"><div id="qcrScroller" class="qic-form-scroll"><div id="qcrPaper"></div></div></main></div>`;$('dfQualityFormWorkspace').append(pane);
  $('qcrRefresh').onclick=run(async()=>{if(!discard())return;await reload();if(S.row)selectSaved(S.row.id);else newForm();render();say('최신 상태를 불러왔습니다.');});
  $('qcrNew').onclick=()=>{if(discard()){newForm();render();}};$('qcrCopy').onclick=()=>{if(!discard())return;const f={...S.form};newForm();S.form={...f,request_date:date(),author_name:profile()?.name||''};chooseTarget(f.doc_code);say('새 신청서로 복사했습니다. 첨부와 결재선을 확인하세요.');};
  $('qcrSave').onclick=run(()=>save(false));$('qcrSubmit').onclick=run(()=>save(true));$('qcrPrint').onclick=run(print);$('qcrReview').onclick=run(()=>window.DF_QCR_APPROVAL_OPEN?.(S.row.id));
  $('qcrOperation').onchange=e=>{S.form.operation=e.target.value;recalculate();render();};$('qcrTarget').onchange=run(e=>chooseTarget(e.target.value));
  $('qcrScope').onchange=e=>{S.scope=e.target.value;lists();};$('qcrYear').onchange=e=>{S.year=Number(e.target.value);S.scope='year';$('qcrScope').value='year';lists();};$('qcrSearch').oninput=e=>{S.query=e.target.value;lists();};
  $('qcrFit').onclick=()=>{S.fit=!S.fit;$('qcrFit').classList.toggle('active',S.fit);fit();};
  $('qcrChoose').onclick=e=>{e.stopPropagation();$('qcrFileInput').click();};$('qcrFileInput').onchange=run(async e=>{const files=[...e.target.files];e.target.value='';await prepare(files,$('qcrUploadRole').value);});
  const drop=$('qcrDrop');drop.onclick=e=>{if(e.target!==$('qcrFileInput')&&e.target!==$('qcrChoose')&&!$('qcrFileInput').disabled)$('qcrFileInput').click();};drop.onkeydown=e=>{if(e.target===drop&&['Enter',' '].includes(e.key)){e.preventDefault();$('qcrFileInput').click();}};
  for(const type of ['dragenter','dragover'])drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add('dragging');});for(const type of ['dragleave','drop'])drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove('dragging');});drop.addEventListener('drop',run(e=>prepare([...e.dataTransfer.files],$('qcrUploadRole').value)));
  pane.addEventListener('input',e=>{const k=e.target.dataset.qcrField;if(!k||!editable()||S.busy)return;S.form[k]=e.target.value;if(k==='from_revision'){recalculate();const to=pane.querySelector('[data-qcr-field="to_revision"]');if(to)to.value=S.form.to_revision;}$('qcrState').textContent=dirty()?'저장 전 변경사항':'저장됨';});
  pane.addEventListener('change',run(e=>{if(e.target.dataset.qcrStep!==undefined){if(editable()&&!S.busy)S.steps[Number(e.target.dataset.qcrStep)].approver_id=e.target.value;}else if(e.target.dataset.qcrField==='doc_code')chooseTarget(e.target.value);}));
  pane.addEventListener('click',run(async e=>{const b=e.target.closest('[data-qcr-record],[data-qcr-preview],[data-qcr-remove],[data-qcr-add]');if(!b||S.busy)return;if(b.dataset.qcrRecord)return select(b.dataset.qcrRecord);if(b.dataset.qcrPreview)return preview(b.dataset.qcrPreview);if(b.dataset.qcrRemove)return removeFile(b.dataset.qcrRemove);$('qcrUploadRole').value=b.dataset.qcrAdd;$('qcrFileInput').click();}));
  pane.addEventListener('load',e=>{if(['IMG','IFRAME'].includes(e.target.tagName))fit();},true);
  if(window.ResizeObserver)new ResizeObserver(fit).observe($('qcrScroller'));
 }
 async function open(id){if(S.busy)return;if(!can('view'))throw Error('작성용 품질문서 조회 권한이 없습니다.');if(S.active&&!discard())return;window.DF_QPF_FORMS.open();ensure();S.identity=me().id;S.active=true;S.ready=false;S.rows=[];S.docs=[];S.files=[];S.pending=[];S.catalog=[];newForm();$('qcrPane').hidden=false;$('qpfFolderPane').hidden=true;$('qpfLedgerPane').hidden=true;window.DF_QPF_FORMS.state.view='qpf-change';$('dfDocTitle').textContent='DFEN-QPF-02-02 (01) 품질문서 제·개·폐 신청서';$('dfDocDescription').textContent='담당자 → 책임기술자 → 품질책임자 · 비교 첨부 · 최종결재 후 REV 반영';$('dfDocBack').textContent='← 작성용 품질문서';render();say('신청서와 현재 REV 확인 중…');await reload();if(id)selectSaved(id);render();say('대상 문서와 제정·개정·폐지 구분을 선택하세요.');}
 function close(){S.active=false;S.load++;if($('qcrPane'))$('qcrPane').hidden=true;resetUrls();}
 async function approvalData(d){
  const identity=me()?.id;if(!identity)throw Error('로그인 후 확인하세요.');
  const [row,files]=await Promise.all([result(db().from('quality_change_requests').select(REQUEST_FIELDS).eq('id',d.id).single()),result(db().from('quality_change_files').select('*').eq('request_id',d.id).order('created_at'))]);
  if(me()?.id!==identity)throw Error('로그인이 변경되었습니다.');return {row,files};
 }
 async function renderApproval(target,d,steps){
  target.innerHTML='<p>신청서와 전·후 비교자료를 불러오는 중…</p>';
  try{const {row,files}=await approvalData(d);for(const f of files)await previewUrl(f);if(!target.isConnected)return;
   target.classList.add('qcr-approval-preview');target.innerHTML=sheet(true,fields(row),{files,steps})+'<div class="qcr-approval-files">'+files.map(f=>`<button type="button" data-qcr-approval-file="${esc(f.id)}">${esc(ROLES[f.role]+' · '+f.name)}</button>`).join('')+'</div>';
   target.querySelectorAll('[data-qcr-approval-file]').forEach(b=>b.onclick=async()=>{try{const f=files.find(x=>x.id===b.dataset.qcrApprovalFile),data=await blob(f);if(window.DF_QUALITY_FILE_PREVIEW)await window.DF_QUALITY_FILE_PREVIEW.open({name:f.name,mime:f.mime,size:f.size,load:()=>Promise.resolve(data)});else download(data,f.name);}catch(e){alert(e.message);}});
  }catch(e){target.textContent='신청서 불러오기 실패 · '+(e.message||e);}
 }
 async function printApproval(d,steps){
  const popup=window.open('about:blank','_blank');if(!popup)return alert('미리보기 팝업을 허용해주세요.');popup.document.body.textContent='신청서 불러오는 중…';
  try{const {row,files}=await approvalData(d);for(const f of files)await previewUrl(f);const base=new URL('.',document.baseURI).href;popup.document.open();popup.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><base href="${esc(base)}"><title>${esc(d.title)}</title><link rel="stylesheet" href="qpf_change_request.css?v=beta36"></head><body class="qcr-print"><nav><button onclick="print()">인쇄 / PDF</button></nav>${sheet(true,fields(row),{files,steps})}</body></html>`);popup.document.close();}catch(e){popup.document.body.textContent='미리보기 실패 · '+e.message;}
 }
 const navigation={capture(){return {identity:S.identity,row:S.row,form:JSON.parse(JSON.stringify(S.form)),steps:JSON.parse(JSON.stringify(S.steps)),pending:S.pending.slice(),baseline:S.baseline,year:S.year,scope:S.scope,query:S.query,draftId:S.draftId};},canLeave(){return !S.busy;},restore(v){if(v?.identity&&v.identity!==me()?.id){close();throw Error('이전 계정의 신청서는 복원할 수 없습니다. 다시 열어주세요.');}ensure();Object.assign(S,v||{});S.active=true;S.identity=me()?.id;$('qcrPane').hidden=false;window.DF_QPF_FORMS.state.view='qpf-change';$('dfDocTitle').textContent='DFEN-QPF-02-02 (01) 품질문서 제·개·폐 신청서';$('dfDocDescription').textContent='담당자 → 책임기술자 → 품질책임자 · 비교 첨부 · 최종결재 후 REV 반영';$('qcrScope').value=S.scope;$('qcrYear').value=S.year;$('qcrSearch').value=S.query;render();}};
 window.DF_QPF_CHANGE={open:run(open),close,confirmDiscard:discard,navigation,state:S,isRequest:d=>String(d?.content||'').startsWith('DF-QCR:'),openById:run(open),print:run(print),renderApproval,printApproval,_test:{cleanCode,recalculate,fields,blank,dirty,sheet,category,validForm}};
 document.addEventListener('df:menu-permissions-changed',()=>{if(me()?.id!==S.identity||!can('view')){close();S.rows=[];S.docs=[];S.files=[];S.people=[];S.ready=false;}if(S.active)render();});
 document.addEventListener('df:quality-revision-changed',run(async()=>{if(S.active&&!S.busy&&!dirty()){const id=S.row?.id;await reload();if(id)selectSaved(id);render();}}));
 window.addEventListener('beforeunload',e=>{if(S.active&&(S.busy||dirty())){e.preventDefault();e.returnValue='';}});
})();
