/* Beta 3.12.3 · Import the original HWP 5 equipment-ledger table, cells and pictures. */
(function(){'use strict';
 const unit=n=>n*25.4/7200,decoder=new TextDecoder('utf-16le');
 const dv=a=>new DataView(a.buffer,a.byteOffset,a.byteLength),color=(a,o)=>'#'+[a[o],a[o+1],a[o+2]].map(x=>(x||0).toString(16).padStart(2,'0')).join('');
 function records(a){const out=[];let p=0;while(p<a.length){if(p+4>a.length)throw Error('HWP 레코드가 손상되었습니다.');const h=dv(a).getUint32(p,true);p+=4;let n=h>>>20;if(n===4095){if(p+4>a.length)throw Error('HWP 레코드를 확인해주세요.');n=dv(a).getUint32(p,true);p+=4;}if(p+n>a.length||out.length>50000)throw Error('HWP 구성요소 범위를 확인해주세요.');out.push({tag:h&1023,level:(h>>>10)&1023,bytes:a.subarray(p,p+n)});p+=n;}return out;}
 async function rawInflate(bytes){const reader=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader();const chunks=[];let total=0;try{while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>50*1024*1024)throw Error('압축 해제된 HWP 구성요소가 너무 큽니다.');chunks.push(value);}}finally{await reader.cancel().catch(()=>{});}const a=new Uint8Array(total);let p=0;for(const c of chunks){a.set(c,p);p+=c.length;}return a;}
 async function inflate(bytes){try{return await rawInflate(bytes);}catch(e){if(!/Junk found after end/.test(e.message)||bytes.length<9)throw e;const expected=dv(bytes).getUint32(bytes.length-4,true);if(expected>50*1024*1024)throw Error('압축 해제 크기가 너무 큽니다.');const out=await rawInflate(bytes.subarray(0,-8));if(out.length!==expected)throw Error('HWP 압축 크기가 일치하지 않습니다.');return out;}}
 function text(a){let out='';for(let p=0;p+1<a.length;){const c=dv(a).getUint16(p,true);if(c<32){if(c===10)out+='\n';if(c===9||c===30||c===31)out+=' ';if(c===24)out+='-';p+=[1,2,3,4,5,6,7,8,9,11,12,14,15,16,17,18,19,20,21,22,23].includes(c)?16:2;}else{out+=String.fromCharCode(c===0xf09e?0xb7:c);p+=2;}}return out;}
 const normalized=s=>String(s).replace(/[\s·.\-\/]/g,'');
 const labels={equipment_name:'장비명',equipment_code:'관리번호',model:'모델명',serial_no:'SNo',purpose:'용도',manufacturer:'제조사',purchase_date:'구입일자',purchase_price:'구입금액',department:'관리부서',last_inspection:'검교정일자',next_inspection:'차기검교정일자',specification:'제원및사양'};
 function fieldMap(cells){const map={};for(const [k,label] of Object.entries(labels)){const cell=cells.find(c=>normalized(c.text)===label);if(cell){const value=cells.find(c=>c.r===cell.r&&c.c===cell.c+cell.cs);if(value)map[k]=cells.indexOf(value);}}return map;}
 function bounds(cells,n,key,span,size){const edges=cells.filter(c=>c[size]>0).sort((a,b)=>a[span]-b[span]),out=Array(n+1).fill(null);out[0]=0;for(let pass=0;pass<n+2;pass++){for(const c of edges){const a=c[key],b=a+c[span];if(b>n)throw Error('표의 병합 범위를 확인해주세요.');if(out[a]!==null&&out[b]===null)out[b]=out[a]+c[size];else if(out[b]!==null&&out[a]===null)out[a]=out[b]-c[size];}}if(out[n]===null)throw Error('이 문서의 표 크기를 해석하지 못했습니다.');for(let a=0;a<n;){let b=a+1;while(b<=n&&out[b]===null)b++;for(let j=a+1;j<b;j++)out[j]=out[a]+(out[b]-out[a])*(j-a)/(b-a);a=b;}if(out.some((x,i)=>i&&x<out[i-1]))throw Error('이 문서의 표 배치를 해석하지 못했습니다.');return out;}
 // BinData has its own compression mode; JPEGs may be raw inside a compressed HWP.
 function binaryInfo(a){if(a.length<2)throw Error('HWP 사진 속성이 손상되었습니다.');const v=dv(a),flags=v.getUint16(0,true),type=flags&15,compression=flags>>>4&3;if(type===0)return {type,compression};if(![1,2].includes(type)||a.length<4)throw Error('HWP 사진 저장 정보를 확인해주세요.');return {type,compression,id:v.getUint16(2,true)};}
 async function pictureBytes(item,meta,compressed){if(!meta||meta.type===0)throw Error('외부 연결 사진은 한글 문서 안에 포함한 뒤 다시 불러와주세요.');if(meta.compression===3)throw Error('지원하지 않는 HWP 사진 압축 방식입니다.');const unzip=meta.compression===1||(meta.compression===0&&compressed);try{return unzip?await inflate(item.bytes):item.bytes;}catch(e){throw Error('문서 사진의 압축 데이터를 읽지 못했습니다. 한글에서 다시 저장한 파일로 시도해주세요. ('+e.message+')');}}
 function pictureType(a){if(a[0]===66&&a[1]===77)return 'image/bmp';if(a[0]===255&&a[1]===216&&a[2]===255)return 'image/jpeg';if(a[0]===137&&a[1]===80&&a[2]===78&&a[3]===71)return 'image/png';if(String.fromCharCode(...a.subarray(0,6)).match(/^GIF8[79]a$/))return 'image/gif';throw Error('문서 안의 사진 형식을 읽지 못했습니다. JPG·PNG·BMP·GIF 사진을 사용해주세요.');}
 function tableGrid(t){if(!t.rows||!t.cols||t.rows>80||t.cols>30)throw Error('문서 표의 행·열 범위를 확인해주세요.');return {...t,xs:bounds(t.cells,t.cols,'c','cs','w'),ys:bounds(t.cells,t.rows,'r','rs','h')};}
 // Keep separate history tables in the same editable cell model, including their original gap.
 function joinTables(main,tables){const parts=tables.filter(t=>t===main||(t.level===main.level&&tables.indexOf(t)>tables.indexOf(main)&&!t.cells.some(c=>c.text.includes('DFEN-QPF-13-01')))).map(tableGrid),first=parts[0];if(parts.length===1)return first;
  const xs=[],cells=[],ys=[...first.ys];for(const t of parts){t.dx=(t.origin?.x||0)-(first.origin?.x||0);for(const x of t.xs.map(x=>x+t.dx))if(!xs.some(v=>Math.abs(v-x)<.06))xs.push(x);}xs.sort((a,b)=>a-b);if(xs[0]<-.06||xs.length>31)throw Error('문서 표의 가로 배치를 확인해주세요.');const xi=x=>xs.findIndex(v=>Math.abs(v-x)<.06);
  for(const [index,t] of parts.entries()){let row=0;if(index){const top=t.origin?.y-first.origin?.y;if(!Number.isFinite(top)||top<ys.at(-1)-.06)throw Error('여러 표의 배치가 겹칩니다. 한글에서 표 위치를 확인해주세요.');if(top>ys.at(-1)+.06){cells.push({r:ys.length-1,c:0,rs:1,cs:xs.length-1,w:xs.at(-1),h:top-ys.at(-1),text:'',style:{},picture:null,spacer:true});ys.push(top);}row=ys.length-1;ys.push(...t.ys.slice(1).map(y=>top+y));}
   for(const c of t.cells){const left=xi(t.xs[c.c]+t.dx),right=xi(t.xs[c.c+c.cs]+t.dx);cells.push({...c,r:c.r+row,c:left,cs:right-left,spacer:!c.text&&!c.picture&&!(c.style.edges||[]).some(e=>e.kind!=='none')});}}
  if(cells.length>500||ys.length>81)throw Error('장비관리대장의 표 범위를 확인해주세요.');return {rows:ys.length-1,cols:xs.length-1,xs,ys,cells};
 }
 // Cropping uses the picture's native extent, not its insertion rectangle (which may use a different DPI).
 function pictureLayout(a,shape){const v=dv(a);let w=v.getInt32(20,true),h=v.getInt32(32,true);if(a.length>=90&&v.getUint32(78,true)===0){const nativeW=v.getInt32(82,true),nativeH=v.getInt32(86,true);if(nativeW>0&&nativeH>0){w=nativeW;h=nativeH;}}const [left,top,right,bottom]=[44,48,52,56].map(o=>v.getInt32(o,true));return {kind:'source',bin:v.getUint16(71,true),angle:shape?.angle||0,aspect:shape?.w>0&&shape?.h>0?shape.w/shape.h:null,crop:w>0&&h>0&&right>left&&bottom>top?[left/w,top/h,(right-left)/w,(bottom-top)/h]:[0,0,1,1]};}
 async function parse(file){
  if(!/\.hwp$/i.test(file.name)||!file.size||file.size>20*1024*1024)throw Error('20MB 이내 HWP 장비관리대장을 선택해주세요.');
  if(!window.XLSX?.CFB)throw Error('한글 읽기 구성요소를 불러오지 못했습니다. 새로고침해주세요.');
  const raw=new Uint8Array(await file.arrayBuffer()),cfb=XLSX.CFB.read(raw,{type:'array'}),entries=cfb.FileIndex.map((v,i)=>({name:(cfb.FullPaths[i]||v.name).replace(/^[^/]+\//,''),bytes:new Uint8Array(v.content||[])}));
  const get=n=>entries.find(e=>e.name===n)?.bytes,header=get('FileHeader');if(!header||new TextDecoder().decode(header.subarray(0,17))!=='HWP Document File')throw Error('HWP 5 형식의 장비관리대장이 아닙니다.');
  const flags=dv(header).getUint32(36,true);if(flags&6)throw Error('암호 또는 배포용 보호를 해제한 HWP 파일을 사용해주세요.');const decompress=async a=>flags&1?inflate(a):a;
  const docInfo=records(await decompress(get('DocInfo'))),borders=[],chars=[],paras=[],bins=[];
  const weights=[.1,.12,.15,.2,.25,.3,.4,.5,.6,.7,1,1.5,2,3,4,5];
  for(const r of docInfo){const a=r.bytes,v=dv(a);if(r.tag===18)bins.push(binaryInfo(a));else if(r.tag===20){const edges=[];for(let i=0;i<4;i++){const o=2+i*6;edges.push({kind:a[o]===0?'none':a[o]>=8?'double':a[o]===3?'dotted':a[o]===2?'dashed':'solid',width:weights[a[o+1]]||.1,color:color(a,o+2)});}borders.push({edges,background:a.length>=40&&(v.getUint32(32,true)&1)?color(a,36):'#ffffff'});}else if(r.tag===21&&a.length>=56)chars.push({font:Math.max(5,Math.min(28,v.getInt32(42,true)/100)),bold:!!(v.getUint32(46,true)&2),color:color(a,52)});else if(r.tag===25)paras.push({align:['justify','left','right','center'][v.getUint32(0,true)>>>2&7]||'left'});}
  const sections=entries.filter(e=>/^BodyText\/Section\d+$/.test(e.name));if(sections.length!==1)throw Error('현재 장비관리대장은 원본과 같은 단일 구역의 A4 양식을 지원합니다.');
  const recs=records(await decompress(sections[0].bytes));let active=null,cell=null,shape=null,para=0,flowY=0,paraY=0;const tables=[],tableControls=new Map();
  for(const r of recs){const a=r.bytes,v=dv(a);if(r.tag===66&&r.level===0)paraY=flowY;if(r.tag===69&&r.level===1){for(let o=0;o+36<=a.length;o+=36)flowY=Math.max(flowY,unit(v.getInt32(o+4,true)+v.getInt32(o+8,true)+v.getInt32(o+20,true)));}if(r.tag===71&&a.length>=24&&v.getUint32(0,true)===0x74626c20)tableControls.set(r.level,{x:unit(v.getInt32(12,true)),y:paraY+unit(v.getInt32(8,true))});if(active&&r.level<active.level){active=null;cell=null;}if(r.tag===77){active={level:r.level,origin:tableControls.get(r.level-1),rows:v.getUint16(4,true),cols:v.getUint16(6,true),cells:[]};tables.push(active);cell=null;}else if(active&&r.tag===72&&r.level===active.level&&a.length>=34){cell={r:v.getUint16(10,true),c:v.getUint16(8,true),cs:v.getUint16(12,true),rs:v.getUint16(14,true),w:unit(v.getUint32(16,true)),h:unit(v.getUint32(20,true)),text:'',paragraphs:[],style:{...(borders[v.getUint16(32,true)-1]||{})},picture:null};active.cells.push(cell);}else if(cell&&r.tag===66&&r.level===active.level){para=v.getUint16(8,true);cell.style.align=paras[para]?.align||'center';}else if(cell&&r.tag===67&&r.level===active.level+1){cell.paragraphs.push(text(a));}else if(cell&&r.tag===68&&r.level===active.level+1&&a.length>=8){Object.assign(cell.style,chars[v.getUint32(4,true)]||{});}else if(cell&&r.tag===69&&r.level===active.level+1&&a.length>=36&&cell.h===0){cell.h=unit(v.getInt32(4,true)+v.getInt32(8,true)+282);}else if(r.tag===76&&a.length>=46){const base=a[0]===a[4]&&a[1]===a[5]?8:4;shape={angle:v.getUint16(base+32,true)%360,w:v.getUint32(base+20,true),h:v.getUint32(base+24,true)};}else if(cell&&r.tag===85&&a.length>=73){cell.picture=pictureLayout(a,shape);}}
  for(const t of tables)for(const c of t.cells){c.text=c.paragraphs.join('\n').trim();delete c.paragraphs;}
  const main=tables.find(t=>t.cells.some(c=>normalized(c.text)==='장비관리대장'));
  if(!main||main.cells.length>250||main.rows>80||main.cols>30)throw Error('DFEN-QPF-13-01 장비관리대장 양식을 확인해주세요.');
  const fields=fieldMap(main.cells);if(Object.keys(fields).length!==Object.keys(labels).length)throw Error('원본의 장비명·관리번호·검교정일·제원 등 필수 칸을 찾지 못했습니다.');
  main.cells[fields.purchase_price].text=main.cells[fields.purchase_price].text.replace(/^\\(?=\s*\d)/,'₩');
  const grid=joinTables(main,tables),{xs,ys}=grid;const mergedFields=fieldMap(grid.cells);
  const used=new Set(grid.cells.filter(c=>c.picture).map(c=>c.picture.bin)),pictures=new Map();let total=0;
  for(const bin of used){const meta=bins[bin-1];if(!meta||meta.type===0)throw Error('문서 안에 포함된 사진만 불러올 수 있습니다.');const item=entries.find(e=>new RegExp('^BinData/BIN'+meta.id.toString(16).padStart(4,'0')+'\\.','i').test(e.name));if(!item)throw Error('문서 안의 사진 원본이 없습니다.');const a=await pictureBytes(item,meta,!!(flags&1));total+=a.length;if(total>70*1024*1024)throw Error('문서 사진 크기가 너무 큽니다.');pictures.set(bin,new Blob([a],{type:pictureType(a)}));}
  const footer=tables.find(t=>t!==main&&t.cells.some(c=>c.text.includes('DFEN-QPF-13-01')))?.cells.map(c=>c.text).filter(Boolean)||['DFEN-QPF-13-01','Rev. 00','- 주식회사 드림포이엔 -','A4(210×297mm)'];
  const doc={schema:1,page:{width:210,height:297,left:13,top:15.4},table:{rows:grid.rows,cols:grid.cols,xs,ys,cells:grid.cells},fields:mergedFields,footer};if(xs.at(-1)>190||ys.at(-1)>264)throw Error('A4 한 페이지 범위를 벗어나는 양식입니다.');
  return {doc,pictures,raw,file,preview:get('PrvImage'),code:main.cells[fields.equipment_code].text.trim().toUpperCase()};
 }
 window.DF_EQ_LEDGER_IMPORT={parse,fieldMap,_test:{records,text,bounds,binaryInfo,pictureBytes,pictureLayout}};
})();
