// DREAMFOREN v120.22 Excel-based sample record beta
(function(){
  'use strict';
  let book=null;const el=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function cellStyle(cell){const s=cell?.s||{},font=s.font||{},fill=s.fill||{},align=s.alignment||{},css=[];if(font.bold)css.push('font-weight:700');if(font.sz)css.push(`font-size:${Math.max(8,Math.min(18,font.sz))}px`);if(font.color?.rgb)css.push(`color:#${font.color.rgb.slice(-6)}`);if(fill.fgColor?.rgb)css.push(`background:#${fill.fgColor.rgb.slice(-6)}`);if(align.horizontal)css.push(`text-align:${align.horizontal==='centerContinuous'?'center':align.horizontal}`);if(align.vertical)css.push(`vertical-align:${align.vertical}`);if(align.wrapText)css.push('white-space:pre-wrap');return css.join(';')}
  function render(){const name=el('dfSampleBetaSheet')?.value||book?.SheetNames?.[0],ws=book?.Sheets?.[name],box=el('dfSampleBetaCanvas');if(!ws||!box)return;let range=XLSX.utils.decode_range(ws['!ref']||'A1:A1');if(name==='기록지(먼지)')range=XLSX.utils.decode_range('E1:R50');const merges=(ws['!merges']||[]).filter(m=>m.e.r>=range.s.r&&m.s.r<=range.e.r&&m.e.c>=range.s.c&&m.s.c<=range.e.c),covered=new Set(),starts=new Map();for(const m of merges){const sr=Math.max(m.s.r,range.s.r),sc=Math.max(m.s.c,range.s.c),er=Math.min(m.e.r,range.e.r),ec=Math.min(m.e.c,range.e.c);starts.set(`${sr}:${sc}`,{rowspan:er-sr+1,colspan:ec-sc+1});for(let r=sr;r<=er;r++)for(let c=sc;c<=ec;c++)if(r!==sr||c!==sc)covered.add(`${r}:${c}`)}const cols=[];for(let c=range.s.c;c<=range.e.c;c++){const w=ws['!cols']?.[c]?.wpx||Math.round((ws['!cols']?.[c]?.wch||10)*7);cols.push(`<col style="width:${Math.max(35,w)}px">`)}let html=`<table class="df-beta-sheet"><colgroup>${cols.join('')}</colgroup><tbody>`;for(let r=range.s.r;r<=range.e.r;r++){const h=ws['!rows']?.[r]?.hpx||Math.round((ws['!rows']?.[r]?.hpt||15)*1.33);html+=`<tr style="height:${Math.max(18,h)}px">`;for(let c=range.s.c;c<=range.e.c;c++){if(covered.has(`${r}:${c}`))continue;const addr=XLSX.utils.encode_cell({r,c}),cell=ws[addr],merge=starts.get(`${r}:${c}`),value=cell?.w??cell?.v??'',formula=cell?.f?` title="수식: ${esc(cell.f)}"`:'';html+=`<td${merge?` rowspan="${merge.rowspan}" colspan="${merge.colspan}"`:''}${formula} style="${cellStyle(cell)}">${esc(value).replace(/\n/g,'<br>')}</td>`}html+='</tr>'}html+='</tbody></table>';box.innerHTML=html;el('dfSampleBetaStatus').textContent=`${name} · Excel 원본 범위 ${XLSX.utils.encode_range(range)} 표시`}
  async function load(){const status=el('dfSampleBetaStatus');if(status)status.textContent='Excel 원본을 불러오는 중입니다.';try{const res=await fetch('assets/dreampoen_record_template.xlsm?v=12022000');if(!res.ok)throw Error(`원본 파일 응답 ${res.status}`);book=XLSX.read(await res.arrayBuffer(),{type:'array',cellStyles:true,cellDates:true});const select=el('dfSampleBetaSheet');select.innerHTML=book.SheetNames.map(n=>`<option value="${esc(n)}" ${n==='기록지(먼지)'?'selected':''}>${esc(n)}</option>`).join('');render()}catch(e){if(status)status.textContent='Excel 원본을 불러오지 못했습니다: '+e.message;window.DF_DIAG?.error('SAMPLE-BETA','Excel 원본 표시 실패',e.message||String(e))}}
  document.addEventListener('DOMContentLoaded',()=>{el('dfSampleBetaSheet')?.addEventListener('change',render);el('dfSampleBetaReload')?.addEventListener('click',load);document.querySelector('[data-view="sample-beta"]')?.addEventListener('click',()=>{if(!book)setTimeout(load,200)});window.DF_DIAG?.info('SAMPLE-BETA','Excel 원본 기반 시료채취기록지 BETA 준비 완료')},{once:true});
})();
